### ISSUE TITLE
规则仓库更新规则时显示错误

### ISSUE THREAD

**Issue by Thesouth-EricWang** [Predidit/Kazumi#10]
在规则仓库页面点击更新时会导致其他规则部分被错误显示为未安装，具体情况见图片
![Screenshot_2024-06-27-11-19-51-330_com predidit kazumi](https://github.com/Predidit/Kazumi/assets/109672389/46111afe-023a-49f2-a31a-45e8fb266f76)
![Screenshot_2024-06-27-11-19-57-533_com predidit kazumi](https://github.com/Predidit/Kazumi/assets/109672389/60f7878d-c6c0-48a2-8d15-bc9b36f3c90f)
复现方法:进入规则仓库，点击图片中规则的更新按钮

**Comment by Predidit** [comment]
在退出这个页面后，规则实际上被正确安装了吗。

**Comment by Predidit** [comment]
补丁已经提交到仓库，等待下一次版本发布
