### ISSUE TITLE
关于播放器界面对观感的影响

### ISSUE THREAD

**Issue by yingheshiyu** [Predidit/Kazumi#103]
### issue 内容

点击屏幕播放器的界面唤起之后再次点击屏幕无法隐藏，要等几秒才能隐藏
暂停会一直不隐藏

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这两点都不是 Bug 目前的设计本来就是这样的。

不过这两条修改预期会与播放器界面的过渡动画一同到来。
