### ISSUE TITLE
[Bug]: 顶部弹幕有时候会到中间

### ISSUE THREAD

**Issue by madoka773** [Predidit/Kazumi#105]
### 在使用的时候发生了什么 Bug ？

顶部弹幕有时候会到中间

### 您在使用哪个操作系统？

Linux

### 请具体提供设备、版本号等信息。

Fedora Silverblue 40 
Kazumi 1.2.5

### （选填）一些与 Bug 相关的硬件信息。

![截图 2024-08-01 18-53-11](https://github.com/user-attachments/assets/07f1b0cc-6218-4d9a-8ea2-503d356d0ab5)
![截图 2024-08-01 18-54-27](https://github.com/user-attachments/assets/4a138f93-e2c8-4138-bd23-cbf2bec6d57e)

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这个问题来自弹幕库 [Predidit/canvas_danmaku](https://github.com/Predidit/canvas_danmaku)

这是当时我在编写时的取舍。为了效率，并没有在每帧，而是只有当新的弹幕加入屏幕时才会计算已有弹幕是否应该被移除，在顶部弹幕的处理中，这导致了一个问题。

如果我在新加入屏幕时移除过期弹幕，那么将永远不会出现B站那种顶部弹幕偶尔错行(上方弹幕已经消失，但下方弹幕还未消失而出现空行)的效果。

如果我先移除过期弹幕，再加入新弹幕，那么就是现在这样，虽然有B站的错行效果，但是发生频率太高了。

你觉得哪种处理好一点，或是其他的方法？

**Comment by madoka773** [comment]
我是觉得现在发生的频率太高了，总是有弹幕糊在中间。
编程的问题我不懂，如果能减少发生这种状况的频率就挺好了，具体看作者取舍

**Comment by Predidit** [comment]
你觉得问题的关键是在于错行，还是顶部和底部的弹幕不受弹幕区域设置的制约呢

**Comment by madoka773** [comment]
测试用的视频是girigirilove源的《败犬女主太多了！》播放列表2，第一话

**Comment by Predidit** [comment]
你尝试过关闭底部弹幕吗，这样还会有那么离谱的错行吗。

**Comment by madoka773** [comment]
> 你尝试过关闭底部弹幕吗，这样还会有那么离谱的错行吗。

好像找到问题所在了

**Comment by Predidit** [comment]
我现在认为这是一个不需要修复的预期行为。

我刚刚看了一下B站的方案，在弹幕不是满屏的情况下会自动禁用底部弹幕。这个特性我会在后续加入。
