### ISSUE TITLE
[Bug]: 部分番剧的视频源在除搜索结果以外的场景下无法加载

### ISSUE THREAD

**Issue by ymqng** [Predidit/Kazumi#107]
### 第一个
在搜索界面搜索“鹿乃子……”后得到结果，点击此番剧详情页视频源可正常加载。
追番此番剧后前往追番界面点开番剧详情页，大部分视频源无法正常加载。
回到搜索界面，再次点开番剧详情页，出现了与上述相同的视频源无法正常加载的情况。

### 第二个
在第二次回到搜索界面时，上方搜索框消失，但搜索结果依然存在。

### 第三个
正常使用软件且网络正常时，软件会经常提示“网络异常”，但提示时软件可正常使用。

上述操作均未使用梯子，且网络质量良好。

### 附演示视频两个

https://github.com/user-attachments/assets/e7706fc3-95f5-4fbe-a16a-6067f2d366dc

https://github.com/user-attachments/assets/e665fde9-69bd-4edb-ac0e-9c86ae42d2e4

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

** Android 10 **

### 日志信息

```shell
无错误日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
1. 和 #53 重复
2. 这是一个预期行为
3. 任何网络连接没有返回预期结果都会出现此提示，也就是说只要有任意视频源出现问题，便会出现此提示。尝试移除不稳定的视频源。

**Comment by ymqng** [comment]
> 1. 和 [在时间表那里点进去看番，有些番的某个源就看不了，而搜索出来的番的片源却正常显示 #53](https://github.com/Predidit/Kazumi/issues/53) 重复
> 2. 这是一个预期行为
> 3. 任何网络连接没有返回预期结果都会出现此提示，也就是说只要有任意视频源出现问题，便会出现此提示。尝试移除不稳定的视频源。

抱歉啊，#53 在比较考后的位置且不是打开状态，没看到。
