### ISSUE TITLE
感谢话语

### ISSUE THREAD

**Issue by vpatter** [Predidit/Kazumi#11]
开源作者你好，非常感谢你和其他参与项目的人的付出，由于我是个小白以及我没有经验，我无法参与项目的开发，所以只能作感谢，毕竟国内 github 开发者本来就少，基本上不是被垄断就是被各种找麻烦，所以我很珍惜和感谢你们的默默付出，无论做得程度如何，我都觉得这是好的，且不错的，属于是一股清流了。
另外，再次感谢！

**Comment by Predidit** [comment]
感谢您的支持。

如果您有兴趣的话，可以向我们贡献规则，这是非常容易的，让我们一起让这个项目变得更好。
