### ISSUE TITLE
[Bug]: Callback received: The number of iframe tags is0If there is audio but no video, please report it to the rule developer.

### ISSUE THREAD

**Issue by ENE4546** [Predidit/Kazumi#112]
### 在使用的时候发生了什么 Bug ？

我什么规则都没设置都是默认的，点任意的番都出现这种情况，咱也不知道怎么使用
![PixPin_2024-08-04_23-22-49](https://github.com/user-attachments/assets/1e9f8946-3eaa-4f61-977c-00ac69a12d68)
![PixPin_2024-08-04_23-23-42](https://github.com/user-attachments/assets/a3705479-15d2-466f-acee-f3a39985b47c)
![image](https://github.com/user-attachments/assets/938e2cff-d813-4920-8dbf-85879c84a783)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

windows 10

### 日志信息

```shell
错误日志没有数据
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
和 #109 重复。

前面那些是正常的日志输出。如果出现视频源解析失败的提示，可以返回上一级页面，选择其他视频源。

尽量不要用代理访问，大部分视频源基于它们自己的考量，都屏蔽日本和北美的访问。

如果还是不可用，可以在规则仓库开Issue报告失效的规则。
