### ISSUE TITLE
[Bug]: IOS视频声音消失

### ISSUE THREAD

**Issue by zhizu11** [Predidit/Kazumi#115]
### 在使用的时候发生了什么 Bug ？

在点击一个番剧,加载完成后,视频正常播放也有声音,但只要进行操作后声音就突然消失了,如点击画面区域,横屏后点击画面区域,声音就会突然消失,只有重启app才可以修复

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

IPHONE13

### 日志信息

```shell
日志没有显示相关内容
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
全屏状态下能通过上下滑动右半边屏幕来调节音量吗。

**Comment by zhizu11** [comment]
> 全屏状态下能通过上下滑动右半边屏幕来调节音量吗。

可以调节大小，而且是系统音量，但是无效，还是没有声音

**Comment by Predidit** [comment]
> > 全屏状态下能通过上下滑动右半边屏幕来调节音量吗。
> 
> 可以调节大小，而且是系统音量，但是无效，还是没有声音

设置选项卡的播放设置，尝试禁用硬件解码

**Comment by zhizu11** [comment]
> > > 全屏状态下能通过上下滑动右半边屏幕来调节音量吗。
> > 
> > 
> > 可以调节大小，而且是系统音量，但是无效，还是没有声音
> 
> 设置选项卡的播放设置，尝试禁用硬件解码

在我关闭硬件解码，并且重启软件后，点击视频后播放，甚至不需要操作，直接失去声音

**Comment by zhizu11** [comment]
> > > 全屏状态下能通过上下滑动右半边屏幕来调节音量吗。
> > 
> > 
> > 可以调节大小，而且是系统音量，但是无效，还是没有声音
> 
> 设置选项卡的播放设置，尝试禁用硬件解码

我似乎找到问题了，在IOS开启静音模式会失去声音，关闭静音模式才有声音

**Comment by Predidit** [comment]
1.3.1 解决了这一问题，现在静音模式下也有声音
