### ISSUE TITLE
为什么我使用webdav同步不生效?

### ISSUE THREAD

**Issue by biusp** [Predidit/Kazumi#116]
### issue 内容

webdav里kazumiSync文件夹创建了,但是没有任何文件

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
同步在退出播放器页面时触发，以及确定 webdav 同步开关打开，以及 webdav 服务端的写入权限正确。

**Comment by biusp** [comment]
同步有时生效有时不生效,大部分时间是不生效的;
错误日志如下:
**2024-08-09 12:43:35.305191** 
 webDav backup diretory create failed 
 null
