### ISSUE TITLE
native播放器 部分规则的播放地址解析不正确

### ISSUE THREAD

**Issue by biusp** [Predidit/Kazumi#117]
### issue 内容

之前clicli规则编写时发现无法使用native播放器,研究了一下发现:
![image](https://github.com/user-attachments/assets/ec5fbe88-66a4-4fcd-a820-2a344c702320)
它只解析到了https://www.clicli.pro/addons/dp/player/dp.php?key=0&from=&id=5&api=&url=https://vod.2bdm.cc/2024/07/25cydyh/01.mp4&jump= 这个地址
但是我通过网页爬取发现实际的播放地址是https://vod.2bdm.cc/2024/07/25cydyh/01.mp4?verify=1723179574-HvcptN...........
之间的一次跳转native好像无法获取

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
Kazumi 的设计是这样的，在定位到播放器所在 iframe 之后，会拉起一个无头 webview 来访问 iframe ，webview 拥有所有的浏览器功能，所以他可以通过各种加密校验。然后我们使用一些有趣的 javascript 魔术来截取接下来要请求的视频流，成功之后 webview 被销毁，视频流交给内嵌播放器播放。

上图的 Parsing video source 是要解析的 iframe 而不是视频流本身。实际上获取的视频流的地址是绝对正确的，只不过没有打印在日志中。 打印日志是 webview 阶段，当开始转圈后，即进入内嵌播放器阶段。

那为什么播放不了呢，我刚刚检查了一下这条规则，看上去它和次元城的播放器是完全相同的。他们在影片加载完成，可以播放第一帧前，向服务器发送一次回调，标记当前视频流为可用状态，如果没有这个标记，视频流不可用。

为了效率，Kazumi在解析出视频地址后会立即销毁 webview 并拉起内嵌播放器。这时视频还没开始加载，回调也尚未发出，所以视频流无效。

如果一定要等这个回调，解析会大概慢5秒，这在我看来是无法接受的。
