### ISSUE TITLE
为什么老是会显示服务器异常

### ISSUE THREAD

**Issue by love-Yui** [Predidit/Kazumi#118]
### issue 内容

![Screenshot_2024-08-10-21-04-47-992_com predidit kazumi](https://github.com/user-attachments/assets/5d544ae6-80fb-4682-93f8-4f827f85edf7)
正常使用搜索栏搜索任意的番名然后添加喜欢就会报服务器异常，有时真正观看的过程中也会报异常，版本是1.2.5，求大佬解决

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这和追番没有关系，添加的规则太多了，只要有任意规则的请求失败就会触发错误提示，选几条自己觉得好用的规则就可以了，这样视频源的负载也小一点。

**Comment by love-Yui** [comment]
好的我去试试，可能是我添加太多了，谢谢


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月10日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Predidit/Kazumi] 为什么老是会显示服务器异常 (Issue #118) |

这和追番没有关系，添加的规则太多了，只要有任意规则的请求失败就会触发错误提示，选几条自己觉得好用的规则就可以了，这样视频源的负载也小一点。
