### ISSUE TITLE
windows10下全屏播放无法隐藏底部状态栏

### ISSUE THREAD

**Issue by kazane1998** [Predidit/Kazumi#119]
### issue 内容

下载的windows 1.2.6版本，全屏播放时底部栏无法隐藏，不知是否是我操作问题？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
使用软件内的全屏按钮全屏，不要使用 windows 的最大化快捷键。

**Comment by zmy15501525166** [comment]
![QQ截图20240811121721](https://github.com/user-attachments/assets/04c72358-6f63-4673-a177-dbe19519bf88)
![QQ截图20240811121748](https://github.com/user-attachments/assets/f702b03d-1dec-4f1f-88a8-a12dff5146f0)
![QQ截图20240811121706](https://github.com/user-attachments/assets/8c7243ab-2891-4d8a-927d-550cb1c91bde)
使用的是这个全屏按钮，但是底部无法隐藏

**Comment by Predidit** [comment]
我不知道为什么会这样，可能的原因很多，包括一些嵌入到任务栏中的插件。

不幸的是，我没有 win10 设备可供测试，目前我无法在 win11 上复现这一问题。

**Comment by zmy15501525166** [comment]
谢谢！我暂时的解决办法是将底部栏在Windows里设置为默认隐藏

**Comment by X-Fei-D** [comment]
win11, 1.3.2最新版本，也出现此问题。

**Comment by Predidit** [comment]
@X-Fei-D @kazane1998 

我高度怀疑是注入资源管理器的第三方插件(例如联想电脑管家/360驻留任务栏的电池管理)改变了任务栏的默认行为，这些插件毫无意义，并且引入了额外的缺陷和不稳定。

但考虑到使用这些插件使用范围很广，我做了一个简单的 workaround 来兼容这些场景，尝试以下的实验性构建是否修复问题

https://github.com/Predidit/Kazumi/actions/runs/10957431166/artifacts/1957609391

**Comment by X-Fei-D** [comment]
@Predidit 我测试了下链接中的版本，很好地解决了问题，非常感谢。

**Comment by Predidit** [comment]
包含此补丁的 1.3.3 已经发布
