### ISSUE TITLE
导入番剧

### ISSUE THREAD

**Issue by UF4OVER** [Predidit/Kazumi#12]
能不能一键导入<b>囧次元</b>中看过的番剧

**Comment by Predidit** [comment]
跟踪与同步追番进度在开发计划中。

目前的打算是使用 bangumi 番组计划 或者 aniList 进行同步，他们都提供了开放平台与API供第三方开发者使用。

类似于囧次元这种来源可疑的第三方站点，我们无法保证相关数据的安全性，他们也不不可能向我们提供API接口，我们固然可以通过一些hack的手段实现目的，但是会非常不稳定，

综上，没有同步囧次元追番进度的计划。
