### ISSUE TITLE
增加弹幕源选择功能

### ISSUE THREAD

**Issue by kazuyaalex** [Predidit/Kazumi#122]
### issue 内容

有些番b站有，现在弹幕功能默认获取所有网站的弹幕就会把b站的弹幕都弄过来，太哈人了，刷得很多又弱智，最近看败犬女主不知道怎么的获取到b站的弹幕，明明b站官方没有上这个番。弹弹play原本在添加弹幕时就可以选择弹幕源，实现这个功能应该很容易。

**Comment by Predidit** [comment]
这个功能可以实现，应该会包含在下个版本中。

不过我看了一下，败犬女主里的简体弹幕来自DanDanPlay本身，是DanDanPlay的用户发的。

**Comment by kazuyaalex** [comment]
> 不过我看了一下，败犬女主里的简体弹幕来自DanDanPlay本身，是DanDanPlay的用户发的。

昨晚我看的时候确实是有b站的，我专门开了弹弹play的app搜弹幕确认了，过一段时间后就没了，估计是b站那边盗传的动画视频被下架了就没了，不知道弹弹play怎么会搜到那些小up盗传动画的弹幕

**Comment by Predidit** [comment]
此功能在 1.2.7 加入
