### ISSUE TITLE
网站番剧集数显示与kazimi中集数显示不一致时导致弹幕不匹配的问题

### ISSUE THREAD

**Issue by SCP-XC** [Predidit/Kazumi#123]
### issue 内容

你好，我在kazumi中观看《我独自升级》第8集（kazumi显示共13集），发现弹幕与剧情内容不相符，去原视频网站上发现，存在一个7.5集的情况（该集为总结前七集的内容，没有新的剧情，A1公司貌似很多番都这么搞），共12集的剧情实际有13个视频（因为包括了7.5集），也因此在kazumi中显示13集（kazumi只显示整数集），这样导致kazumi播放第8集（实际播放第7.5集）的弹幕是原第8集的弹幕，kazumi播放第9集（实际播放第8集）显示的弹幕实际是第9集的弹幕，往后都是如此。kazumi播放第13集（实际第12集）则找不到弹幕源。

另外，关于弹幕源我想能否加入弹幕源切换功能，因为在kazumi中貌似弹幕源被确定后就无法改变，就只有弹幕开关这一个功能了，我有一个不小心选错就没办法改回来了。如果弹幕源切换功能能在精确到具体集数那就更好了，这也能变相解决上面的问题。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
我需要考虑一下怎么实现这个功能。

**Comment by Predidit** [comment]
1.2.7 版本添加了弹幕手动切换功能
