### ISSUE TITLE
Windows版中观看时换集没有反应，退出当前番剧重新进入后换集才生效。

### ISSUE THREAD

**Issue by kingzhang999** [Predidit/Kazumi#124]
### 在使用的时候发生了什么 Bug ？

![屏幕截图 2024-08-12 140238](https://github.com/user-attachments/assets/6d3af8cc-13a7-4f41-b1d6-d3a2bd1e30e8)
如上图。当前正在播放第二集。我点击了第一集，一直在加载，没有任何反应，一直在播放第二集。退出当前番剧重进后才播放第一集。

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

Windows 11

### 日志信息

```shell
无日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
转圈说明刮削器已经启动。当获取到视频资源后才会黑屏加载新的视频资源。

看上去这是一个网络问题，你到视频源的网络质量似乎不稳定，换一个视频源应该就好了。

**Comment by kingzhang999** [comment]
使用AGE观看时会这样。刚试了其他的源已经没有这个问题了。
