### ISSUE TITLE
安卓某些地方小横条不适配

### ISSUE THREAD

**Issue by huanglinfeng18** [Predidit/Kazumi#125]
### issue 内容

安卓某些地方小横条不适配
好难受

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
哪个地方没适配

**Comment by huanglinfeng18** [comment]
> 地方适配

![Screenshot_20240812-220026](https://github.com/user-attachments/assets/a15cc3dd-0122-4034-92e6-a599fdfffac8)
在选集页面
系统是PixelOS安卓14

**Comment by huanglinfeng18** [comment]
![CRnall_20240816_164952850](https://github.com/user-attachments/assets/8b023170-3c64-4994-918e-5a82a44c055b)
这个是不是我的问题，我是个小白，不太会搞这种
如果是我的问题我会想办法解决

**Comment by Predidit** [comment]
缺依赖，按照上面的提示安装依赖就可以了。

这种和当前 issue 不相关的问题尽量单开 issue，不然邮件多的时候我不一定能注意到。

**Comment by Predidit** [comment]
小白条已经在 1.2.9 版本修复
