### ISSUE TITLE
[Bug]: 播放器进度条无法回退

### ISSUE THREAD

**Issue by Skzynic** [Predidit/Kazumi#127]
### 在使用的时候发生了什么 Bug ？

进度条向左拉视频进度不会倒退，使用girigirilove源

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

win11 23H2

### （选填）一些与 Bug 相关的硬件信息。

4060 laptop

### 日志信息

```shell
**2024-08-13 14:57:49.281645** 
 解析推荐列表错误 type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这一般和网络问题相关，我无法复现。

**Comment by Predidit** [comment]
我好像意识到问题可能出在哪啊，我现在还没测试，但是这个问题会在连续回退时触发吗。

**Comment by chenbihao** [comment]
> 我好像意识到问题可能出在哪啊，我现在还没测试，但是这个问题会在连续回退时触发吗。

我也遇到偶发的进度条失灵的情况，较难复现

**Comment by Skzynic** [comment]
> 我好像意识到问题可能出在哪啊，我现在还没测试，但是这个问题会在连续回退时触发吗。

似乎是这样，我也不一定会遇到这个问题

**Comment by SCP-XC** [comment]
> 我好像意识到问题可能出在哪啊，我现在还没测试，但是这个问题会在连续回退时触发吗。
当番剧没有自动搜索到弹幕源时，再通过手动搜索确定弹幕源后，键盘将无法控制进度条（稳定触发），鼠标则没有问题，可以滚轮控制音量和拖动控制进度条，这是我遇到的问题。

**Comment by Predidit** [comment]
> > 我好像意识到问题可能出在哪啊，我现在还没测试，但是这个问题会在连续回退时触发吗。
> 
> 当番剧没有自动搜索到弹幕源时，再通过手动搜索确定弹幕源后，键盘将无法控制进度条（稳定触发），鼠标则没有问题，可以滚轮控制音量和拖动控制进度条，这是我遇到的问题。

我复现了这个问题，这是一个焦点问题，和其他人讨论的进度条失效问题应该无关，不过我应该可以修复这个问题。
