### ISSUE TITLE
想要问一问弹幕源选择功能具体是怎么用的？

### ISSUE THREAD

**Issue by kingzhang999** [Predidit/Kazumi#132]
### issue 内容

有一些剧没有弹幕，说是可以手动添加弹幕源。想要问一下这个功能具体是怎么用的？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
没有这个功能啊。

不过弹幕匹配失败时，点击弹幕切换开关，会弹出对话框，可以用其他关键词检索弹幕。

**Comment by kingzhang999** [comment]
知道了，谢谢
