### ISSUE TITLE
非常遗憾，能不能将我们移出默认规则

### ISSUE THREAD

**Issue by girigirilove2022** [Predidit/Kazumi#139]
### issue 内容

由于我们番剧资源是储存在云服务器中，这边带来的流量消耗实在太大了，带宽费用增加过，高达到了10天1万rmb的程度，麻烦您将我们移出默认规则，拜托了。我们只是为爱发电的小团体，资金并不充裕，非常抱歉。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by girigirilove2022** [comment]
id为 girigiri爱动漫网 感激不尽

**Comment by Predidit** [comment]
非常抱歉给你们带来的不便，我会在明天发布新的版本。

**Comment by girigirilove2022** [comment]
❤️

**Comment by Predidit** [comment]
1.2.7 版本已经发布

爱站已经不再是默认规则，考虑到使用者对版本更新并不积极，流量可能需要一段时间才会下降。
