### ISSUE TITLE
能出个linux版的嘛

### ISSUE THREAD

**Issue by JanSky520** [Predidit/Kazumi#14]
电脑用的是arch，作者考虑下适配嘛😍😍

**Comment by Predidit** [comment]
flutter 作为跨平台开发套件，对各个平台的适配程度是不同的。

Linux 的图形界面相对来说用户较少，在 flutter 世界，Linux是货真价实的二等公民，缺少一些重要的特性和功能。

本项目需要一些在 Linux 上还未支持的特性，也就是 flutter/flutter#41724 和 flutter/flutter#41726

在这两个特性被实现前，linux版本是无法推出的。

**Comment by Predidit** [comment]
由于 flutter 短期内没有在 linux 在推进相关进度的迹象，这些内容甚至没有出现在他们的路线图中。

所以我们不再等待 flutter 的官方支持。我编写了一个插件实现 linux 上缺失的部分特性。

目前进度见 #15 ，目前看上去它运行良好。不过 Linux 桌面的碎片化程度比较高，我不确定它的适用性。

你可以测试一下 #15 中的实验性构建并给出反馈吗。

**Comment by Predidit** [comment]
包含 Linux 支持的 1.2.4 版本已经发布。
