### ISSUE TITLE
有无可能添加apple tv版本

### ISSUE THREAD

**Issue by cchenhen** [Predidit/Kazumi#140]
### issue 内容

有无可能添加apple tv版本，大部分看视频时间在家里电视上，希望可以出apple tv版本

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
没有。

tvOS 不是 flutter 的目标平台。添加 tvOS 支持需要修改 flutter 引擎。
