### ISSUE TITLE
搜索结果换页有办法实现吗？

### ISSUE THREAD

**Issue by zedtresh** [Predidit/Kazumi#141]
### issue 内容

首先感谢大佬为程序作出的努力，下面是我目前遇到的一个问题：
在部分网站里，搜索结果可能不止一页，但在kazumi里只会显示第一页的内容，可以通过修改规则获取下一页的搜索结果吗？如果不能，大佬后续可以考虑一下加入相关功能吗？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
目前不支持通过修改规则获取下一页结果。

这个功能没有计划。
