### ISSUE TITLE
无法搜索到剑来

### ISSUE THREAD

**Issue by jayavira** [Predidit/Kazumi#144]
### issue 内容

希望搜索功能做好一点，有些动画无法搜到

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
搜索功能依赖 Bangumi 开放 API

我们并不能对当然番剧列表进行变更

**Comment by jayavira** [comment]
> 搜索功能依赖 Bangumi 开放 API
> 
> 我们不能对当然番剧列表进行变更

ok，那么有没有办法看到剑来呢？
