### ISSUE TITLE
动画与手势识别问题

### ISSUE THREAD

**Issue by acaciachan** [Predidit/Kazumi#148]
### issue 内容

仅测试最新版Android客户端，时间表界面左右滑动的时候，动画结束的太慢，会非常缓慢的停下；但是此过程中存在第二个问题，就是动画未结束之前无法上下滑动，上下滑动会被强行解释为左右滑动(上下滑动不可能绝对竖直，会把其中作用滑动的左右方向的微小分量认为是左右滑动)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这是 flutter 原生控件的问题，我无法解决。
