### ISSUE TITLE
[改進]關於提供給Windows的Release

### ISSUE THREAD

**Issue by ElliotCHEN37** [Predidit/Kazumi#149]
### issue 内容

能否為Windows提供Installer？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
我并没有为 标准 msix 安装包签名所需要的证书，安装这种安装包需要使用者导入我的自签证书。

如果使用非 msi/msix 格式的 installer，就要忍受不优雅的安装过程和丑陋的安装界面。

**Comment by ElliotCHEN37** [comment]
> 我并没有为 标准 msix 安装包签名所需要的证书，安装这种安装包需要使用者导入我的自签证书。
> 
> 如果使用非 msi/msix 格式的 installer，就要忍受不优雅的安装过程和丑陋的安装界面。

哈哈哈哈哈，好吧。謝謝你的回覆
