### ISSUE TITLE
[Bug]: 发现无法连接服务器

### ISSUE THREAD

**Issue by wangzhongtian1224** [Predidit/Kazumi#150]
### 在使用的时候发生了什么 Bug ？

其实在几个版本之前就有这个bug了，不知道是怎么触发的，每次一点开番剧就会先显示局域网异常，然后点入动漫里就会出现代码错误。之前能正常播放的动漫虽然不能搜索后播放，但是可以通过历史纪录这个选项进入观看
![网络异常](https://github.com/user-attachments/assets/1fce6874-0164-427a-81e1-6596378cb386)
![问题2](https://github.com/user-attachments/assets/2741eee2-3230-4412-967b-82473b2fa9e3)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

机械革命翼龙15pro Windows 11 23H2

### 日志信息

```shell
**2024-08-02 16:06:12.719984** 
 RangeError (index): Invalid value: Valid value range is empty: 0 
 null**2024-08-02 16:06:15.641586** 
 RangeError (index): Invalid value: Valid value range is empty: 0 
 null**2024-08-02 16:06:17.257392** 
 RangeError (index): Invalid value: Valid value range is empty: 0 
 null**2024-08-02 16:06:23.240307** 
 RangeError (index): Invalid value: Valid value range is empty: 0 
 null**2024-08-02 16:06:24.156129** 
 RangeError (index): Invalid value: Valid value range is empty: 0 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
尝试添加其他规则。

某些视频源封禁了本程序的UA，我会在下个版本解决。

**Comment by Ssvn7n** [comment]
我发现有这个问题，具体不太一样，通过重置代理解决了
