### ISSUE TITLE
[問題]有關於軟體的協議部分

### ISSUE THREAD

**Issue by ElliotCHEN37** [Predidit/Kazumi#151]
### issue 内容

根據GitHub儲存庫，該軟體採用GPL 3.0協議。

該協議為自由協議，因此商用是允許的（該軟體成為了自由軟體，在遵守GPL 3.0協議的情況下，商用，修改，分發等都是允許的）。但是Readme以及首次啟動的免責聲明提到若為付費獲取應當索取賠償，禁止商用，以此獲利。而協議中提到「When we speak of free software, we are referring to freedom, not price.」自由軟體主要是自由而非價格。「To protect your rights, we need to prevent others from denying you these rights or asking you to surrender the rights.  Therefore, you have certain responsibilities if you distribute copies of the software, or if you modify it: responsibilities to respect the freedom of others. For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received.  You must make sure that they, too, receive or can get the source code.  And you must show them these terms so they know their rights.」此段更直接表明不論商用或者免費都擁有與開發者相同的權利。於第4條（Conveying Verbatim Copies）也講到「 You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.」第10條也有提到「You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License.  For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License, and you may not initiate litigation (including a cross-claim or counterclaim in a lawsuit) alleging that any patent claim is infringed by making, using, selling, offering for sale, or importing the Program or any portion of it.」

簡單來講就是GPL 3.0協議允許任何重新分發，商用等的權利（前提是他們有遵守GPL 3.0協議）
雖然在GPL 3.0中，附加條款是允許的，但是限制重新分發，商用等的權利是不允許的。
我不太確定我的理解是否有誤，我也沒有深入研究過GPL 3.0（本人通常採用MIT協議，簡單易懂呵呵）。也不確定當附加協議與GPL 3.0協議衝突時是以附加協議為准還是衝突的附加協議視為無效。

更簡潔的話：
你用GPL 3.0協議（自由軟體協議）授權=被授權軟體（Kazumi）為自由軟體，自由軟體強調自由，因此不限制商用或以此獲利（前提是遵守GPL 3.0協議）但是你的Readme以及免責聲明都明顯違反了GPL 3.0協議及其宗旨。

我只是單純好奇，完全沒有想要商用的想法

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by ElliotCHEN37** [comment]
防止有人沒看到，再說一遍，免得惹麻煩：
我只是單純好奇而已，沒有任何想要以此獲利的打算

**Comment by Predidit** [comment]
添加了禁止商用条款的 GPLv3 许可是有效的，但是视为一种自定义开源许可，或是一种混合许可。
