### ISSUE TITLE
[改進] 搜索所使用之語言

### ISSUE THREAD

**Issue by ElliotCHEN37** [Predidit/Kazumi#154]
### issue 内容

由於當前搜索功能使用簡中，而有些網站僅提供繁中，這可能會導致無法搜索（待考證，有可能是我在自己寫規則的時候有問題，但目前覺得可能是因為搜索功能使用簡中）

希望能夠與[#153](https://github.com/Predidit/Kazumi/issues/153)一起使用

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
检索依赖 bangumi 开放API

它们的 API 支持繁体中文检索，但是某些繁体中文的译名可能检索不出来。

我们并不能改变 bangumi API 的行为。
