### ISSUE TITLE
[Bug] 啟用深色模式後tray icon的context menu為白色

### ISSUE THREAD

**Issue by ElliotCHEN37** [Predidit/Kazumi#157]
### 在使用的时候发生了什么 Bug ？

啟用深色模式後tray icon的context menu為白色

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

這個程錯應該與操作系統無關，個人認為可能是由於所使用的GUI套件所導致的問題
Windows 11 23H2 22631.4037

### 日志信息

```shell
這個程錯應該與操作系統無關，個人認為可能是由於所使用的GUI套件所導致的問題。所以日誌也沒有錯誤
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
我确认了这个问题，会尝试修复。

**Comment by Predidit** [comment]
最近几天我回到了这个问题上，但是似乎没有合适的解决方法。

现在的托盘菜单功能基于老的 win32 API。理论上来说，如果我们迁移到新的 windows App SDK。我们就可以自动获得现代的托盘菜单，就像微软的其他自带应用那样。

当我在这方面做了一些工作后，情况开始变的有些复杂，新的 windows sdk 并没有更新的关于托盘菜单的调用。实际上，那些自带应用的漂亮的托盘菜单是 winUI 组件库的一部分，和 winUI 是完全耦合的。

也就是说，我们唯一获取这些空间的方式是引入 winUI 组件库，这非常重。并且会导致后续开发无法在 flutter 指南所要求的标准环境中进行，我们需要额外安装 xaml/winUI 相关开发环境，这会导致标准的 github actions CI/CD 无法兼容 kazumi。我们还需要额外构建自己的 flutter CI/CD runtime

总之为了解决托盘菜单样式的问题，而导致那么多麻烦是完全不合算的，我决定关闭这一问题。
