### ISSUE TITLE
Windows端无法访问规则仓库

### ISSUE THREAD

**Issue by 2291457574** [Predidit/Kazumi#16]
Windows端无法访问规则仓库，无论是否开启镜像和梯子都不行；另外主页面能正常加载但是启动时会弹网络异常，求解决方法。
![image](https://github.com/Predidit/Kazumi/assets/64952686/c2781480-81a9-4024-8b60-22563a6c7d38)
![image](https://github.com/Predidit/Kazumi/assets/64952686/b1115005-2509-45b5-986b-30c3aed79947)

**Comment by Predidit** [comment]
开关镜像后需要重启程序才能生效。

规则仓库只会在程序开启时从 github 同步一次，以尽可能较少镜像的负担。如果开了梯子，也要重启程序才能看到作用。

**Comment by 2291457574** [comment]
事实上， 我已经反复重启程序、开关镜像以及梯子试了许多次，但是总是无法访问规则仓库，首页也会弹连接失败或者网络异常，但是Android端没有问题。如果没办法的话我只能先用Android端看番了。

**Comment by Predidit** [comment]
这是完全没有道理的，可能是您那边android和windows网络状况不同，一个恰当的验证方式是手机开热点给电脑测试。

另外关于梯子，是这样的，梯子一般只会代理浏览器或是其他使用系统代理的应用，不会代理应用程序，要实现代理所有程序的全局代理，需要启用TUN。

**Comment by 2291457574** [comment]
> 这是完全没有道理的，可能是您那边android和windows网络状况不同，一个恰当的验证方式是手机开热点给电脑测试。
> 
> 另外关于梯子，是这样的，梯子一般只会代理浏览器或是其他使用系统代理的应用，不会代理应用程序，要实现代理所有程序的全局代理，需要启用TUN。

好的，我会尝试的，感谢您的回复
