### ISSUE TITLE
启用github镜像后仍无法访问远程仓库，将规则json手动添加到plugin文件夹后规则不生效

### ISSUE THREAD

**Issue by GreenBudsOnPotato** [Predidit/Kazumi#161]
### issue 内容

系统版本：Windows 10 Build 19045.4780
网络环境：实际中国大陆 联通 局域网（VPN所属IP：香港/日本/美国 等）不论是否使用VPN均会出现本issue所述情况
软件版本：1.2.7（实测旧版本同样会出现该问题）
问题描述：打开软件时底部气泡显示“正在使用局域网 网络异常”，但主页番剧资源、图片，番剧内容及视频、弹幕均可正常加载。
进入设置-规则管理后，软件自带的三个规则存在并正常使用，使用“从规则仓库导入”功能时出现错误，显示“无法访问远程仓库 镜像已启用”。尝试手动导入规则至..\Kazumi\data\flutter_assets\assets\plugins目录后，“规则管理”界面仍未正常读取到导入的规则。
问题需求：可能是我网络配置的问题，实测同一网络环境下手机裸连或使用VPN都可以正常使用，还请麻烦帮忙寻找一下解决办法，谢谢。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
github 镜像也部署在中国大陆之外，在中国大陆部署 github 镜像是不被允许的。可能你在的区域对网络有更强的管制，中国大陆的少数地区存在域名白名单，你可能在这样的白名单区域，所以镜像不能生效。

某流行的代理软件在 windows 和 android 上的处理不同，简单说，它在 windows 上无论代理模式如何，一般只代理网页。而在 android 上是真正的全局代理。本程序是一个独立的程序而不是网页，所以在 windows 上的代理不生效。

你访问的目录是预载规则的目录，真正的当前规则目录在 `%AppData%/com.example/kazumi/plugins`

**Comment by Predidit** [comment]
我不知道为什么会这样，可能是全局代理未生效，或是代理IP同时共享的人数过多，导致被github拉黑。

你可以按照我上面给出的目录手动导入。这个目录是一个windows上的保留目录，用来储存应用数据，输入资源管理器就可以打开了。不需要自己编译kazumi。
