### ISSUE TITLE
[Bug]: webdav无法同步

### ISSUE THREAD

**Issue by dix9901** [Predidit/Kazumi#163]
### 在使用的时候发生了什么 Bug ？

因为有公网IP，所以我自己使用了本地设备当作webdav服务器，使用app的同步功能时，点击WEBDAV同步按钮，一直会显示“同步成功，这是一个不存在已有同步文件的webdav”。
而且观看后也无法同步（换设备发现并没有同步过来观看记录），似乎app并没有将本身的历史记录上传到webdav服务器里，我查看挂载的服务器路径，当下文件夹里只有一个tmp文件。

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

华为平板m6，荣耀magic6pro

### 日志信息

```shell
没有提示错误
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
`同步成功，这是一个不存在已有同步文件的webdav` 是正常的提示，表示这是一个新的 webdav 且初始化成功。

kazumi 只会在启动时从 webdav 获取资料，只有在从 视频页面 退出到详情页面时会上传观看进度。这是为了减轻 webdav 负担，很多公共 webdav 服务的 rate limit 非常低。
