### ISSUE TITLE
Windows下的编译环境咨询

### ISSUE THREAD

**Issue by YamakiYume** [Predidit/Kazumi#164]
### issue 内容

我想咨询一下本项目Cmake的环境设置。
我曾遇到过此问题
>CMake Error at flutter/generated_plugins.cmake:24 (add_subdirectory): add_subdirectory given source
>"flutter/ephemeral/.plugin_symlinks/window_manager/windows" which is not anexisting directory.

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
kazumi 的编译没有什么特别的要求。

kazumi 使用的部分库需要从 sourceforge 或是 maven repository 获取依赖，这些资源在大陆的访问质量一样有问题。

所以如果在中国大陆的话，只为 flutter 设置镜像的话大概率是编译不通过的，有条件的话尝试使用全局代理。

**Comment by YamakiYume** [comment]
好的，我尝试一下。谢谢。

**Comment by YamakiYume** [comment]
我想再问一下，您的Windows程序也是用flutter编写的吗？

**Comment by Predidit** [comment]
这个工程的构建依赖 flutter 套件，具体步骤参考 flutter 构建指南。

项目目录里 windows 文件夹下的 visual studio 工程是 flutter 工具链自动生成的，这一工程无法独立使用 Visual Studio 构建。

**Comment by YamakiYume** [comment]
好的，我明白了。谢谢。
