### ISSUE TITLE
[Feature] 手动上传下载 WebDav 同步功能

### ISSUE THREAD

**Issue by Immortal-Sty** [Predidit/Kazumi#166]
### issue 内容

第一次打开 WebDav 功能会自动下载同步，然后失败，且不会立刻上传配置。

我同时在电脑和手机上安装了软件，并在电脑端配置好了收藏夹和同步。到手机上搞好同步后，想直接把收藏夹同步过来，但失败了，上云端才发现电脑端还没同步。

现在只能把电脑端挂后台，每过一会儿就试试同步了没，太麻烦了。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
现在同步的时机是，在从视频播放页面回退到详情页面时会上传历史记录，启动 app 时会下载历史记录，这似乎频率太低了，且由于代码中的问题，有时同步不会生效。

同步相关的补丁已经提交到仓库，修复了有时同步不生效的问题，并新增在程序切换到后台时上传历史记录，切换到前台时下载历史记录的同步时机。

这些补丁会包含在下个版本中。

**Comment by Immortal-Sty** [comment]
不好意思，没有表述清楚。我其实是想问，能否加入手动上传下载功能（挠头）。

同步的机制，我刚在其他 issue 里面看到。然后发现好像不支持同步收藏。

或许可以用 Json 来存储收藏，并在每一项中加上编辑时间，更新时按编辑时间来决定操作。你看这样行不？

**Comment by Predidit** [comment]
1.2.8 已经发布

**Comment by Immortal-Sty** [comment]
大佬神速！
