### ISSUE TITLE
非常抱歉再次打扰到您 开发者们

### ISSUE THREAD

**Issue by girigirilove2022** [Predidit/Kazumi#168]
### issue 内容

我们发现在规则仓库中依然有我们站点，上次也说过为爱发电的网站经费实在不充裕，我们不反对非盈利用途的使用我们网站的资源，用户个人如果自己配置来使用也没关系，但是基于公开的规则仓库传播性和带来的流量消耗太过大，能否将我们的配置从规则仓库删除呢

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
非常抱歉又给你们添了麻烦，但我还是想做一下说明。

流量不只来自我们，以爱站相关关键词在github上按照github检索指南进行代码层面的检索。我们可以发现几乎所有类似项目都收录了爱站，包括人气超高的 easybangumi 项目。

我们接受移除示例规则的请求，但是对于已经不是示例规则的请求，我们并不会移除，您可以通过一些方法令其失效，在这种情况下，规则会被移除或修改。

大家都在用爱发电，并用自己的时间和劳动让自己的东西变得更好。

**Comment by girigirilove2022** [comment]
好的 感谢配合，其他项目我也会一并联系他们，非常感谢

**Comment by girigirilove2022** [comment]
我们下载并安装了easybangumi，他们并没有提供示例规则和默认规则的选项(贵方主要是公开了我们的规则(有默认规则和规则仓库)，我们反对的也是这个)，我们并不反对个人用户自己使用我们站点的规则（只要不公开和非盈利用途）

**Comment by Predidit** [comment]
所以我上面说了，您按照 github 检索指南在代码层面，而不是一般的项目描述中检索爱站关键词，这样您才能发现一些事情。

easybangumi 并不是您说的那样，您可以发现他们的唯一拓展其实是他们组织下面的 community extension 那个库，您大可以安看看里面是什么。

**Comment by Predidit** [comment]
那是唯一的官方收录扩展，里面包含六个站点，作为使用者可以开发自己的扩展。

**Comment by Predidit** [comment]
上面关于爱站的资源被不同项目使用是属实的。

**Comment by girigirilove2022** [comment]
好的 非常感谢

**Comment by girigirilove2022** [comment]
我会挨个联系他们
