### ISSUE TITLE
安卓11无法播放视频，求助大佬解决bug

### ISSUE THREAD

**Issue by MisakaNo23300** [Predidit/Kazumi#17]
如题，每一个规则网站源都是这样。
但很奇怪的是有声音，没画面

提示：Callback received:The number of video tags is0Callback received:The number of iframe tags is0If there is audio but no video, please report it to the
rule developer.

手机型号：vivo Y31s
系统：安卓11
系统包PD2068B_A_1.25.16

![Screenshot_20240629_234131](https://github.com/Predidit/Kazumi/assets/89892822/649d22c3-909d-4466-9054-0edd4b0f6f03)
![Screenshot_20240630_000743](https://github.com/Predidit/Kazumi/assets/89892822/189827c9-b639-4919-8f64-75a141683f0e)

**Comment by Predidit** [comment]
播放设置，关掉硬件解码试试。

**Comment by MisakaNo23300** [comment]
> 播放设置，关掉硬件解码试试。

试过了诶，还是不行

**Comment by Predidit** [comment]
您的界面实质上是日志，而不是报错，您等待约10秒后，界面会显示超时吗。

此外webview规则而非native规则可用吗。

**Comment by MisakaNo23300** [comment]
今天又可以看了，好神奇啊，可能是播放源的问题
