### ISSUE TITLE
没有了

### ISSUE THREAD

**Issue by H5555555** [Predidit/Kazumi#170]
### issue 内容

sex anime（H），can not find，(ಥ_ಥ)呜呜呜～，please，important

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这不是 kazumi 可以解决的问题。

Kazumi 的检索功能来自 Bangumi 开放API, 他们的 API 在上次更新后不再返回 R18 条目。

**Comment by Predidit** [comment]
以前也只是能检索到条目，但是没有视频源。
