### ISSUE TITLE
[Bug]: 出现在时间表，但却无法检索？

### ISSUE THREAD

**Issue by jm3720343** [Predidit/Kazumi#171]
### 在使用的时候发生了什么 Bug ？

如题
![Screenshot_20240824_232559](https://github.com/user-attachments/assets/d62ca05a-feed-4259-bb96-5b593939c387)
![Screenshot_20240824_232543](https://github.com/user-attachments/assets/ef5bfba3-a75f-47d4-be9d-31c43e8c3d2a)

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

努比亚Z40spro Android14

### 日志信息

```shell
**2024-08-20 02:35:55.330045** 
 RangeError (length): Invalid value: Valid value range is empty: 0 
 null**2024-08-20 02:35:58.037449** 
 RangeError (length): Invalid value: Valid value range is empty: 0 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
番剧检索和时间表都来自 bangumi 开放 API 我们并不能影响 bangumi API 的行为。

我会保持这个 Issue 为开启状态，因为我在测试时发现了另一个需要跟踪的问题。当搜索无结果时，某些情况下会一直显示加载动画。
