### ISSUE TITLE
无法webdav同步

### ISSUE THREAD

**Issue by OneRing-R** [Predidit/Kazumi#172]
### issue 内容

在Windows server 2022上用alist v3.36.0挂载本地存储，在kazumi配置好后打开webdav开关时报错“同步失败 HiveError:Wrong checksum in bytes. Box may be corrupted.”

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
看上去备份文件被损坏了，我不知道为什么会这样，尝试清空备份文件夹。

在线 webdav 服务有这个问题吗。

**Comment by OneRing-R** [comment]
更换设备依然报错，不过更换为坚果云的webdav到是可以正常使用

**Comment by OneRing-R** [comment]
应该是我alist配置错了
