### ISSUE TITLE
刮削不到的番剧如何收藏

### ISSUE THREAD

**Issue by xuze1993** [Predidit/Kazumi#173]
### issue 内容

一些国漫刮削不到，搜索时页面只显示其他结果。随便点一个结果进去搜索的番剧名是对的，可以进网站观看，但是似乎不能收藏追番

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
暂时没有办法。

我们没有办法控制 Bangumi API 的行为。
