### ISSUE TITLE
macOS/iOS 外部播放器支持

### ISSUE THREAD

**Issue by Predidit** [Predidit/Kazumi#176]
Edit at 2024/10/22

基本外部播放器支持已经由 @ErBWs 完成 (#315) (#335)

预期会包含在 1.4.0 版本中

**Comment by ErBWs** [comment]
macOS可以选择应用，但原理是用命令行打开链接，所以众多软件基本不是没法解码链接就是不支持命令行唤起，所以能支持的可能只有mpv本体和基于mpv编写的IINA
<img width="429" alt="image" src="https://github.com/user-attachments/assets/f3f8fb4c-1f89-4736-babf-1e52ea51adc3">

**Comment by Predidit** [comment]
macOS 外部播放器支持最终在 1.4.0 完成
