### ISSUE TITLE
通过搜索栏查找番剧可以解析出视频但收藏里解析不出视频

### ISSUE THREAD

**Issue by maobuchiyu** [Predidit/Kazumi#178]
### issue 内容

![QQ20240827-140124](https://github.com/user-attachments/assets/e7c27bcb-7171-4636-b56a-ab5f2cf64ba1)
![QQ20240827-140144](https://github.com/user-attachments/assets/40664b25-977c-48a5-8af8-80b25b0025db)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
和 #53 重复
