### ISSUE TITLE
看任何片都会显示：服务器异常，请稍后重试！

### ISSUE THREAD

**Issue by idmixx** [Predidit/Kazumi#179]
### issue 内容

![Screenshot_2024-08-27-19-00-09-850_com predidit kazumi](https://github.com/user-attachments/assets/ee6377e4-62f8-4f32-bcab-b94dc41c844f)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by idmixx** [comment]
这个问题如何解决？谢谢开发者解惑答疑！

**Comment by Predidit** [comment]
左右滑动能换到其他源的

不要装那么多源，选几个好用的就行了，任一源出错都会有错误提示的

**Comment by idmixx** [comment]
好的谢谢，解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月27日(周二) 晚上7:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Predidit/Kazumi] 看任何片都会显示：服务器异常，请稍后重试！ (Issue #179)




 
左右滑动能换到其他源的
 
不要装那么多源，选几个好用的就行了，任一源出错都会有错误提示的

**Comment by Arichlife** [comment]
为什么ios自签完打开无法使用 多人都有这个问题 请问开发者怎样解决该问题
![IMG_4383](https://github.com/user-attachments/assets/7234c6b6-c691-4200-b84b-b0285319fa24)

**Comment by Predidit** [comment]
@Arichlife 

不行就换一个视频源试试，这些视频网站基本都在用一些奇怪的手段白嫖带宽和储存空间，避免自己托管视频资源的带宽开销。

这些手段有时会导致 SSL 错误，在其他平台上这种错误会被忽略，但是 iOS 不允许我们忽略这种错误。

**Comment by Arichlife** [comment]
开发者您好！
感谢您在百忙中回复了我
在我刚刚想继续反馈的时候又返回了app试了一下 又突然能用了！我非常惊讶也很欣喜 感谢您开发了这款app 您的oneanime我和朋友们也经常使用
我们十分喜爱您的kazumi和oneanime 这两款app
请问这是app开发者您的邮箱吗 如果以后app有些许问题我是否可以借助邮箱询问您呢&nbsp;

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Predidit ***@***.***&gt;
发送时间: 2024年8月28日 18:11
收件人: Predidit/Kazumi ***@***.***&gt;
抄送: Arichlife ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Predidit/Kazumi] 看任何片都会显示：服务器异常，请稍后重试！ (Issue #179)





 
@Arichlife
 
不行就换一个视频源试试，这些视频网站基本都在用一些奇怪的手段白嫖带宽和储存空间，避免自己托管视频资源的带宽开销。
 
这些手段有时会导致 SSL 错误，在其他平台上这种错误会被忽略，但是 iOS 不允许我们忽略这种错误。

**Comment by Predidit** [comment]
> 开发者您好！ 感谢您在百忙中回复了我 在我刚刚想继续反馈的时候又返回了app试了一下 又突然能用了！我非常惊讶也很欣喜 感谢您开发了这款app 您的oneanime我和朋友们也经常使用 我们十分喜爱您的kazumi和oneanime 这两款app 请问这是app开发者您的邮箱吗 如果以后app有些许问题我是否可以借助邮箱询问您呢&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Predidit ***@***.***&gt; 发送时间: 2024年8月28日 18:11 收件人: Predidit/Kazumi ***@***.***&gt; 抄送: Arichlife ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [Predidit/Kazumi] 看任何片都会显示：服务器异常，请稍后重试！ (Issue #179) @Arichlife 不行就换一个视频源试试，这些视频网站基本都在用一些奇怪的手段白嫖带宽和储存空间，避免自己托管视频资源的带宽开销。 这些手段有时会导致 SSL 错误，在其他平台上这种错误会被忽略，但是 iOS 不允许我们忽略这种错误。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

这是Github动态生成的邮箱，不是我的邮箱，发送到这个邮箱的回复会被同步到 Github 的相关 Issue 页面。

有相关问题可以在对应仓库打开新的 Issue , 让我们一起让这个项目变得更好。
