### ISSUE TITLE
[enhancement] Windows 端添加最小化和全屏按钮

### ISSUE THREAD

**Issue by xsfx0313** [Predidit/Kazumi#18]
功能请求如题  
现在在Windows端没有全屏和最小化按钮在右上角，使用不便， 希望能添加保障正常使用体验。  谢谢！
感谢开发者! ^_^

**Comment by Predidit** [comment]
全屏按钮不应该被使用，那样会导致布局错乱。

最小化按钮可以有，但那样会占用更多的右上角空间。
