### ISSUE TITLE
webdav手动下载

### ISSUE THREAD

**Issue by luckyjion** [Predidit/Kazumi#181]
### issue 内容

手动上传后再手动下载提示同步失败dioexception [bad response]:null Error:not found

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
等待出现上传成功的提示后再下载

**Comment by luckyjion** [comment]
![同步成功](https://github.com/user-attachments/assets/eea088ec-59df-47ee-8911-ca664e2607f7)

还是不行它总是会提示同步失败没有找到资源

**Comment by yushengblog** [comment]
<img width="1101" height="296" alt="Image" src="https://github.com/user-attachments/assets/566a2a56-b1e3-470b-8b63-ffc2d50c66bd" />

<img width="1006" height="235" alt="Image" src="https://github.com/user-attachments/assets/5b69719c-d296-4502-98b2-722d086be071" />

<img width="1134" height="359" alt="Image" src="https://github.com/user-attachments/assets/d78a3878-03ff-4431-949d-f727883313e2" />

用的IIS配置的WebDAV对吧，IIS 默认不会为未知扩展名的文件提供服务
（我也是翻了半天的Issues，发现了和我有同样的问题，但没找到解决办法，好在找到原因了）
按照如图所示，添加一下MIME 类型：

- 文件扩展名：.tmp

- MIME 类型：application/octet-stream
