### ISSUE TITLE
视频无法倍速播放

### ISSUE THREAD

**Issue by FateNineMeow** [Predidit/Kazumi#182]
### issue 内容

倍速播放pls

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
现有的倍速播放功能出了什么问题吗

**Comment by FateNineMeow** [comment]
![image](https://github.com/user-attachments/assets/5c1607d8-09ad-44e7-a810-cc2b06889e8b)
![image](https://github.com/user-attachments/assets/88b1f2dc-43d9-4f9b-aace-57f87af667e6)

![image](https://github.com/user-attachments/assets/ba0be272-abf9-40f8-b067-c17693556978)
Windows端  版本1.2.9


倍速播放功能 刚刚截图补充的时候看到了，抱歉之前眼瞎，问题提错了，【磕一个
另外提两个功能增强：
1、播放无音量调节
2、不支持快捷键操作

**Comment by Predidit** [comment]
1. 音量调节绑定在了鼠标滚轮上，在移动设备上是屏幕右侧上滑与下滑

2. 快捷键方案类似B站网页端快捷键

**Comment by FateNineMeow** [comment]
好的，谢谢解答
