### ISSUE TITLE
iOS播放没有声音

### ISSUE THREAD

**Issue by LigayaLyphme** [Predidit/Kazumi#183]
### issue 内容

用的是最新版，音量也可以调节，但无论如何就是有画面无声音。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
检查是否打开系统的静音

**Comment by LigayaLyphme** [comment]
> 检查是否打开系统的静音

并没有打开系统静音，因为最近出现了以下情况：在第一次打开并播放的一段极短呃呃时间内有声音，随后无论播放什么内容都不会再出现声音。

**Comment by Predidit** [comment]
1.3.1 彻底解决了这一问题
