### ISSUE TITLE
[feature]希望增加分发模式或者更新方法

### ISSUE THREAD

**Issue by Eazed-Yu** [Predidit/Kazumi#184]
### issue 内容

开发者您好，以下是我在使用过程中发现的不足之处和我的建议，希望我的建议能起到积极的作用。
不足：目前window平台每次更新都需要重新下载压缩包，每次我都需要重新删除旧版文件，重新安装新版文件。
建议：希望能支持安装方式，或者支持增量更新。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by WhiteXero** [comment]
附议，确实直接软件内更新会比较好

不过对于更新这一块，考虑到 github 的国内访问问题，也许不能直接从 github 下载更新内容
我的想法是在 gitee 等国内易于访问的平台同步这个仓库，然后进行下载

对于 Linux，建议直接创建 actions 自动上传 AUR，这应该更有效

macos 和 ios 就只能先搁置了

**Comment by Predidit** [comment]
Linux 现在已经上架到 flathub

F-Droid 的上架流程看上去比较复杂，@WhiteXero 有兴趣进行 F-Droid 的上架工作吗。

其他平台暂时还没想到合适的方案

**Comment by WhiteXero** [comment]
当然，f-droid我可以研究一下

**Comment by Predidit** [comment]
F-Droid 需要从源代码开始编译，由于 kazumi 并不是标准 android 应用，而是 flutter 应用，看上去我们要编写一个非标准的构建脚本。

**Comment by WhiteXero** [comment]
是，而且还需要搞可重复

有点难度

考虑直接应用内更新吗？

**Comment by Predidit** [comment]
应用内更新需要考虑托管位置，而且相较于现在的模式似乎并没有特别明显的优势

**Comment by Predidit** [comment]
也许我们可以参考 F-Droid 上已有的 flutter 应用的例子，以及不进行可重复

**Comment by Predidit** [comment]
@Eazed-Yu 

1.4.6 版本开始提供带有可信签名的 MSIX 安装包
