### ISSUE TITLE
不显示番剧

### ISSUE THREAD

**Issue by Fo1ever** [Predidit/Kazumi#186]
### issue 内容

![Screenshot_2024-08-31-01-52-50-635_com predidit kazumi](https://github.com/user-attachments/assets/1519cc98-2996-437c-8fda-dd642cfa8847)
点进去后下面不显示是为什么，之前有显示

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
和 #53 重复
