### ISSUE TITLE
[Bug]: 全屏播放两侧是白色的

### ISSUE THREAD

**Issue by XiaoWei54** [Predidit/Kazumi#187]
### 在使用的时候发生了什么 Bug ？

当全屏播放视频时，屏幕两侧都是白色的。
![A3C9EA52-665F-4467-BC3C-32F6129A0377](https://github.com/user-attachments/assets/b5c3b25e-e28f-487d-bb45-f9c95669dad2)

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

iPhone 12 iOS 15.4.1

### 日志信息

```shell
无
```

### 提交前确认

- [ ] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是一个回归，看上去是修复 #125 的补丁导致的。

这个现象似乎和iOS版本相关，今天太晚了，明天我会构建一个测试版本，麻烦到时测试一下有没有问题。

**Comment by Predidit** [comment]
https://github.com/Predidit/Kazumi/actions/runs/10650122601/artifacts/1878623148

检查这个构建有无问题

**Comment by XiaoWei54** [comment]
问题仍然存在，但我尝试使用1.2.8版本后没有遇到这个问题。

**Comment by Predidit** [comment]
1.3.0 版本已经发布，问题应得到解决
