### ISSUE TITLE
🐛[bug?/question] Windows 端卡顿，显卡高占用

### ISSUE THREAD

**Issue by xsfx0313** [Predidit/Kazumi#19]
## 环境以及信息
|项目|信息|
|----|----| 
|Kazumi 版本|1.15|
|windows 版本|windows11-23H2-22631.6372|
|CPU|i5-10210U|
|GPU|核显|

## 问题描述
1. 在刚打开软件时 GPU 占用在5-20%
2. 随便点开一个番剧，找一个 native 源时就开始占用大量GPU，占用约60-80%，直接吃满3D，GPU 整体占用**稳定**100%
3. 在开始播放后出现**大量画面撕裂**以及**卡顿**
4. 在**暂停**播放时，GPU 占用维持不变，**依然**稳定100%
5. 更关键的是，在离开播放界面后(比如进入设置界面)，依然保持了极高 GPU 占用，没有降低(50%以上)

## 一些其他描述以及想法
1. 无论是硬解还是软解，都一样
2. webview 好一些，没有画面撕裂，不过占用依然不小
3. 可以非常稳定的发生，绝对不漏

## 一些其他的话
这个 issue 可能无法提供任何建设性作用，也无法定位问题所在，对此我非常抱歉。不过还是希望开发者能继续优化，解决一下性能问题。关于卡也有可能是我笔记本性能太差了吧 (笑)，希望能对低性能设备友好一点。我很喜欢和看好此项目。谢谢啦！:  )

**Comment by Predidit** [comment]
1. 你的笔记本正确安装并更新集成显卡驱动程序了吗，现在的驱动程序版本是多少。

2. 只有当前版本有问题吗，1.1.4是否有问题。

3. 开启与关闭弹幕是否影响卡顿与画面撕裂

**Comment by xsfx0313** [comment]
抱歉，这两天有事
1. 已按照您的建议更新了显卡驱动，但并无改观。版本为：31.0.101.2128 驱动更新日期：2024/5/3
2. 1.14也有问题
3. 与弹幕是否打开无关，事实上，弹幕都极难打开
4. 我又测试了其他几个源，都有问题，webview也一样。  

另：我电脑可以YouTube8k不卡，bilibili 4k不卡

**Comment by Predidit** [comment]
我对这个问题感到非常迷茫，我现在想确定问题来自哪里。

你可以看到我的另一个项目 oneAnime 吗，他的最新版本和1.2.0版本分别测试一下，有类似的情况发生吗。1.2.0版本的视频播放方案和本项目相同， oneAnime 的最新版本视频播放使用了一个闭源方案。

**Comment by Predidit** [comment]
我已经确认这是一个来自 webview_windows 库中的 bug，在调用其 dispose 方法后，webview 并不会停止离屏渲染。

在本程序的用例中，当正确获取视频资源后，隐藏的本应该被释放的 webview 在C++侧仍然进行离屏渲染，并与播放器的渲染画面竞争资源，导致高GPU占用，这在低端图形设备上非常明显。

补丁已经提交到我维护的 webview_windows 分支，这个问题会在下个版本得到修复。

**Comment by Predidit** [comment]
1.2.1 已经发布
