### ISSUE TITLE
bangumi番剧索引登录，部分番剧不登录账号是搜索不到的。

### ISSUE THREAD

**Issue by tiancer** [Predidit/Kazumi#190]
### issue 内容

bangumi番剧索引登录，部分番剧不登录是搜索不到的。
也无法进源搜索。
希望可以登录bangumi或进源搜索，任一即可。
![IMG_20240901_114936](https://github.com/user-attachments/assets/c787af2d-e5c2-486b-8c8c-54b2856f8f95)
![IMG_20240901_115002](https://github.com/user-attachments/assets/ae316e14-6e9c-45db-8838-dab5578ea6ba)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
和 #159 重复
