### ISSUE TITLE
[Bug]: macOS图标过大

### ISSUE THREAD

**Issue by shenfangda520** [Predidit/Kazumi#191]
### 在使用的时候发生了什么 Bug ？

图标太大啊   格格不入

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

对对对

### 日志信息

```shell
mac  图标太大
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
我们需要macOS用户提交并测试恰当的图标

**Comment by CAiNSEMBRACE** [comment]
> 我们需要macOS用户提交并测试恰当的图标
这是适配好的macOS图标, 可以测试一下
[kazumi.icns.zip](https://github.com/user-attachments/files/17227494/kazumi.icns.zip)
<img width="335" alt="image" src="https://github.com/user-attachments/assets/c3129aba-64d6-4c12-aa17-bc55e52b739d">

**Comment by Predidit** [comment]
@CAiNSEMBRACE 

感谢你的帮助

我没有 macOS 设备来进行测试与调整，macOS 图标位于 /macos/Runner/Assets.xcassets/AppIcon.appiconset/

目录下不同尺寸的 .png 适用于不同的场合

这些图标由 flutter_launcher_icons 从原图标文件自动生成，但看上去在 macOS 上工作的不是那么好

项目中需要的是 .png 而不是 .icns 

你能解压 .icns 为不同分辨率的 .png 文件并提交PR来更新它们吗

**Comment by Predidit** [comment]
感谢 @CAiNSEMBRACE 

此问题已在 1.3.5 版本修复
