### ISSUE TITLE
建议Windows增加RTX视频增强功能，或可使用本地播放器播放

### ISSUE THREAD

**Issue by yiangeng** [Predidit/Kazumi#194]
### issue 内容

建议Windows增加RTX视频增强功能，或可使用本地播放器播放

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
英伟达视频超分辨率相关资料与sdk只开放给合作伙伴，我们并不能拿到相关资料。

外部播放器播放的话，可以使用视频右上角的外部播放功能。

**Comment by Predidit** [comment]
我们在 1.5.2 引入了基于 Anime4K 的实时超分辨率

启用相关设置后查看是否有改善
