### ISSUE TITLE
[Bug]: 最后一格规则删除不方便

### ISSUE THREAD

**Issue by Unmannedruins** [Predidit/Kazumi#196]
### 在使用的时候发生了什么 Bug ？

规则删除

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

23h2

### （选填）一些与 Bug 相关的硬件信息。

![image](https://github.com/user-attachments/assets/e6e40e1a-4bc0-4bd5-b7cd-468d7fe20655)

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
和 #128 重复
