### ISSUE TITLE
Windows端调用第三方播放器（比如potplayer，mpv等）进行播放

### ISSUE THREAD

**Issue by Alvin-Blithe** [Predidit/Kazumi#198]
### issue 内容

如题
我查看了 #23，只有部分视频具右上角的远端播放，但是即使有这个按钮的，点外部播放后只是在调用浏览器下载视频，并没有唤起本地播放器。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
如果所有的视频源都能被正确解析，那么就只有native规则，不会有webview规则了。仓库里的webview规则都是无法被解析出资源地址的，所以使用webview播放。

webview的限制相较于浏览器大很多，也不可能会有油猴这样的执行环境，如果能载入油猴的话，kazumi也不用折腾那么多js魔术了。

**Comment by Alvin-Blithe** [comment]
噢噢，我确实不是很了解这个，其实我只是想在看番时候用anime4K的着色器，现在看起来有点难；抱歉，感谢大佬的回复，谢谢！

**Comment by Predidit** [comment]
@Alvin-Blithe 

我想我们现在在这个问题上取得了进展，现在播放器可以调用系统中的 .m3u8 文件默认打开方式而不是浏览器来打开视频流。目前我们没有办法自定义要使用的播放器，切换播放器需要切换系统默认 .m3u8 文件打开方式。

测试下面的构建: 

https://github.com/Predidit/Kazumi/actions/runs/11007423398/artifacts/1969772903

**Comment by Alvin-Blithe** [comment]
> @Alvin-Blithe
> 
> 我想我们现在在这个问题上取得了进展，现在播放器可以调用系统中的 .m3u8 文件默认打开方式而不是浏览器来打开视频流。目前我们没有办法自定义要使用的播放器，切换播放器需要切换系统默认 .m3u8 文件打开方式。
> 
> 测试下面的构建:
> 
> https://github.com/Predidit/Kazumi/actions/runs/11007423398/artifacts/1969772903

无法唤起，报错如下，我已经设置了默认调用m3u8的播放器为mpv
![image](https://github.com/user-attachments/assets/ba50c51d-855d-46d4-b844-2aeec1284363)

**Comment by Predidit** [comment]
看上去是视频地址太长了，也许我可以修复它，你尝试过其他规则吗。比如 AGE

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/7e134d4a-ef72-4502-ac23-9bb1dea670ac)
换了AGE规则后，成功唤起了播放器，但显示黑屏无内容

**Comment by Predidit** [comment]
看上去这是 girigirilove 规则，这个规则调用外部播放器有一个已知问题

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/958c6d0b-d479-4eba-a49b-e95bf6d1171a)
这个是AGE的规则，尝试了好几个动漫，也出现了和上面第一个图一样的报错；少部分能唤起播放器，但也是黑屏

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/643e4a7c-304f-4571-a166-3435c727d8b6)
在更换播放器尝试的过程中，又出现了另外一种报错

**Comment by Predidit** [comment]
我想我知道问题在哪了，稍后我会在这里发送另一个实验性构建

**Comment by Predidit** [comment]
尝试这个实验性构建

https://github.com/Predidit/Kazumi/actions/runs/11015071620/artifacts/1971802644

**Comment by Alvin-Blithe** [comment]
![image](https://github.com/user-attachments/assets/d48bf6a8-a90d-452f-a276-666f43b23153)
成功能够拉起了！但是弹幕没有传输过来，不过已经很好用了，辛苦作者大大了

**Comment by Predidit** [comment]
感谢你的反馈

由于使用了非常规方法来达到目的，我不能保证这一功能的稳定性，我会暂时保持这个 Issue 为开启状态来收集相关反馈。

有什么问题欢迎在这里继续留言。

**Comment by Predidit** [comment]
此功能已在 1.3.4 实现

1.3.4 额外实现了播放器选择对话框
