### ISSUE TITLE
在linux下提示储存初始化错误

### ISSUE THREAD

**Issue by kjrin710** [Predidit/Kazumi#199]
### issue 内容

尊敬的开发者你好，我在linux上运行kazumi的时候遇到了一些问题。

下面我将尝试复现该问题：
在release中下载了Kazumi_linux_1.3.0_amd64.tar.gz。
将Kazumi_linux_1.3.0_amd64.tar.gz解压至我的Desktop文件夹。
发现文件夹中有一个kazumi的可执行文件，执行后新弹出了一个内部错误的窗口。
![2024-09-04-181421_hyprshot](https://github.com/user-attachments/assets/ff74db2f-d62a-4bc8-a7c0-6bf7c448914b)
我确定我没有重复启动该程序，并且查看了kazumi的进程和输出信息，但还是没有找到其他的解决办法，所以在此寻求帮助。
![2024-09-04-181424_hyprshot](https://github.com/user-attachments/assets/441bb3aa-d278-4f60-910e-b7482e11c202)
![2024-09-04-183348_hyprshot](https://github.com/user-attachments/assets/8eead0aa-276c-4719-8b55-923a802200bd)

下面是我机器的运行环境：
OS: Gentoo 2.15 x86_64
Kernel: Linux 6.6.47-gentoo-x86_64
WM: Hyprland (Wayland)

webkit版本:webkit-gtk-4.1
kazumi版本:Kazumi_linux_1.3.0_amd64

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
本地用户数据储存初始化失败，这一般发生在重复运行 kazumi 而产生资源竞争的场合

或者在出现权限问题导致无法访问用户数据目录时，也可能出现这一错误

尝试使用wheel用户组或更高级别的用户操作

**Comment by kjrin710** [comment]
> 本地用户数据储存初始化失败，这一般发生在重复运行 kazumi 而产生资源竞争的场合
> 
> 或者在出现权限问题导致无法访问用户数据目录时，也可能出现这一错误
> 
> 尝试使用wheel用户组或更高级别的用户操作

随后我查看了我的用户权限信息，看起来我应该是有wheel级别的权限的。
![2024-09-04-210922_hyprshot](https://github.com/user-attachments/assets/a158d5c7-1d5a-43c9-9032-4438e3d0a7af)

你说的无法访问用户数据目录，我不清楚指的是不是webkit-gtk没有权限来访问用户目录。或者还有其他建议？

**Comment by kjrin710** [comment]
> Kazumi 需要一个目录来储存追番以及历史记录等信息，实在不行你用 sudo 运行试试

sudo运行只会输出以下信息：
0.29.1 (git 6a7cd03) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux 4KB x86_64; glibc2.24/2.39 libc++190100; Clang19.1.0 (++20240826073158+5f744ee5c770-1~exp1~20240826073300.27); 12:05:46 Sep  1 2024
Authorization required, but no authorization protocol specified


(kazumi:29421): Gtk-WARNING **: 22:49:23.316: cannot open display: :0

**Comment by Predidit** [comment]
我不知道为什么会这样，因为 linux 的高度碎片化，我们无法保证kazumi在所有发行版中运行良好，特别是使用 .tar.gz 这种仅为方便二次打包的格式时。

我们测试linux构建的环境是 Manjaro Gnome，并没有遇到过类似问题。

如果需要进一步排查原因，可能需要安装flutter构建工具链进行编译与调试，导致错误的代码在 /lib/main.dart 中储存初始化的部分，你可以尝试在哪里打印日志而不是简单地重定向到错误页面。

如果你取得进展的话，并确认这是kazumi代码中的错误，可以尝试提交PR

**Comment by pugaizai** [comment]
你可能需要xdg-user-dirs

**Comment by kjrin710** [comment]
> 你可能需要xdg-user-dirs

是的，按照你的建议安装xdg-user-dirs后问题已经解决了，目前kazumi运行完全符合预期，感谢你的帮助！
