### ISSUE TITLE
[Bug]: 最新版，完全无法使用

### ISSUE THREAD

**Issue by yll-zynmt** [Predidit/Kazumi#202]
### 在使用的时候发生了什么 Bug ？

![image](https://github.com/user-attachments/assets/2cde2684-3130-444b-9c83-5ae9f225aafd)
![image](https://github.com/user-attachments/assets/3c3cd670-1d40-494e-9009-680e9c97c769)
![image](https://github.com/user-attachments/assets/b74d5c8d-be00-4029-9d44-27cbff2a611f)
![image](https://github.com/user-attachments/assets/64011d3c-697d-4a44-8eb7-cccd01a664c4)
![image](https://github.com/user-attachments/assets/8d75a6a9-965a-43e8-86e3-d2f9a3c37c87)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

win10  22H2  19045.4780

### （选填）一些与 Bug 相关的硬件信息。

第一次使用，是最新版，刚下载，各个源都无法使用。
随便点开一个，都是 《服务器异常，请稍后重试》，哪怕能点进集数（80tv偶尔会出现列表，其他源是全空白），打开也是各种错误日志《解析视频资源超时》等等，参照截图

### 日志信息

```shell
错误日志是空的
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
尽量别用日本的代理，可能是考虑到版权问题，大部分视频源都是禁止日本IP的

**Comment by yll-zynmt** [comment]
原来如此，好的吧，辛苦了
