### ISSUE TITLE
搜索番剧信息不全

### ISSUE THREAD

**Issue by Alvin-Blithe** [Predidit/Kazumi#203]
### issue 内容

使用搜索功能时，国产动漫有不少无法识别，但这些源网站是有的，比如下面这个
![image](https://github.com/user-attachments/assets/34f4b8eb-c56e-4eb2-a3c8-0e8697464e5d)
![image](https://github.com/user-attachments/assets/e4292e8d-fefe-487d-947f-3b70b542c8ee)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
没有提供国产动画支持的计划

**Comment by Alvin-Blithe** [comment]
好的，辛苦作者大大
