### ISSUE TITLE
通过时间表打开的番会导致某些规则不可用

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#204]
### 在使用的时候发生了什么 Bug ？

下图为通过时间表打开的邻座遮羞的次元城规则，无法识别
![IMG_0698](https://github.com/user-attachments/assets/8e7d3c01-2bcc-40dc-9a07-941d51e2e360)
下图为通过搜索打开的邻座遮羞的次元城规则，可用
![IMG_0697](https://github.com/user-attachments/assets/925979dd-5085-462f-a6dc-e64d467294d0)

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipados 16

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by YCZ01111** [comment]
补充，从追番中进入也无法识别源
另外，希望追番可以直接固定源

**Comment by YCZ01111** [comment]
补充，从搜索框搜索的番剧在匹配规则时貌似是以输入内容作为关键词。
比如若我输入的是“遮羞”，则可以匹配到次元城中的“不时轻声地以俄语遮羞的艾莉同学”。如果我输入的是“不时用俄语小声说真心话的艾莉同学”，则匹配不到次元城中的番。
估计追番和时间表也是同理。因此我希望每个番都绑定多个别名作为关键词，防止因番名不一样导致规则匹配不到的情况。

**Comment by Predidit** [comment]
和 #53 重复
