### ISSUE TITLE
为此软件构建Flatpak包的许可

### ISSUE THREAD

**Issue by first-storm** [Predidit/Kazumi#206]
### issue 内容

我已经构建完成，这可以极大便利Linux用户的使用。
请求打包的许可。这是flathub官方要求的。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
感谢您杰出的工作。

您有我的许可，您可以向flathub提交上架申请。

我对flatpak缺乏经验，我在这里提出一个可能的问题，这个问题解决与否并不影响我的许可。

这个构建是基于release中的tar.gz再度打包还是重新编译的，如果是后者的话，由于没有使用特别裁剪过的ffmpeg库，可能会丢失一些非标准格式视频流支持。

**Comment by first-storm** [comment]
> 感谢您杰出的工作。
> 
> 您有我的许可，您可以向flathub提交上架申请。
> 
> 我对flatpak缺乏经验，我在这里提出一个可能的问题，这个问题解决与否并不影响我的许可。
> 
> 这个构建是基于release中的tar.gz再度打包还是重新编译的，如果是后者的话，由于没有使用特别裁剪过的ffmpeg库，可能会丢失一些非标准格式视频流支持。

是用deb包再打包的。flathub编译时不允许联网，重新编译非常麻烦而且不划算。
