### ISSUE TITLE
能否自定义Github镜像链接

### ISSUE THREAD

**Issue by QwindF** [Predidit/Kazumi#209]
### issue 内容

1.3.0 安卓版本能否使用自己的github镜像，我发现启用默认提供的github镜像服务还是会导致“网络连接超时”。
但是规则都可以正常更新下载（我不确定是不是这个问题）

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
只要有任意网络请求失败，就会有网络连接超时的提示

一般规则装太多了，有些规则不可用导致的，和镜像没有关系

**Comment by QwindF** [comment]
感谢提醒
