### ISSUE TITLE
1.1.5版本安卓平板适配的小问题

### ISSUE THREAD

**Issue by shangjin2001** [Predidit/Kazumi#21]
首先感谢作者大大对安卓平板的适配，绝大多数的适配很好，但是也存在一点小问题，在播放视频时如果点击全屏，会强制转换为竖屏然后再横屏全屏，如图
![Screenshot_20240630_161621](https://github.com/Predidit/Kazumi/assets/76458667/f72b8873-318a-4550-a196-c622b61ffa45)
![Screenshot_20240630_161631](https://github.com/Predidit/Kazumi/assets/76458667/51d12a3a-a0d3-4813-9343-d7fa12c5df2d)

**Comment by Predidit** [comment]
点击全屏之后是会竖屏全屏，需要手动通过系统提供的屏幕旋转选项旋转。还是竖屏会一闪而过然后正确横屏全屏呢。

系统ROM是哪个厂商的呢，什么版本。不同安卓平板的屏幕旋转处理不太一样。

**Comment by shangjin2001** [comment]
是竖屏会一闪而过然后正确横屏全屏，安卓平板版本信息如下
![Screenshot_20240630_164032](https://github.com/Predidit/Kazumi/assets/76458667/75440776-5d1e-4247-a110-3bd374d8fa73)

**Comment by Predidit** [comment]
退出全屏的过程正常吗，会不会先竖屏一下再横屏。

**Comment by shangjin2001** [comment]
推出过程是正常的

**Comment by Predidit** [comment]
实际上我不能在我的平板上复现这一问题，安卓平板间的差距比较大。

我构建了一个测试版本，Issue里只能上传 .zip 不能上传 .apk，解压这个 .zip 将得到 apk

[tablet_fullscreen.zip](https://github.com/user-attachments/files/16044121/tablet_fullscreen.zip)

尝试这个版本是否能正确进入全屏与正确退出全屏，可以的话这个修改将包含在下个版本中。

**Comment by shangjin2001** [comment]
你好，经过测试，该版本可以正常进入与退出全屏模式，非常感谢(≧∇≦)ﾉ
