### ISSUE TITLE
关于多个资源节点的读取问题

### ISSUE THREAD

**Issue by XHXYT** [Predidit/Kazumi#210]
### issue 内容

以这个页面为例https://www.jibi.cc/index.php/vod/detail/id/10474.html，进网页可以看到有两条线路，但是在软件里读取时只能读到一条线，我尝试了两种写法：
第一种ChapterRoads：//div/div[2]/div/div[3]     ChapterResult：//div[2]/div/div/a
第二种ChapterRoads：//div/div[2]/div/div[3]div[2]/div/div/     ChapterResult：//a
这两种写法都只能读到一条线路，感觉有点奇怪，
附：
SearchUrl：https://www.jibi.cc/index.php/vod/search.html?wd=@keyword
SearchList：//div/div[2]/div/div/div[3]
SearchName：//div/div[2]/div/a
SearchResult：//div/div[2]/div/a

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
ChapterRoads: //div/div[2]/div/div[3]/div/div/div

ChapterResult: //a

你可以比较以下两条线路的差异，然后把差异的部分抹掉就可以了
