### ISSUE TITLE
[Bug]: 弹幕区域貌似并不能正确发挥作用

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#211]
### 在使用的时候发生了什么 Bug ？

当我调节弹幕区域后，并没有发生变化，始终保持25%左右（推测）。（我第一次用的时候好像是铺满的，调成25%之后就一直这样了）
并且当我离开软件再回到软件，又或者是重启软件后，弹幕区域设置条会回到100%，但实际上还是25%（并没有铺满）。
当我暂停番剧并调节弹幕区域后，首次取消暂停后番剧会正常播放但弹幕会卡住不动，当我再次暂停并再次播放后，弹幕恢复正常。
用的ipad

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipados16

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
我复现了这两个错误，感谢你的报告

**Comment by Predidit** [comment]
1.3.1 版本已经发布
