### ISSUE TITLE
[Bug]: 视频无法播放/黑屏

### ISSUE THREAD

**Issue by Dekurri** [Predidit/Kazumi#212]
### 在使用的时候发生了什么 Bug ？

windows11系统，点击番剧无法播放
![屏幕截图 2024-09-09 102610](https://github.com/user-attachments/assets/0c1bd576-0566-4ee9-b319-dae51ead66af)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

windows11

### （选填）一些与 Bug 相关的硬件信息。

显卡型号：NCIDIA GeForce RTX4070 Laptop GPU
显卡驱动 game ready 552.12

### 日志信息

```shell
**2024-09-09 09:57:59.394082** 
 解析推荐列表错误 type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
参考 #175

**Comment by Dekurri** [comment]
感谢作者，换全局代理后已解决

**Comment by santuliu** [comment]
怎么换全局代理
