### ISSUE TITLE
关于内置播放器的功能请求

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#213]
### issue 内容

1、希望在全屏时的上方控制面板的中央加入当前现实时间（尤其是移动端）
2、希望在全屏时左上角返回按钮旁显示番名以及集数
3、希望拖动快进时显示目标时间点/总时长，而不是多少秒
4、希望添加全屏时锁定功能#76 
5、希望记住弹幕的启用或关闭状态，而不是每一集都要去手动开启

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这些功能会在 1.3.2 中考虑实现

现在设置选项卡的弹幕设置里可以设置弹幕默认状态

播放器上方太拥挤了，我要想一想怎么做比较好

**Comment by Predidit** [comment]
这是一个特定于iOS的问题，和音量的问题不同，我对亮度调节不生效的问题毫无头绪，使用亮度调节手势时会出现亮度条吗

**Comment by YCZ01111** [comment]
> 这是一个特定于iOS的问题，和音量的问题不同，我对亮度调节不生效的问题毫无头绪，使用亮度调节手势时会出现亮度条吗

会出现这个，数值是正确的，但不论如何滑动，都没有变化
![IMG_0709](https://github.com/user-attachments/assets/d93e4a26-f5c5-4b15-829a-7bbf7a92c606)

**Comment by Predidit** [comment]
能出现亮度条就不是 dart 侧的问题，这需要在 native 侧进行 swift 相关的调试，这需要拥有 Xcode 开发环境的开发者的帮助

**Comment by YCZ01111** [comment]
> 能出现亮度条就不是 dart 侧的问题，这需要在 native 侧进行 swift 相关的调试，这需要拥有 Xcode 开发环境的开发者的帮助

很遗憾，并没有mac，也没有Xcode～

**Comment by YCZ01111** [comment]
还有一个小建议我就不单独开issue了
就是历史记录是不是可以从设置中弄出来，放在追番按钮的上面或下面，目前来说历史记录的体验以及使用频率都比追番页面要高

**Comment by YCZ01111** [comment]
> 这要和移动设备保持一致，移动设备下部导航栏有五个按钮的话太拥挤了，我考虑一下

你看这样如何，在设置中历史记录那一项提供可滑动的预览，这样即使不用点进历史记录也可以直接点击番剧

**Comment by kurikoo23** [comment]
> 能出现亮度条就不是 dart 侧的问题，这需要在 native 侧进行 swift 相关的调试，这需要拥有 Xcode 开发环境的开发者的帮助

感觉应该是滑动判定的问题，滑动速度慢就没变化，滑动速度快就可以调节

**Comment by YCZ01111** [comment]
> > 能出现亮度条就不是 dart 侧的问题，这需要在 native 侧进行 swift 相关的调试，这需要拥有 Xcode 开发环境的开发者的帮助
> 
> 感觉应该是滑动判定的问题，滑动速度慢就没变化，滑动速度快就可以调节

我刚试了一下，有细微的变化，但是数值没变，好像被限制在系统亮度上下的一个非常小的范围内。

**Comment by Predidit** [comment]
https://github.com/Predidit/Kazumi/actions/runs/10792217350/artifacts/1914040223

试试这个构建，我调高灵敏度

**Comment by Predidit** [comment]
> > https://github.com/Predidit/Kazumi/actions/runs/10792217350/artifacts/1914040223
> > 试试这个构建，我调高灵敏度
> 
> 提高了什么的灵敏度？我并没有发现什么变化

滑动手势的灵敏度，看上去好像没什么效果 sad

**Comment by YCZ01111** [comment]
> 亮度的灵敏度，因为上面提到亮度在大幅滑动的情况下可能可以调节
> 
> 好消息是，我重新审视这部分代码之后，找到了可能的解决方案，尝试下面的构建
> 
> https://github.com/Predidit/Kazumi/actions/runs/10792676241/artifacts/1914158361
> 
> 这是应该是我最后一次尝试了，没有测试设备的情况下做这种补丁感觉像在算命

现在的情况是，可以调节亮度了，但是有bug，这个bug貌似跟触摸时长有关，当我快速滑动并抬起时，亮度能有效调节。当我缓慢滑动时，假设当前亮度为60，那么若我向下缓慢滑动，则亮度会在59和60反复横跳，若我稍微加快点速度，那么亮度会在40到60中间循环，话的越快，循环范围越大。也就是说每滑动一段时间后亮度貌似会回到原点。

**Comment by Predidit** [comment]
这个 Bug 是这样的，我不知道为什么 iOS 取得一次当前屏幕亮度会被 android 慢那么多

播放器每隔一秒会从系统校准一次当前亮度，以防止在播放器页面使用系统状态栏调节亮度，导致亮度数据脱钩而出现的混乱。

这在 android 上运行良好，但在 iOS 上，同步耗时过长，导致同步的结果相较于当前调节亮度的动作是过时的，具体就表现会亮度跳跃到数十毫秒前的值

我能想到的解决方案就是调低 iOS 上的亮度调节灵敏度，这会缓解问题，我应该不会再发布一个实验性构建，而是在下个版本直接调低灵敏度

**Comment by YCZ01111** [comment]
> 这个 Bug 是这样的，我不知道为什么 iOS 取得一次当前屏幕亮度会比 android 慢那么多
> 
> 播放器每隔一秒会从系统校准一次当前亮度，以防止在播放器页面使用系统状态栏调节亮度，导致亮度数据脱钩而出现的混乱。
> 
> 这在 android 上运行良好，但在 iOS 上，同步耗时过长，导致同步的结果相较于当前调节亮度的动作是过时的，具体就表现会亮度跳跃到数十毫秒前的值
> 
> 我能想到的解决方案就是调低 iOS 上的亮度调节灵敏度，这会缓解问题，我应该不会再发布一个实验性构建，而是在下个版本直接调低灵敏度

不能直接调节系统亮度吗？

**Comment by YCZ01111** [comment]
> 这个 Bug 是这样的，我不知道为什么 iOS 取得一次当前屏幕亮度会比 android 慢那么多
> 
> 播放器每隔一秒会从系统校准一次当前亮度，以防止在播放器页面使用系统状态栏调节亮度，导致亮度数据脱钩而出现的混乱。
> 
> 这在 android 上运行良好，但在 iOS 上，同步耗时过长，导致同步的结果相较于当前调节亮度的动作是过时的，具体就表现会亮度跳跃到数十毫秒前的值
> 
> 我能想到的解决方案就是调低 iOS 上的亮度调节灵敏度，这会缓解问题，我应该不会再发布一个实验性构建，而是在下个版本直接调低灵敏度

还有其他的bug，我现在无法通过系统下拉栏调节亮度，当我调节完回到软件，亮度会被强制调节会播放器原来的亮度。
还有就是亮度与数字之间有延迟，这并不应该出现。
虽然我对app开发并不了解，但我觉得这部分逻辑是错误的，因为我在其他软件中的体验（比如omo，已死）不是这样的。

**Comment by Predidit** [comment]
https://github.com/Predidit/Kazumi/actions/runs/10794712100/artifacts/1914747397

现在亮度值不会再跳动

**Comment by YCZ01111** [comment]
> 应用内调节的是应用亮度，不是系统全局亮度

我发现进入播放器后调节播放器亮度之前，其是跟随系统亮度变化的。
当我调节播放器亮度后，其就无法跟随系统亮度变化了。
播放器亮度可以控制系统亮度而系统亮度不能控制播放器亮度？
我觉得应用亮度内和系统亮度应该双向控制才对，现在是单向控制。

**Comment by YCZ01111** [comment]
> 应用内调节的是应用亮度，不是系统全局亮度

所以前面问题的解决方法就是将两个亮度分离开来吗～

**Comment by YCZ01111** [comment]
> 应用内调节的是应用亮度，不是系统全局亮度

市面上的视频软件都是直接调节系统亮度（笑），那样反而不是更简单吗。当然如果您觉得现在更好那就当我没说～

**Comment by Predidit** [comment]
跨平台应用开发是这样的

保证不同平台的体验完全一致是非常困难的，当出现差异是要做很多 workaround 

如果你恰好没有对应的设备可供调试，事情就变得更复杂了，你甚至有时不知道问题是什么

实际上我没有完全理解上面的文字描述提到的亮度问题，你可以录一个视频吗

**Comment by YCZ01111** [comment]
> 跨平台应用开发是这样的
> 
> 保证不同平台的体验完全一致是非常困难的，当出现差异是要做很多 workaround
> 
> 如果你恰好没有对应的设备可供调试，事情就变得更复杂了，你甚至有时不知道问题是什么
> 
> 实际上我没有完全理解上面的文字描述提到的亮度问题，你可以录一个视频吗

https://pan.240502.xyz/raw/RPReplay_Final1725985315.mp4
如果是直接调节系统亮度的话，应该不会出现延迟

**Comment by YCZ01111** [comment]
> 跨平台应用开发是这样的
> 
> 保证不同平台的体验完全一致是非常困难的，当出现差异是要做很多 workaround
> 
> 如果你恰好没有对应的设备可供调试，事情就变得更复杂了，你甚至有时不知道问题是什么
> 
> 实际上我没有完全理解上面的文字描述提到的亮度问题，你可以录一个视频吗


https://github.com/user-attachments/assets/e86af24a-38fb-4c64-9f62-69e9ef9060bf
录屏无法显示亮度变化，只能看到系统亮度条跳跃

**Comment by YCZ01111** [comment]
> 跨平台应用开发是这样的
> 
> 保证不同平台的体验完全一致是非常困难的，当出现差异是要做很多 workaround
> 
> 如果你恰好没有对应的设备可供调试，事情就变得更复杂了，你甚至有时不知道问题是什么
> 
> 实际上我没有完全理解上面的文字描述提到的亮度问题，你可以录一个视频吗


https://github.com/user-attachments/assets/7c4740b1-1446-4cbf-9c7b-65d270ddfc5d
附件不能超过10mb。。。。不知道你能否看懂这简短的视频

**Comment by kurikoo23** [comment]
> https://github.com/Predidit/Kazumi/actions/runs/10794712100/artifacts/1914747397
> 
> 现在亮度值不会再跳动

最新的这个构建已经可以正常调节应用内亮度了，不过也确实存在楼主所说的现象，我拍了个视频简单复现了一下。

https://github.com/user-attachments/assets/fb5c93df-700f-4a40-b19f-52b97a1d8b7a

现象描述：在进入kazumi首次使用手势调节应用内亮度前，在控制中心可以调节全局亮度，包括kazumi内的亮度。当在kazumi内使用手势调节了应用内亮度后，呼出控制中心或切换到其他应用都会恢复之前的亮度，这时kazumi内的亮度和其他场景的亮度为独立的，各自调节互不影响。

个人认为这应该是正常现象，iOS的亮度调策略可能就是如此：通常状态下调节亮度为全局调节，当某个应用调节了应用内亮度，这时再调节全局亮度只用影响除这个应用以外的其他场景，只有完全退出这个应用才会恢复完全的全局调节。

如果想避免出现这个现象应该只能将kazumi的手势亮度调节改为调节全局亮度。

**Comment by Predidit** [comment]
Kazumi所使用的亮度插件只能设置应用亮度，不能设置全局亮度。

我们当然可以像在 Linux/windows 上做的那样，根据自己的需要修改插件，但这涉及原生互操作，在没有测试设备的情况下几乎是不可能完成的。

**Comment by YCZ01111** [comment]
> 这些功能会在 1.3.2 中考虑实现
> 
> 现在设置选项卡的弹幕设置里可以设置弹幕默认状态
> 
> 播放器上方太拥挤了，我要想一想怎么做比较好

关于显示时间的显示，b站全屏时唤出控制面板的同时是显示系统本身的上栏的，并且是透明显示。这点也许在不同平台实现有些困难？
上方太拥挤的话也许可以把倍速移下来
关于左上角的显示我认为集数在前会更好，这样即使由于番名过长而被隐藏部分也能先看到集数

**Comment by WhiteXero** [comment]
> 这些功能会在 1.3.2 中考虑实现
> 
> 现在设置选项卡的弹幕设置里可以设置弹幕默认状态
> 
> 播放器上方太拥挤了，我要想一想怎么做比较好

也许可以考虑做二级菜单了？

就是点一下按钮出现侧边菜单的功能。很多视频软件的播放器也是这么设计的

**Comment by Predidit** [comment]
@YCZ01111 

可以帮忙测试一下这个构建吗 

https://github.com/Predidit/Kazumi/actions/runs/10971314261/artifacts/1961381599

我在修复带刘海/打孔的 android/iOS 设备在全屏时，视频不在屏幕正中间的问题，我怀疑这一补丁可能会在 iOS 上导致 #187 的回归。

**Comment by YCZ01111** [comment]
> @YCZ01111
> 
> 可以帮忙测试一下这个构建吗
> 
> https://github.com/Predidit/Kazumi/actions/runs/10971314261/artifacts/1961381599
> 
> 我在修复带刘海/打孔的 android/iOS 设备在全屏时，视频不在屏幕正中间的问题，我怀疑这一补丁可能会在 iOS 上导致 #187 的回归。

没有发现问题

**Comment by Predidit** [comment]
屏幕锁定已经实现

由于显示现实时间没有计划，本 Issue 已经完成

**Comment by YCZ01111** [comment]
> 屏幕锁定已经实现
> 
> 由于显示现实时间没有计划，本 Issue 已经完成

我觉得像b站那样加一层显示时间，网络，电量还是很舒服的
