### ISSUE TITLE
[Bug]: 内置播放器受静音模式影响（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#214]
### 在使用的时候发生了什么 Bug ？

我不知道是如何触发的，到今天凌晨为止内置播放器一直是正常的，而今天中午突然没有声音了
我尝试了完全卸载重装，并没有解决
我尝试关闭静音模式，发现只有关闭静音模式后内置播放器才有声音，而在此之前我也是一直开着静音模式的，今天才出现这个情况
![IMG_0707](https://github.com/user-attachments/assets/364bcf7e-b787-4029-829e-df820d3d255f)

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipados16

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
我提交了一个简单的补丁来修复这个问题，但我并没有设备来测试这个修复是否有效，你能帮我测试一下吗

对应的构建为  https://github.com/Predidit/Kazumi/actions/runs/10770406330/artifacts/1908159762

**Comment by YCZ01111** [comment]
> 我提交了一个简单的补丁来修复这个问题，但我并没有设备来测试这个修复是否有效，你能帮我测试一下吗
> 
> 对应的构建为 https://github.com/Predidit/Kazumi/actions/runs/10770406330/artifacts/1908159762

我试了一下，目前看来是解决了

**Comment by Predidit** [comment]
1.3.1 版本已经发布

**Comment by YCZ01111** [comment]
次元城可以用内置播放器了诶，别的规则我没有试，作者别忘了把规则仓库中的这些受到此次更新福利的规则修改一下

**Comment by Predidit** [comment]
次元城在windows上不能用内置播放器，之前测试的视频解析器改进的时候就发现了，所以暂时不会修改这条规则。

我对此感到很困惑，实际上在 windows 上也可以正确获取视频的真实地址，格式和其他平台相同，但是不知道为什么地址会返回403错误。

**Comment by YCZ01111** [comment]
> 次元城在windows上不能用内置播放器，之前测试的视频解析器改进的时候就发现了，所以暂时不会修改这条规则。
> 
> 我对此感到很困惑，实际上在 windows 上也可以正确获取视频的真实地址，格式和其他平台相同，但是不知道为什么地址会返回403错误。

我刚尝试了一下，在我的windows上次元城是可以使用内置播放器的，是否是您那边的问题

**Comment by Predidit** [comment]
好像确实可以，有兴趣在规则仓库提交一个相关PR吗

**Comment by YCZ01111** [comment]
> 好像确实可以，有兴趣在规则仓库提交一个相关PR吗

是需要我更改次元城的规则吗，我没有提交过PR，不太清楚应该怎么做

**Comment by Predidit** [comment]
Fork 规则仓库，在你 Fork 的分支里修改 index.json 和  ciyuancheng.json  中 ciyuancheng 的部分

将对应的 useNativePlayer 字段修改为 true，并修改 version (版本) 字段为更高的版本 (例如 1.1)

现在你 Fork 的分支和主分支出现了差异，在你 Fork 的仓库页面点击 Open a Pull Request，我或者仓库的其他协作者会审核你的PR，没有问题的话变动会被合并到主分支

**Comment by YCZ01111** [comment]
好的，我下午试一下
