### ISSUE TITLE
一个和项目有关的建议

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#215]
### issue 内容

建议作者将软件和规则完全分离开来，不要内置任何规则以及获取规则的通道。
规则可以放在某些社区之类的途径中，让用户自行下载并导入。
这个建议虽然会降低用户体验，但可以让该软件活的更久，是否采纳全看您自己。
这是某位前辈给的建议，他称这种做法为“枪弹分离”

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
感谢你的提醒，我会在后续版本移除默认规则。

其实我们不是很担心相关风险，我们没有插入任何广告，没有注册用户，不管理任何服务器。我们没有接受任何捐助，没有从此项目中以任何形式获利。没有以维护者的身份建立交流群组。
