### ISSUE TITLE
集数顺序问题

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#217]
### issue 内容

因为有些网站的集数采用的是倒序，所以会出现在Kazumi中的第一集按钮其实对应的是最后一集的情况。
是否可以直接获取ChapterRoads文本内容作为集数标签，然后在选集列表中按照正序排序，以适应内置播放器的下一集按钮
或者可以直接在规则中添加一项设置，用于匹配正序或倒序的情况（个人认为这个方法最好）
### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
有些站点不同播放列表排序方式不同

**Comment by YCZ01111** [comment]
> 有些站点不同播放列表排序方式不同

那是否可以像我说的一样直接获取ChapterRoads文本内容作为集数标签，然后再重新排序

**Comment by Predidit** [comment]
可以，但是那样会增加规则编写的复杂度，需要加一条规则

并且这里有一个数据类型转换的问题，解析到的文本内容是字符串，格式可能是 第x话 第x集，或是大写数字/阿拉伯数字，需要将这些内容解析为一个整数，这里可能会出现一些问题

**Comment by YCZ01111** [comment]
我突然意识到集数顺序问题也会导致弹幕无法对应
在解决顺序问题前也许可以先在选集附近添加一个切换弹幕顺序或逆序匹配的按钮……
当然，这也许会使ui变得杂乱，所以并不是必要

**Comment by YCZ01111** [comment]
> 在 Eva03 重制版中会出现 **第21集（原版）** 紧跟 **第21集（重置）** 的情况，但在`video_page`中是以`第$count话`的形式表现，会造成观看者的迷惑，是否可以通过获取`ChapterResult` 中的 `innerText` 显示在列表中？我想这样应该不需要添加一条规则

和我上面的想法一样啊，可以不用进行文本到集数的转换，直接使用规则中的文本，并且给播放页面的选集添加一个正序反序的按钮，如果担心文本内容过长也许可以一行一集

**Comment by Predidit** [comment]
> 在 Eva03 重制版中会出现 **第21集（原版）** 紧跟 **第21集（重置）** 的情况，但在`video_page`中是以`第$count话`的形式表现，会造成观看者的迷惑，是否可以通过获取`ChapterResult` 中的 `innerText` 显示在列表中？我想这样应该不需要添加一条规则

我试试，说不定可行。

**Comment by ErBWs** [comment]
> > 在 Eva03 重制版中会出现 **第21集（原版）** 紧跟 **第21集（重置）** 的情况，但在`video_page`中是以`第$count话`的形式表现，会造成观看者的迷惑，是否可以通过获取`ChapterResult` 中的 `innerText` 显示在列表中？我想这样应该不需要添加一条规则
> 
> 和我上面的想法一样啊，可以不用进行文本到集数的转换，直接使用规则中的文本，并且给播放页面的选集添加一个正序反序的按钮，如果担心文本内容过长也许可以一行一集

可能是你的描述中涉及到了重新排序？

**Comment by YCZ01111** [comment]
> > > 在 Eva03 重制版中会出现 **第21集（原版）** 紧跟 **第21集（重置）** 的情况，但在`video_page`中是以`第$count话`的形式表现，会造成观看者的迷惑，是否可以通过获取`ChapterResult` 中的 `innerText` 显示在列表中？我想这样应该不需要添加一条规则
> > 
> > 
> > 和我上面的想法一样啊，可以不用进行文本到集数的转换，直接使用规则中的文本，并且给播放页面的选集添加一个正序反序的按钮，如果担心文本内容过长也许可以一行一集
> 
> 可能是你的描述中涉及到了重新排序？

因为有些网站是逆序啊，这个问题现在就是存在的，只不过因为标签的统一导致外表看不出来罢了

**Comment by Predidit** [comment]
在 1.3.8 修复
