### ISSUE TITLE
考虑过兼容eso规则吗？

### ISSUE THREAD

**Issue by aooiuu** [Predidit/Kazumi#22]

**Comment by Predidit** [comment]
ESO 是个非常优秀的项目。

这个项目的动态化程度非常高，项目可拓展性非常高，我对这个项目的具体实现是充满敬意的。

但是flutter的发展方向并不是动态化，随着flutter的演进，ESO使用的大量支撑其动态化特性的依赖已经不兼容现代flutter版本，ESO目前只能使用古董flutter版本才能编译通过，这可能也是ESO目前表现出停滞的原因之一。

从技术角度来说，如果要兼容eso规则，我们需要重新实现一次ESO的解释器与动态化引擎。在目前的flutter版本与特性下，这比ESO编写时要更加困难。

从用户角度考虑，这可能会增加规则编写的难度，毕竟ESO规则的编写和Kazumi规则编写的难度几乎不在同一量级，我个人希望避免规则编写的复杂化。
