### ISSUE TITLE
win端，是否能增加置顶功能，另外在不使用全屏情况下是否能加个上下一集快捷按键

### ISSUE THREAD

**Issue by NPC-CBoy** [Predidit/Kazumi#220]
### issue 内容

置顶功能建议用小能自由缩放的小屏功能实现。另外顺嘴提一句，安卓版分窗小屏是竖屏，这样在播放时全屏播放只占显示小屏的三分至一。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
置顶功能和非全屏的下一集按钮没有计划

安卓平板的分屏适配问题

尝试 https://github.com/Predidit/Kazumi/actions/runs/10824895166/artifacts/1923147999

看看这个构建有没有问题

**Comment by Aries014** [comment]
置顶功能可以找其他软件之类的代替，我是使用autohotkey。下一集可以点击播放列表啊
