### ISSUE TITLE
从追番和时间表进入显示动漫简介

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#224]
### issue 内容

目前只有搜索出来的番剧打开才有简介，从追番和时间表打开是空的。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这可能是你的错觉，有没有简介是和番剧条目本身关联的，而不是和进入的方式关联的。

Bangumi API 返回的内容和 Bangumi 官网内容并不是完全一致的，对于新番来说，一般要等待至少一个月，对应的简介才能在 API 中获取。所以大部分时间表里的新番的简介都是空的。

**Comment by YCZ01111** [comment]
> 这可能是你的错觉，有没有简介是和番剧条目本身关联的，而不是和进入的方式关联的。
> 
> Bangumi API 返回的内容和 Bangumi 官网内容并不是完全一致的，对于新番来说，一般要等待至少一个月，对应的简介才能在 API 中获取。所以大部分时间表里的新番的简介都是空的。

搜索出来的新番有简介，时间表和追番的没有

**Comment by Predidit** [comment]
我需要一个例子🌰

**Comment by YCZ01111** [comment]
![IMG_0747](https://github.com/user-attachments/assets/c8a52475-47e8-46b3-afa0-3043464a5565)
![IMG_0748](https://github.com/user-attachments/assets/ac0cfc6b-be2b-4899-ae9f-ad9db3e62e65)

**Comment by YCZ01111** [comment]
我刚发现序号竟然也不一样

**Comment by YCZ01111** [comment]
可能跟序号无关，这个是序号相同的
![IMG_0749](https://github.com/user-attachments/assets/324255f0-3724-41a7-93bf-f2dc9196d724)
![IMG_0750](https://github.com/user-attachments/assets/0dcf3cb2-e76a-40f3-afbd-ef35c124e6b0)

**Comment by Predidit** [comment]
我知道问题可能在哪了，你试试取消一下追番，然后在搜索页面把追番加回去，看看新的追番有没有介绍

**Comment by Predidit** [comment]
为了减轻 Bangumi API 的压力，追番之后，番剧的元数据就被保存了，再查看追番时会使用之前保存的数据

如果保存的时候介绍还没有更新，就没有介绍，保存时介绍已经有了的话，就能查看介绍

那个 # 开头的不是编号，是番剧在 Bangumi 站内的用户打分排行，所以经常会有变动而不一致

所以这是一个预期行为

**Comment by Predidit** [comment]
时间表API的返回的数据不包含简介，所以没有显示，如果从这里追番的话就没有介绍

**Comment by Predidit** [comment]
总之 Bangumi API 的设计怎么说呢，非常有特色

不同接口返回的番剧的数据结构经常是完全不同的

**Comment by YCZ01111** [comment]
> 总之 Bangumi API 的设计怎么说呢，非常有特色
> 
> 不同接口返回的番剧的数据结构经常是完全不同的

是否可以在通过时间表打开的时候注入搜索api的简介数据呢

**Comment by Predidit** [comment]
没什么好方法，只能在时间表打开时再异步请求一次。

最后的效果要么是时间表打开后要过几秒才能看到简介刷出来

要么就是从时间表打开详情时要转圈圈

**Comment by YCZ01111** [comment]
> 没什么好方法，只能在时间表打开时再异步请求一次其他接口。
> 
> 最后的效果要么是时间表打开后要过几秒才能看到简介刷出来
> 
> 要么就是从时间表打开详情时要转圈圈

或者不用在时间表中显示出来，只在加入追番时后台获取一次，以保证从追番打开有简介

**Comment by Predidit** [comment]
看上去 Bangumi API 的问题修复没有什么指望

试试这个构建 https://github.com/Predidit/Kazumi/actions/runs/10859846247/artifacts/1932634242

**Comment by YCZ01111** [comment]
> 看上去 Bangumi API 的问题修复没有什么指望
> 
> 试试这个构建 https://github.com/Predidit/Kazumi/actions/runs/10859846247/artifacts/1932634242

看上去没有什么问题

**Comment by YCZ01111** [comment]
> 看上去 Bangumi API 的问题修复没有什么指望
> 
> 试试这个构建 https://github.com/Predidit/Kazumi/actions/runs/10859846247/artifacts/1932634242

我之前不是建议将拖动时间改为目标时间/总时长吗，我发现你这个构建已经实装了。
但我用下来发现，跳op的时候还是原来的显示秒数好使
还是改回去吧
抱歉让您做了无用功

**Comment by Predidit** [comment]
我倾向于保留现在的方案，B站的方案也是这样的

**Comment by YCZ01111** [comment]
> 我倾向于保留现在的方案，B站的方案也是这样的

b站全屏拖动的时候是会显示控制面板和画面预览的
这一点实现比较困难，但是也可以只把控制面板显示出来，用于对比目标时间和当前时间，因为跳op大约都是1分半，这需要一个起点。
还有就是b站拖动的时候是不会暂停的，看看这点能不能实现（不重要）

**Comment by YCZ01111** [comment]
还有就是未全屏的情况下进度和倍速手势有效但是亮度和音量手势无效，这点是不是可以统一一下。

**Comment by Predidit** [comment]
包含动漫简介修复的 1.3.2 已经发布
