### ISSUE TITLE
希望为历史记录添加批量选择删除功能

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#225]
### issue 内容

现在历史记录只能全部清空，希望可以在右上角加个“编辑”或者是图标之类的，点击后可以选择一条或多条记录进行删除

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by YCZ01111** [comment]
顺便一提，希望历史记录可以显示总集数，比如“上次看到：第9话/共12话”
但这样对于新番来说可能很麻烦，需要每次打开历史记录都去获取对应源的集数
也许有更好的解决办法？
个人认为可以考虑一下bangumi的追番和历史记录

**Comment by Predidit** [comment]
bangumi api 的登录态维持一直有问题，容易掉登录状态，而且他的进度同步是以番剧为单位的，多视频源的情况下不是很兼容。

**Comment by YCZ01111** [comment]
> bangumi api 的登录态维持一直有问题，容易掉登录状态，而且他的进度同步是以番剧为单位的，多视频源的情况下不是很兼容。

其实我早就觉得咱这个历史记录没必要分源，每个番就保存最后一次观看的源就够了，没有人会一个番来回切换源看吧。就算切换源看也不会从历史记录里找，因为现在的历史记录由于每个源单独保存所以乱得很。
所以我推荐历史记录只保存最后一次的就好了。
同时这样也可以同步bangumi

**Comment by Predidit** [comment]
包含 历史记录添加批量选择删除功能 的 1.3.2 已经发布
