### ISSUE TITLE
[bug]：android/iOS 偶发的视频比例错误

### ISSUE THREAD

**Issue by WseNaoBran** [Predidit/Kazumi#226]
###使用时发生了什么错误？当视频播放时长按屏幕倍速播放时，视频比例会被横向压缩，需要刷新后才能恢复

![F9E7BD30-B57E-4B34-88F6-9AA3F9C8865B](https://github.com/user-attachments/assets/a7d7bb19-3018-46fd-9b5d-0c7b28323770)

### 您使用哪个操作系统？macOS/iOS操作系统###请具体提供设备、版本号等信息。苹果手机6s ios15.7.8###（选填）一些与Bug相关的硬件信息。_没有回应_### 日志信息```贝壳无```### 提交前确认- [X]问题 列表中，没有我发现的这个错误- [X] 我正在使用最新版本的Kazumi

**Comment by Predidit** [comment]
图裂开了，上传完成图片后再提交评论

**Comment by Predidit** [comment]
图片嵌入还是有问题，这样查看起来很麻烦。图里有什么问题吗，不是正常的非全屏模式吗，比例也是正确的 16:9

**Comment by WseNaoBran** [comment]
>图片嵌入还是有问题，这样看起来很麻烦。图里有什么问题吗，不是正常的非全屏模式吗，比例也是正确的16:9

视频会被压缩成1:1的状态，松开后也会继续保持这样播放，要刷新视频重新播放才会恢复
![BE85532B-4D29-4F77-9079-6FA42FEF94B5](https://github.com/user-attachments/assets/2c9a7de2-ac6f-440f-815e-a624dec377d2)

**Comment by Predidit** [comment]
调整倍速可以恢复吗，全屏模式下使用长按倍速会被压缩吗

**Comment by WseNaoBran** [comment]
> 调整倍速可以恢复吗，全屏模式下使用长按倍速会被压缩吗

不会恢复，全屏和非全屏都一样

**Comment by Predidit** [comment]
我对这个问题感到很困惑，我没有设备用来测试并复现这个问题。

有一个打开的关于播放器的讨论在 #213 

其中有提到关于播放倍速的变更，@YCZ01111 主要使用ios设备，但他并没有提到这个问题

我怀疑这是一个特定于 iPhone6s 的兼容性问题。为了验证这一假设，你可以尝试在播放设置里禁用硬件解码，这将禁用iOS自带的AVPlayer组件，转而使用ffmpeg进行解码，尝试是否解决问题

**Comment by WseNaoBran** [comment]
> 我对这个问题感到很困惑，我没有设备用来测试并复现这个问题。
> 
> 有一个打开的关于播放器的讨论在 #213
> 
> 其中有提到关于播放倍速的变更，@YCZ01111 主要使用ios设备，但他并没有提到这个问题
> 
> 我怀疑这是一个特定于 iPhone6s 的兼容性问题。为了验证这一假设，你可以尝试在播放设置里禁用硬件解码，这将禁用iOS自带的AVPlayer组件，转而使用ffmpeg进行解码，尝试是否解决问题

真的可以了，看来真是这样，非常感谢！

**Comment by Predidit** [comment]
禁用硬件解码不仅有效能问题，还会导致部分视频无法正常播放。

AVPlayer是和iOS完全绑定的，更新或回退iOS版本可能会修复其中的问题。

**Comment by YCZ01111** [comment]
> 我对这个问题感到很困惑，我没有设备用来测试并复现这个问题。
> 
> 有一个打开的关于播放器的讨论在 #213
> 
> 其中有提到关于播放倍速的变更，@YCZ01111 主要使用ios设备，但他并没有提到这个问题
> 
> 我怀疑这是一个特定于 iPhone6s 的兼容性问题。为了验证这一假设，你可以尝试在播放设置里禁用硬件解码，这将禁用iOS自带的AVPlayer组件，转而使用ffmpeg进行解码，尝试是否解决问题

我遇到过，但是我无法复现，也许跟某些特定源有关

**Comment by YCZ01111** [comment]
> > 图片嵌入还是有问题，这样看起来很麻烦。图里有什么问题吗，不是正常的非全屏模式吗，比例也是正确的16:9
> 
> 视频会被压缩成1:1的状态，松开后也会继续保持这样播放，要刷新视频重新播放才会恢复 ![BE85532B-4D29-4F77-9079-6FA42FEF94B5](https://private-user-images.githubusercontent.com/157893083/367594138-2c9a7de2-ac6f-440f-815e-a624dec377d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTY1MjksIm5iZiI6MTcyNjQxNjIyOSwicGF0aCI6Ii8xNTc4OTMwODMvMzY3NTk0MTM4LTJjOWE3ZGUyLWFjNmYtNDQwZi04MTVlLWE2MjRkZWMzNzdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNjAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODEyNzI1ZjRjNTM2YzcyZTI3YjI3ODZkNjYxMzc5MDE3ZWQ1NjhlMDgxODFhNWJhMjY0MzQ5MTkzNTE1MGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7nPAcuj4k1GpYbF-3BR1UHcJzSuiHmzUKQptoXXOEjg)

你用的哪个规则

**Comment by WseNaoBran** [comment]
> > > 图片嵌入还是有问题，这样看起来很麻烦。图里有什么问题吗，不是正常的非全屏模式吗，比例也是正确的16:9
> > 
> > 
> > 视频会被压缩成1:1的状态，松开后也会继续保持这样播放，要刷新视频重新播放才会恢复 ![BE85532B-4D29-4F77-9079-6FA42FEF94B5](https://private-user-images.githubusercontent.com/157893083/367594138-2c9a7de2-ac6f-440f-815e-a624dec377d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTY1MjksIm5iZiI6MTcyNjQxNjIyOSwicGF0aCI6Ii8xNTc4OTMwODMvMzY3NTk0MTM4LTJjOWE3ZGUyLWFjNmYtNDQwZi04MTVlLWE2MjRkZWMzNzdkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNjAzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODEyNzI1ZjRjNTM2YzcyZTI3YjI3ODZkNjYxMzc5MDE3ZWQ1NjhlMDgxODFhNWJhMjY0MzQ5MTkzNTE1MGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7nPAcuj4k1GpYbF-3BR1UHcJzSuiHmzUKQptoXXOEjg)
> 
> 你用的哪个规则

确实，在girlgirllove上会有此情况，但DM84上不会。

**Comment by YCZ01111** [comment]
> 我对这个问题感到很困惑，我没有设备用来测试并复现这个问题。
> 
> 有一个打开的关于播放器的讨论在 #213
> 
> 其中有提到关于播放倍速的变更，@YCZ01111 主要使用ios设备，但他并没有提到这个问题
> 
> 我怀疑这是一个特定于 iPhone6s 的兼容性问题。为了验证这一假设，你可以尝试在播放设置里禁用硬件解码，这将禁用iOS自带的AVPlayer组件，转而使用ffmpeg进行解码，尝试是否解决问题

我刚试了一下，dms规则会稳定性触发

**Comment by Predidit** [comment]
很明显，这是一个来自AVPlayer和flutter的底层问题，由于没有测试设备，我无法按照常规的错误报告流程制作sample并上报。

我查看了最近的更新日志，有了一些推测，我会尝试回退AVPlayer插件的版本来解决这一问题。但今天有些太晚了，明天我会尝试发布一个测试构建。

**Comment by Predidit** [comment]
发布实验性修复的计划暂缓，要回退的目标版本会破坏macOS构建。

看上去我现在完全无法处理这个来自底层的问题，我们需要等待flutter或是AVPlayer的更新。

**Comment by YCZ01111** [comment]
> 发布实验性修复的计划暂缓，要回退的目标版本会破坏macOS构建。
> 
> 看上去我现在完全无法处理这个来自底层的问题，我们需要等待flutter或是AVPlayer的更新。

其实这个问题并不重要，多源的意义就在于此

**Comment by Predidit** [comment]
@ErBWs 

我们是否可以确认这一错误导致了视频比例问题。在倍速为 2.0 时, 视频比例是否正确。

如果可以确认的话，也许我们可以在全平台不再提供 2.0 以上的倍速选项。此外我们应该在对应位置添加注释。

**Comment by ErBWs** [comment]
> @ErBWs 
> 
> 我们是否可以确认这一错误导致了视频比例问题。在倍速为 2.0 时, 视频比例是否正确。
> 
> 如果可以确认的话，也许我们可以在全平台不再提供 2.0 以上的倍速选项。此外我们应该在对应位置添加注释。

2.0 时比例正确，基本可以确认是这个错误导致的比例错误

**Comment by Predidit** [comment]
@ErBWs 

好耶，可以提交一个PR吗

**Comment by ErBWs** [comment]
@Predidit 另外我还找到了一种解决办法，将 macOS/iOS 的硬件解码由 AVPlayer 换为 [VT](https://github.com/wang-bin/mdk-sdk/wiki/Decoders#vt)，使用苹果的 Video Toolbox 进行硬件解码，可以解决如下几个问题
1. 倍速播放问题
2. macOS 硬件解码会出现视频帧表现不正确，如跳帧、重复帧
3. #238

**Comment by ErBWs** [comment]
@Predidit 另外还找到一种解决办法，将 macOS/iOS 的硬件解码配置为 [VT](https://github.com/wang-bin/mdk-sdk/wiki/Decoders#vt)，使用 Apple 的 Video Toolbox 进行硬件解码，可以解决这些问题：
1. 播放倍速问题
2. macOS 硬件解码会出现帧表现错误，如跳帧、重复帧
3. #238

**Comment by Predidit** [comment]
@ErBWs 

在 fvp 的代码中看到 VT 是 macOS/iOS 上的默认解码方式。所以实际上如果要使用 fvp 实现的话，不配置硬件解码字段就可以了。

实际上在 macOS/iOS 上不使用 fvp 实现的原因是 #353

**Comment by Predidit** [comment]
1.4.1 已经发布
