### ISSUE TITLE
Windows端播放动漫时总会出现严重卡顿

### ISSUE THREAD

**Issue by 6713lyp** [Predidit/Kazumi#227]
无论换哪一个源总是在播放大约五六分钟后就会出现频繁卡顿或者直接一口气卡七八分钟，我换了好几个动漫又换了好几个源但总是会出现这种问题。APP不会有错误日志，但我的网络又是完全正常的。
          Windows系统和APP皆为最新版。

**Comment by Predidit** [comment]
最新版本应该没这个问题了，硬件解码开了吗
