### ISSUE TITLE
能否使用第三方的播放器播放

### ISSUE THREAD

**Issue by ZakiuC** [Predidit/Kazumi#23]
比如mx player之类的

**Comment by Predidit** [comment]
为什么会有这种需求呢。

合适的话我会加上的。

**Comment by MagicAt12138** [comment]
同上，我也有这样的需求，单纯用自己的播放器习惯了

**Comment by Predidit** [comment]
我想确认一下，即使调用自己的播放器会导致 收藏/历史记录/弹幕 功能失效，并且并不会加快加载速度，还会导致额外的资源占用。

仍然觉得这个功能是必要的吗。

**Comment by MagicAt12138** [comment]
> 我想确认一下，即使调用自己的播放器会导致 收藏/历史记录/弹幕 功能失效，并且并不会加快加载速度，还会导致额外的资源占用。
> 
> 仍然觉得这个功能是必要的吗。

我用emby一直有用第三方的习惯，我觉得你可以把这个第三方播放器设置按钮默认关闭

**Comment by ZakiuC** [comment]
> 我想确认一下，即使调用自己的播放器会导致 收藏/历史记录/弹幕 功能失效，并且并不会加快加载速度，还会导致额外的资源占用。
> 
> 仍然觉得这个功能是必要的吗。

之前用的[https://github.com/670848654/SakuraAnime](url)这个老哥的，他可以用第三方的播放器看，播放器用习惯了

**Comment by Takenforgranted** [comment]
> 我想确认一下，即使调用自己的播放器会导致 收藏/历史记录/弹幕 功能失效，并且并不会加快加载速度，还会导致额外的资源占用。
> 
> 仍然觉得这个功能是必要的吗。

我觉得还是不要轻易尝试吧，最多优化优化页面视频播放器啥的，我看到很多成熟的迭代了还几个版本的开源项目对于调用本地播放器仍然属于是实验功能。

**Comment by Predidit** [comment]
此功能已在 1.2.3 版本加入。

**Comment by MagicAt12138** [comment]
> 此功能已在1.2.3版本加入。

不好意思我并没有找到切换第三方播放器的入口
