### ISSUE TITLE
[Bug]: Android播放页面屏幕旋转存在bug

### ISSUE THREAD

**Issue by BlademasterQAQ** [Predidit/Kazumi#230]
### 在使用的时候发生了什么 Bug ？

https://github.com/Predidit/Kazumi/issues/216 中提到了不支持自动旋转。

但是软件有时候会支持旋转，会触发整个软件页面的旋转，此时画面的范围会超出屏幕。

请后续修复的时候注意，可以在非播放页面禁止页面旋转。

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

MIUI、Pixel均复现该问题，应该是Android适配问题。

### 日志信息

```shell
无错误
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
有截图吗，实际上我对这个问题有些困惑。

标题里在说播放页面的旋转问题，内容在说非播放页面的旋转问题。

部分页面支持旋转是为了适配平板，我需要知道哪些页面的问题比较严重。

**Comment by BlademasterQAQ** [comment]
主页面的适配没有什么问题。

下面分别是播放页面竖屏和横屏时候的显示，横屏是把整个软件横屏了，所以在21:9的屏幕下，播放器下面的控件会超出屏幕。
![image](https://github.com/user-attachments/assets/64df23ca-0716-4811-91c6-951985e70492)
![image](https://github.com/user-attachments/assets/ada61b3a-8f16-4a30-8fb6-abc32a797550)

**Comment by Predidit** [comment]
1.3.3 修复了该问题
