### ISSUE TITLE
[Bug]: macOS 上在搜索栏输入任意字符均闪退

### ISSUE THREAD

**Issue by NSFish** [Predidit/Kazumi#231]
### 在使用的时候发生了什么 Bug ？

百分百复现。

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

设备：mac mini M1
系统版本：macOS 14.6.1

### 日志信息

```shell
错误日志是空的。
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这在输入任意字符的情况下都会发生吗，还是只是在键入中文字符的情况下

**Comment by NSFish** [comment]
@Predidit 任意字符

**Comment by Predidit** [comment]
@NSFish 

看上去这是一个来自 flutter 的错误, 参考 [flutter/flutter#151428](https://github.com/flutter/flutter/issues/151428)

根据这里的讨论，这似乎和虚拟键盘相关，禁用虚拟键盘或许会解决问题

这个问题虽然一个半月前已经被标记为解决，但是对应补丁一直没有被 cherry-pick 到稳定分支，我们可能需要等待 flutter 稳定通道的下一次发布。

**Comment by Predidit** [comment]
在 1.4.7 修复
