### ISSUE TITLE
能否为MacOS窗口添加红绿灯🚥

### ISSUE THREAD

**Issue by Aruomeng** [Predidit/Kazumi#232]
### issue 内容

视频的放大只能通过右下角全屏，缩小的话会下意识按Esc缩小，但会直接退出软件，这一点有点反直觉。并且每次打开软件窗口又很小，因为没有全屏键，只能一点点拖大，希望可以实装红绿灯键🥸

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
红绿灯的观感很不协调，以及你有遇到 #231 中提到的问题吗
