### ISSUE TITLE
询问app更新规则问题

### ISSUE THREAD

**Issue by nicolai2024** [Predidit/Kazumi#233]
作者你好，我想咨询一下每次打开app底下都有提示检测到一条新规则可以更新，但是我找不到入口在哪里更新这条提示的规则，请作者教我一下，谢谢（app真的很好用）

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
规则管理->从规则仓库导入 可以更新的规则会显示更新按钮

**Comment by nicolai2024** [comment]
谢谢啦我学会了
