### ISSUE TITLE
[Bug]: 快进时显示快进的秒数没有了？

### ISSUE THREAD

**Issue by Suomm** [Predidit/Kazumi#237]
### 在使用的时候发生了什么 Bug ？

升级完新版本后，看视频拖动进度，屏幕上方显示的是时间 `15:32 / 24:49` 这种格式，之前是 `快进60秒` 这种。

个人感觉还是显示快进秒数比较好，这样可以跳过 OP 和 ED，只需要快进90秒即可，之前我都是这样操作的，改了快进显示格式后不好把握跳过 OP 和 ED 了。

如果有可能也希望支持一下跳过 OP 和 ED。

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

xiaomi pad 5 pro

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这个改动被抱怨了很多次

不出意外的话会在 1.3.4 进行回滚

**Comment by Predidit** [comment]
1.3.4 已经发布
