### ISSUE TITLE
[Bug]: 某些番必须用软件解码才能使用内置播放器（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#238]
### 在使用的时候发生了什么 Bug ？

次元城的女友成双第二季，硬件解码会导致内置播放器只有声音没有画面。

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
只有声音而没有画面时，可以正常拖动进度条吗

**Comment by YCZ01111** [comment]
可以正常拖动

**Comment by Predidit** [comment]
我大概看了一下这个流，这个流和次元城的其他资源不太一样。虽然都是 HEVC 编码，但打包方式不同，这个流使用了不太常见的 hev1 而不是 hvc1。

我查阅了 Apple 开发者文档, Apple AVPlayer 不支持这种格式。从文档来看， Apple 在支持 hvc1 六年之后仍然对 hev1 没有任何想法。

所以看上去这个问题暂时无法解决，这是一个预期中的错误。

我不建议为了这个视频而禁用硬件解码，这会导致更多的视频无法播放。

**Comment by Predidit** [comment]
软件解码时部分视频无法播放的问题已经在 1.3.5 及以后的版本解决

建议在 iOS 上禁用硬件解码

也许这应该成为一个默认选项

**Comment by YCZ01111** [comment]
> 软件解码时部分视频无法播放的问题已经在 1.3.5 及以后的版本解决
> 
> 建议在 iOS 上禁用硬件解码
> 
> 也许这应该成为一个默认选项

不是硬件解码时部分视频无法播放吗

**Comment by Predidit** [comment]
硬件解码部分视频播放不了是 iOS/macOS 独有的问题，因为 Apple AVPlayer 套件对 HEVC 的支持不完整

软件解码部分视频播放不了是全平台的，因为所使用的 ffmpeg 对不同格式的兼容性太好了, 有些视频切片伪装自己为图片来托管到公共图床中, ffmpeg 会将其视为图片而出现错误。

这一问题已经被修复了。
