### ISSUE TITLE
增加进度记录

### ISSUE THREAD

**Issue by huanyying** [Predidit/Kazumi#24]
能否支持播放的进度记录下来，
目前我在历史记录里点进之前未看完的番剧，依旧是从头开始播放
如图，之前的播放进度
![Screenshot_20240702_013524.jpg](https://github.com/Predidit/Kazumi/assets/96985629/3dcbb989-415d-4532-b48f-ace999035de2)

然后从历史记录里播放，如图
![Screenshot_20240702_013546.jpg](https://github.com/Predidit/Kazumi/assets/96985629/612547b4-a351-4d10-ad35-50b86a6f53f4)

希望可以支持进度的保存。

**Comment by Predidit** [comment]
此功能已经添加到刚刚发布的 1.1.6 版本中
