### ISSUE TITLE
[Bug]: 状态栏反色存在问题

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/Kazumi#240]
### 在使用的时候发生了什么 Bug ？

首页和播放页（aosp10的设备一直出现该问题，aosp12就第一次有该问题，后来正常了）的状态栏字体和图标反色异常，其他页面均无此问题，手头两台设备均有该问题，均录屏
m6：

https://github.com/user-attachments/assets/a87c396a-9139-4095-bfa6-d65fe7dcb420

m60p：

https://github.com/user-attachments/assets/f1aab496-82fc-4f1c-b939-8dc52d8b7e78

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

华为m6高能版 鸿蒙2
华为mate60pro 鸿蒙4.2

### 日志信息

```shell
m60p：
**2024-09-24 13:26:35.901261** 
 Resolve bangumi list failed type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null**2024-09-24 13:26:53.928236** 
 Resolve bangumi list failed type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null

m6：
**2024-09-24 12:52:37.343007**
RangeError (length): Invalid value: Valid value range is empty: 0null**2024-09-24 12:52:41.543179**
RangeError (length): Invalid value: Valid value range is empty: 0null**2024-09-24 12:52:45.325454**
RangeError (length): Invalid value: Valid value range is empty: 0null**2024-09-24 12:52:48.817823**
RangeError (length): Invalid value: Valid value range is empty: 0null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
此问题已在 1.3.4 修复
