### ISSUE TITLE
关于弹幕切换的优化

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#242]
### issue 内容

弹幕切换的那个按钮，希望可以改成优先搜索目前正在看的番剧的弹幕，其次才是输入其他番剧的名字去找其他的弹幕，我会提出这个问题主要还是因为有一些播放源，他们的集数是倒过来的。
就比如说DM84这个播放源，部分新番的集数都是倒过来的，举个例子“夜樱家的大作战”这就是倒过来的，25集变成了第1集，第1集变成了25集，因此每次要看的时候，都要先在弹幕切换输入番剧的名字然后切换成第25集的弹幕，比较麻烦，希望能改一改！

哦对了顺便，添加一个切换正序和倒序的按钮吧，应该可以稍微解决一下集数颠倒的播放源。

然后就是关于ciyuancheng，这个播放源没办法用内置的播放器来播放了，只能用网站自身来播放，这样就无法看弹幕了，也不知道是不是我的问题？希望能解决一下！谢谢！

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
弹幕切换的逻辑我需要考虑一下

关于 ciyuancheng, 看上去 ciyuancheng 那边的更改破坏了 kazumi 视频解析器的兼容性，我已经提交了相关补丁，等待 1.3.4 发布

**Comment by Predidit** [comment]
倒序问题在 1.4.0 修复
