### ISSUE TITLE
[Bug]: 取消视频外部播放后，视频比例异常

### ISSUE THREAD

**Issue by reiyutsuki** [Predidit/Kazumi#244]
### 在使用的时候发生了什么 Bug ？

取消视频外部播放后，视频比例异常且无法拖动进度条

https://github.com/user-attachments/assets/df374689-3897-4a68-a9fe-fdd04c3c955a

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

魅族20pro

### 日志信息

```shell
没有数据
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
看上去和 #226 相关，尝试按照 #226 中的问题描述进行视频快进，检查是否复现视频变形的问题

**Comment by reiyutsuki** [comment]
使用快进并不会复现此bug，不过禁用硬件解码能够解决这个问题

**Comment by Predidit** [comment]
此 bug 疑似来自 flutter 框架的视频播放器，禁用原生解码将使用 ffmpeg 而非原生视频播放器进行播放。

我需要时间来调查这个问题，由于重复，我会将这个 Issue 关闭，后续在 #226 追踪此问题
