### ISSUE TITLE
[Bug] 华为 API29 设备上硬件解码不可用

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/Kazumi#248]
### issue 内容

从某个版本开始就无法播放视频了，挂梯子也看不了，请问我该怎么办才可以正常观看？

https://github.com/user-attachments/assets/ee8460bd-e117-4a15-8b16-0df47ddea47f

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Qing-Novel** [comment]
我按照oneanime您给的建议操作了，可以看了
ps：kazumi也有状态栏反色异常的问题（提了issue）

**Comment by Predidit** [comment]
状态栏反色的补丁已经合并到 kazumi，等待下个版本发布。

你在使用哪个型号的设备，安卓版本是什么，有没有使用自定义内核。

硬件解码不可用的情况很不寻常，因为它基于 android 内嵌的多媒体套件 exoplayer 。理论上这个实现是兼容性和性能最好的。

**Comment by Qing-Novel** [comment]
> 状态栏反色的补丁已经合并到 kazumi，等待下个版本发布。
> 
> 你在使用哪个型号的设备，安卓版本是什么，有没有使用自定义内核。
> 
> 硬件解码不可用的情况很不寻常，因为它基于 android 内嵌的多媒体套件 exoplayer 。理论上这个实现是兼容性和性能最好的。

设备是华为m6高能版，aosp10，鸿蒙2。不过我手头鸿蒙4.2的手机可以播放

**Comment by Predidit** [comment]
华为 m6 高能版这台设备的 vulkan 驱动有缺陷, 这是一个被 flutter 引擎团队确认了的问题。

我不知道这台设备现在是否还有更新, 尝试更新操作系统版本。这可能会解决问题。

禁用硬件解码不是一个完美的解决方案，除了增加耗电之外，还会导致部分格式的视频无法播放。

**Comment by Qing-Novel** [comment]
> 华为 m6 高能版这台设备的 vulkan 驱动有缺陷, 这是一个被 flutter 引擎团队确认了的问题。
> 
> 我不知道这台设备现在是否还有更新, 尝试更新操作系统版本。这可能会解决问题。
> 
> 禁用硬件解码不是一个完美的解决方案，除了增加耗电之外，还会导致部分格式的视频无法播放。

原来是这样啊。。。。系统目前不更新了，所以我目前只能禁用硬件解码了。。。增加耗电还好，毕竟是平板，电池大

**Comment by Predidit** [comment]
这个问题应该关联 [flutter/engine##54879](https://github.com/flutter/engine/pull/54879)

flutter 现在会在有缺陷的华为设备上禁用有问题的GPU特性，我相信这会解决问题。

虽然这个PR已经被合并，但是还没有进入 flutter 稳定版本。

我会在下一个 flutter 稳定版本发布时在这里更新。

**Comment by virskor** [comment]
mark to follow

**Comment by Predidit** [comment]
1.4.5 已经发布

**Comment by Qing-Novel** [comment]
希望oneanime也修复下
