### ISSUE TITLE
[Feature]历史记录选集定位问题

### ISSUE THREAD

**Issue by LUFTSCH1** [Predidit/Kazumi#249]
### issue 内容

# 问题描述
观看剧集较多的动漫时，从历史记录进入后需手动滑动定位。
* 例如：观看《乱马1/2》时，每次从历史记录进入后，选集列表不能自动滑动定位到当前播放剧集，想选择当前剧集附近的剧集需要手动滑动定位。这不算bug，但算个可改进点，麻烦dalao看看QAQ
# 其它信息
* 平台：Android
* 系统版本：Android 12 (PixelExperience_Plus_dumpling-12.1-20221112-1603-OFFICIAL)
* 设备型号：ONEPLUS A5010
* Kazumi版本：1.3.3

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
在 1.4.1 中实现
