### ISSUE TITLE
请添加一个新的规则！

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#251]
### issue 内容

我确认过了目前为止的所有规则中应该是没有这一个域名的规则的 www.mutean.com 请问能否添加一个？
请在添加新规则之前先检测一下这个域名，是否能够被内置播放器所解析，以免出现和 yishijie 这个规则相同的情况。

（小小的碎碎念：规则是一个一个看过去的，这个域名应该是没添加过，希望我没有眼花吧？…………）

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这个站点的搜索功能有验证码
