### ISSUE TITLE
[Bug]: WebDav报错 同步失败 DioException [bad response]: null Error: Bad Gateway

### ISSUE THREAD

**Issue by cmhr0086** [Predidit/Kazumi#256]
### 在使用的时候发生了什么 Bug ？

使用同步的时候报网关错误

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

全端

### 日志信息

```shell
并没有显示日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这看上去是 WebDAV 服务端的问题
