### ISSUE TITLE
我认为规则更新按钮显示在规则管理页面更方便

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#258]
### issue 内容

目前更新规则需要去仓库里在所有规则中寻找待更新规则，我认为这并不合理

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by YCZ01111** [comment]
我认为可以一键更新所有正在使用的并且有更新的规则

**Comment by Predidit** [comment]
在 1.4.8 实现
