### ISSUE TITLE
时间表日历无法切换回当下季度

### ISSUE THREAD

**Issue by Kano-I** [Predidit/Kazumi#260]
### issue 内容

时间表日历切换其他季度后，无法切换回当下季度
> 例如：
> 当下季度为2024秋季，当切换成任意其他季度后，无法通过日历切换回当下2024秋季 季度。

可以通过重启应用解决

![Screenshot_2024-10-01-02-33-29-962_com predidit kazumi-edit~01](https://github.com/user-attachments/assets/354f5b06-cd4f-47a0-9874-c0c9171408ad)

![Screenshot_2024-10-01-02-33-57-142_com predidit kazumi-edit~01~01](https://github.com/user-attachments/assets/b8214178-4082-47d3-914c-926836d38035)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
此问题已在 1.3.5 版本修复
