### ISSUE TITLE
请问一下，不知道为什么一个源在老版本可以正常使用但在新版本就不可以使用

### ISSUE THREAD

**Issue by craft327** [Predidit/Kazumi#261]
### issue 内容

老版本为 1.5.1.1
这个是那个源的链接kazumi://eyJhcGkiOiIxIiwidHlwZSI6ImFuaW1lIiwibmFtZSI6InhmZG0iLCJ2ZXJzaW9uIjoiMS4wIiwibXVsaVNvdXJjZXMiOnRydWUsInVzZVdlYnZpZXciOnRydWUsInVzZU5hdGl2ZVBsYXllciI6dHJ1ZSwidXNlUG9zdCI6ZmFsc2UsInVzZXJBZ2VudCI6IiIsImJhc2VVUkwiOiJodHRwczovL2RtMS54ZmRtLnByby8iLCJzZWFyY2hVUkwiOiJodHRwczovL2RtMS54ZmRtLnByby9zZWFyY2gvd2QvQGtleXdvcmQuaHRtbCIsInNlYXJjaExpc3QiOiIvL2Rpdls0XS9kaXYvZGl2WzFdL2Rpdi8vZGl2Iiwic2VhcmNoTmFtZSI6Ii8vZGl2WzNdL2RpdlsxXS9kaXZbMV0iLCJzZWFyY2hSZXN1bHQiOiIvL2RpdlszXS9kaXZbMl0vYVsxXSIsImNoYXB0ZXJSb2FkcyI6Ii8vZGl2WzZdL2RpdlsyXS9kaXZbMl0vL2RpdiIsImNoYXB0ZXJSZXN1bHQiOiIvL2xpL2EifQ==

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
没有 1.5.1.1 这个版本号

具体是哪个版本

**Comment by craft327** [comment]
抱歉，1.1.5，6月29号的那个版本

**Comment by Predidit** [comment]
视频解析器的核心机制有过重大变动。

破坏了这个规则的兼容性，但是现在的方案在大多数情况表现更好，应该不会回滚。
