### ISSUE TITLE
[Enhancement]弹幕显示区域

### ISSUE THREAD

**Issue by SeiyaCooper** [Predidit/Kazumi#262]
### issue 内容

观看番剧时，有时弹幕太多会遮挡画面
希望能限制弹幕的显示区域，例如只在1/4屏幕显示^_^

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这功能已经有了，弹幕设置里弹幕区域和透明度都能调
