### ISSUE TITLE
[Bug]: README描述支持安卓10及以上，但是release提供的apk为最低安卓5.0，是否意味着旧版可能出现问题而不会特意为旧版debug？

### ISSUE THREAD

**Issue by jeansanghhhh** [Predidit/Kazumi#263]
### 在使用的时候发生了什么 Bug ？

说是question，其实是遇到了无法使用的问题，但是是在旧版本安卓系统上。
* 设备：小米平板4（骁龙660AIE 3G内存）
* 系统：MIUI10 9.8.29 开发版（安卓8.1）

自带的三个源都无法播放，从主页/搜索/时间表进入都是一样，在播放区域滚过一堆信息后，“解析视频资源超时，请切换到其他播放列表或视频源”
而在同一局域网下使用的一台windows10、一部安卓14都可以播放。
目前又找来了抽屉里放置许久、同样是8.1的坚果pro2s，发现同样无法播放。（我刚发现这俩设备已经连炉石都不能搓了，炉石最低28）（找来了更久没用的、刷为安卓9的nexus5，想起它处理器是32位遂放回抽屉）
所以我想知道：
* 是否会为安卓5.0-安卓9上出现的问题Debug？
* “Callback received: The number of video tags is0”和“Callback received: The number of the tags is4”分别有什么含义，是否对解决问题有帮助？
* 我还能提供什么找到问题原因的其他信息？我不期望解决但是我有点想知道原因

（提issue这会儿刚好遇上bangumi出问题了）

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

* 小米平板4（骁龙660AIE 3G内存）
  * 安卓8.1（MIUI10 9.8.29 开发版）
* 坚果pro2s（骁龙710 6G内存）
  * 安卓8.1

### 日志信息

```shell
10月2日10点22分前没有日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
Kazumi 调用了许多系统内嵌的组件来提高性能并减少自身大小

例如 Kazumi 的播放器在 Android 上依赖  Android ExoPlayer，视频解析器依赖 Android Webview

较低版本安卓系统的组件虽然调用约定保持一致，但是部分行为不一致，这会导致问题

所以 README 中提到最低安卓版本为 10 

看上去这是视频解析器发生错误，尝试更新系统内置 Android Webview 到最新版本，应该会解决问题

也许应该同样提高 release 中的 apk 的版本要求到 10

**Comment by Predidit** [comment]
也有可能是系统级证书过期导致的。

系统级证书过期会导致 Android Webview 遇到证书错误而无法访问部分站点。

一般来说这种证书是和系统绑定的，这种情况需要更新系统。不需要安卓大版本更新，系统的安全更新有时会包含证书更新。

**Comment by jeansanghhhh** [comment]
我将平板webview更新到121（比旁边那部安卓14的版本（118）更高），结果依旧。（坚果的sos不让我选择webview）

我之前也想是不是系统内置的证书之类的问题或其他跟系统更新相关的问题，因此我讲不期望解决: (

**Comment by jeansanghhhh** [comment]
感谢回复

我将平板webview更新到121（比旁边那部安卓14的版本（118）更高），结果依旧。（坚果的sos不让我选择webview）

我之前也想是不是系统内置的证书之类的问题或其他跟系统更新相关的问题，因此我讲不期望解决: (

（话说您是不是用markdown编辑器写完复制粘贴的，还是习惯？每段话都加空行）

**Comment by jeansanghhhh** [comment]
慢着慢着，可以播放了！
是我测试不够充分，正好连续碰到无法播放的源了
