### ISSUE TITLE
能否为Windows端添加键盘上下方向键控制音量的功能

### ISSUE THREAD

**Issue by BlademasterQAQ** [Predidit/Kazumi#264]
### issue 内容

https://github.com/Predidit/Kazumi/issues/131 中可以使用鼠标滚轮控制音量
感觉能用方向键快速调节音量会比较方便，比如按一下调节10%

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
在 1.4.3 完成
