### ISSUE TITLE
追番页面排列顺序

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#269]
### issue 内容

我不知道目前是按什么顺序排列的
不过我希望可以按照加入追番的时间排列，后加入的排在前面，就像入栈一样

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
本来就是入栈啊

**Comment by YCZ01111** [comment]
![IMG_0809](https://github.com/user-attachments/assets/edf25b97-930c-49a7-b3b0-a70ef496b351)
倒数第二个是我刚点的，但是却出现在这里

**Comment by Predidit** [comment]
在 1.4.7 实现
