### ISSUE TITLE
差点忘了，排期表可以再多添一个优化！

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#270]
### issue 内容

排期表中会出现日本和国产的那些番剧混合在一起显示的情况，会比较混乱。
所以希望在排期表那里添加一个筛选按钮，让排期表只显示日本的或国产的或者混合在一起出现，可以自行选择的筛选按钮。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这个功能实现不了

元数据来自 Bangumi API。他们的排期表API返回的数据没有标识番剧为日本或国产的字段。

为每个番剧单独请求一次来源地区是不现实的
