### ISSUE TITLE
[Bug]: 偶尔无法切换片源

### ISSUE THREAD

**Issue by meibelol** [Predidit/Kazumi#272]
### 在使用的时候发生了什么 Bug ？

在观看《超自然武装当哒当》《机械手臂》等动画无法切换视频源除播放列表1以外的其他播放列表，试过如爱站对多种视频源，均不行。但观看如《败犬女主太多了》却可正常切换

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

redmi note 13

### 日志信息

```shell
**2024-07-31 15:16:43.804308** 
 解析推荐列表错误 type '_Map<String, String>' is not a subtype of type 'Iterable<dynamic>' 
 null**2024-08-03 18:36:58.507171** 
 解析推荐列表错误 type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null**2024-10-02 23:14:45.423672** 
 Resolve bangumi list failed type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null**2024-10-05 01:23:59.974288** 
 RangeError (length): Invalid value: Valid value range is empty: 0 
 null**2024-10-05 23:12:15.492332** 
 RangeError (length): Invalid value: Valid value range is empty: 0 
 null**2024-10-05 23:12:17.386420** 
 RangeError (length): Invalid value: Valid value range is empty: 0 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
有些视频只有一个播放列表

**Comment by meibelol** [comment]
我所提到的均显示有两个或两个以上播放列表，但无法切换
![Screenshot_2024-10-05-23-42-38-030_com predidit kazumi](https://github.com/user-attachments/assets/eb29fa37-3222-4337-bbe6-793bf2dec5fd)

**Comment by Predidit** [comment]
我看到背景中已经显示播放列表2


看上去是切换成功了？

**Comment by meibelol** [comment]
点击屏幕中第1集无反应

**Comment by Predidit** [comment]
会转圈吗

**Comment by meibelol** [comment]
不会

**Comment by Predidit** [comment]
这个问题和视频源相关吗，只发生在爱站吗。

我没能复现这一问题，因为机械手臂似乎没有在爱站上架，另一部则在全局检索不到

**Comment by meibelol** [comment]
lmm，age等都不行，我猜全局搜索不到的原因是bangumi里超自然武装当哒当译作胆大党（）

**Comment by Predidit** [comment]
我已经找到问题在哪了，感谢你的反馈。对应补丁会包含在 1.3.6 中

**Comment by Predidit** [comment]
BUG 准确的触发条件应该是选择不同播放列表的相同选集。

和视频源无关。

**Comment by meibelol** [comment]
哦哦，明白了
