### ISSUE TITLE
[Bug]: Windows端ui问题

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#273]
### 在使用的时候发生了什么 Bug ？

如图
![image](https://github.com/user-attachments/assets/ff39e249-cb60-4f95-9ca8-5c8b6d815e27)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

Windows10

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
1：1 的屏幕比例现在也太少见了

flutter 的响应式布局不好用，这部分大概只能通过强行截断来修复了

**Comment by YCZ01111** [comment]
> 1：1 的屏幕比例现在也太少见了
> 
> flutter 的响应式布局不好用，这部分大概只能通过强行截断来修复了

  启动就这么大啊

**Comment by kiccd4g** [comment]
解析播放源的时候, 好像不能调整跟移动窗口.

**Comment by Predidit** [comment]
包含以上两个修复的 1.3.6 版本已经发布
