### ISSUE TITLE
大佬可以加上锁定画面功能吗

### ISSUE THREAD

**Issue by Siyan114514** [Predidit/Kazumi#274]
### issue 内容

就在播放器那添一把锁，点击后就可以不呼出播放器面板了，非常好功能（好像不应该叫锁定画面？）
![IMG_20241006_182121](https://github.com/user-attachments/assets/1ec5a1d9-fee2-4075-a4d3-f4766909c358)
![IMG_20241006_182023](https://github.com/user-attachments/assets/0048fd40-57c6-4dd7-b4c4-3820cd4f2df6)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
已经加上了 1.3.6 版本会包含这一功能

**Comment by Predidit** [comment]
1.3.6 已经发布
