### ISSUE TITLE
请求加入代理设置

### ISSUE THREAD

**Issue by sdgsgsdf** [Predidit/Kazumi#275]
### issue 内容

有些源似乎对网络有一定限制，而软件本身似乎也不走系统代理，我有挂系统代理，浏览器里访问时正常的，但是在软件里就是直接红了
![图片](https://github.com/user-attachments/assets/b173005f-4aaf-4c1e-8d28-6b2796263886)
然后试了下让软件通过Proxifier走代理，发现全都正常用了，可否请大佬直接加入代理设置，或者走系统代理呢？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
后续在 #228 zhuiz
