### ISSUE TITLE
这个播放列表能不能直接显示动漫源而不是列表1234

### ISSUE THREAD

**Issue by twcgzgs** [Predidit/Kazumi#278]
![Screenshot_2024-10-07-16-41-56-808_com.predidit.kazumi.jpg](https://github.com/user-attachments/assets/cb2b48cd-5289-459f-a506-8c83ae9b6974)

![Screenshot_2024-10-07-16-42-07-093_com.predidit.kazumi.jpg](https://github.com/user-attachments/assets/d7a3620f-45e7-48d1-8556-a571f36f82d0)

**Comment by Predidit** [comment]
这个播放列表对应的是当前视频源提供的播放列表，可以去age看看，同一个视频是有很多播放列表的。

**Comment by twcgzgs** [comment]
了解，那在合集旁边标明是哪个视频源，并且加上可以随时切换视频源的选项可以不
类似这样
![Screenshot_2024-10-11-22-44-52-619_me.him188.ani.jpg](https://github.com/user-attachments/assets/c7d9351e-0cc9-40ec-8e10-01c7654e1ca3)
