### ISSUE TITLE
规则改个名它就直接新建一个新了

### ISSUE THREAD

**Issue by twcgzgs** [Predidit/Kazumi#279]
AGE改成AGE动漫就两个都有了
![Screenshot_2024-10-07-16-53-10-297_com.predidit.kazumi.jpg](https://github.com/user-attachments/assets/b1550b66-28f3-46bd-9b38-991e07959c04)

**Comment by Predidit** [comment]
什么意思，可以描述仔细一些吗

**Comment by Predidit** [comment]
啊。我理解了，不过这是一个预期行为，不是bug
