### ISSUE TITLE
追番全屏后部分按钮无法点击

### ISSUE THREAD

**Issue by yanli78** [Predidit/Kazumi#28]
追番全屏之后，下面的暂停，进度条控制，弹幕开关，退出全屏无法点击，上方的按钮没有影响

**Comment by Predidit** [comment]
额，windows 还是 android呢。

怎么全屏的呢，用自带的全屏按钮还是操作系统的全屏。

为什么点击不了呢，是控件被任务栏之类的东西覆盖了，还是单纯只是点击不了。

这条 Issue 包含的信息也太少了。

**Comment by yanli78** [comment]
windows 11 ，是用自带的全屏按钮，单纯点不了，我的也是150%缩放，次元城的源全屏后下方有大块白条
![屏幕截图 2024-07-04 140219](https://github.com/Predidit/Kazumi/assets/174435874/19853e43-2c66-4a10-8759-5881053213a6)

**Comment by Predidit** [comment]
补丁已经提交到仓库，等待下个版本发布。
