### ISSUE TITLE
[Bug]: 打开软件是开屏页状态栏部分是灰色而不是跟其他部分一样的白色

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/Kazumi#280]
### 在使用的时候发生了什么 Bug ？

打开软件是开屏页状态栏部分是灰色而不是跟其他部分一样的白色
![Videoframe_20241008_102821_com huawei himovie local](https://github.com/user-attachments/assets/c7675602-7736-4992-a0e6-a9b87ffd5c5b)

https://github.com/user-attachments/assets/dea3e2ac-7a43-4c1d-9eb5-e49794854bf0

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

鸿蒙4.2（aosp12）

### 日志信息

```shell
错误日日志内无内容
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这就是正常的透明状态栏啊。

预期是什么样的。

**Comment by Predidit** [comment]
透明状态栏是符合最佳实践的做法。

可以自适应暗黑模式以及配色方案切换。

**Comment by Qing-Novel** [comment]
> 这就是正常的透明状态栏啊。
> 
> 预期是什么样的。

预期是跟下面页面颜色一样，

https://github.com/user-attachments/assets/3ccc750a-edf5-4190-9c30-f2b077eed566

**Comment by Predidit** [comment]
这是一个和 flutter 框架相关的错误 [flutter/flutter#64001](https://github.com/flutter/flutter/issues/64001)

此问题尚未得到解决, 讨论中提到的解决方案并不完美

这个问题似乎还和不同厂商的安卓系统的动画实现相关

例如在我使用的 Android14 设备上, 这个缺陷几乎无法复现

如果你找到了使用 flutter 开发的带有状态栏沉浸的应用程序没有这个缺陷，欢迎告诉我，我可以借鉴他们的实现

**Comment by Qing-Novel** [comment]
> 这是一个和 flutter 框架相关的错误 [flutter/flutter#64001](https://github.com/flutter/flutter/issues/64001)
> 
> 此问题尚未得到解决, 讨论中提到的解决方案并不完美
> 
> 这个问题似乎还和不同厂商的安卓系统的动画实现相关
> 
> 例如在我使用的 Android14 设备上, 这个缺陷几乎无法复现
> 
> 如果你找到了使用 flutter 开发的带有状态栏沉浸的应用程序没有这个缺陷，欢迎告诉我，我可以借鉴他们的实现

我录了个屏，您看看这几个应用是不是用您

https://github.com/user-attachments/assets/d7ab9913-ce42-4ff9-b970-4b70a7a72f02

说的flutter做的？surfboard、mihon、kotatsu、libchecker

**Comment by Predidit** [comment]
都不是，使用 flutter 开发的应用，第一开发语言是 Dart。

占比第一的是 Kotlin 则为原生 Android 应用。

开发语言统计可以在对应仓库的首页找到。

这个 surfboard 看上去和 FlClash 很像，你可以测试一下 FlClash 有这个问题吗，FlClash是一个很棒的完全开源的 flutter 应用，不是像 surfboard 这这样的闭源软件。

**Comment by Qing-Novel** [comment]
> 都不是，使用 flutter 开发的应用，第一开发语言是 Dart。
> 
> 占比第一的是 Kotlin 则为原生 Android 应用。
> 
> 开发语言统计可以在对应仓库的首页找到。
> 
> 这个 surfboard 看上去和 FlClash 很像，你可以测试一下 FlClash 有这个问题吗，FlClash是一个很棒的完全开源的 flutter 应用，不是像 surfboard 这这样的闭源软件。

FIClash没这个问题

Uploading SVID_20241008_114722_1.mp4…

**Comment by Predidit** [comment]
视频裂了

**Comment by Qing-Novel** [comment]
> 视频裂了

稍等下，我重发，然后作者大大，我怎么在github能搜到surfboard啊。。。（https://github.com/getsurfboard/surfboard）

https://github.com/user-attachments/assets/f3548e25-583b-4f83-b386-883a8fa178a5

**Comment by Qing-Novel** [comment]
https://github.com/getsurfboard/surfboard

**Comment by Predidit** [comment]
试试这个 https://github.com/Predidit/Kazumi/actions/runs/11228477119/artifacts/2027407846

需要注意，安装实验性构建会清除应用数据

PS: 托管在 Github 上的不一定是开源项目, 像是 BILI 和 SurfBoard 这种只在 Github 上发布构建好的二进制文件，把 Github 当成网盘使用，他们的代码仓库是空的或是只包含简要说明。他们没有公开任何代码，也没有使用开源许可证。

**Comment by Qing-Novel** [comment]
> 试试这个 https://github.com/Predidit/Kazumi/actions/runs/11228477119/artifacts/2027407846
> 
> 需要注意，安装实验性构建会清除应用数据
> 
> PS: 托管在 Github 上的不一定是开源项目, 像是 BILI 和 SurfBoard 这种只在 Github 上发布构建好的二进制文件，把 Github 当成网盘使用，他们的代码仓库是空的或是只包含简要说明。他们没有公开任何代码，也没有使用开源许可证。

原来如此

**Comment by Qing-Novel** [comment]
> 试试这个 https://github.com/Predidit/Kazumi/actions/runs/11228477119/artifacts/2027407846
> 
> 需要注意，安装实验性构建会清除应用数据
> 
> PS: 托管在 Github 上的不一定是开源项目, 像是 BILI 和 SurfBoard 这种只在 Github 上发布构建好的二进制文件，把 Github 当成网盘使用，他们的代码仓库是空的或是只包含简要说明。他们没有公开任何代码，也没有使用开源许可证。

还是有问题
![2024_10_08_122841686](https://github.com/user-attachments/assets/b999ef84-71c4-4870-8912-76d72325bbfa)
![2024_10_08_122855230](https://github.com/user-attachments/assets/0a2be9da-6277-4055-91cc-17edc9275cb6)

https://github.com/user-attachments/assets/5bf4e60c-1be9-403b-a5e3-a86caea3b6d2

**Comment by Predidit** [comment]
试试这个 https://github.com/Predidit/Kazumi/actions/runs/11228820379/artifacts/2027485623

**Comment by Qing-Novel** [comment]
> 试试这个 https://github.com/Predidit/Kazumi/actions/runs/11228820379/artifacts/2027485623

还是不行，问题跟第一个修改版一样

**Comment by Predidit** [comment]
这已经成了一个玄学问题。我需要一些时间寻找解决方法。

有新进展会在这里更新。

**Comment by Qing-Novel** [comment]
> 这已经成了一个玄学问题。我需要一些时间寻找解决方法。
> 
> 有新进展会在这里更新。
好的好的🤣辛苦作者了

**Comment by Qing-Novel** [comment]
> > 这已经成了一个玄学问题。我需要一些时间寻找解决方法。
> > 有新进展会在这里更新。

好的好的🤣辛苦作者了

**Comment by Qing-Novel** [comment]
佬可以参考下这个软件，这个软件我也有反馈这个问题，解决了（修完这个问题出现了状态栏反色异常，但之后修复了）https://github.com/qixiaoo/masiro/issues/20

**Comment by Predidit** [comment]
之所以是一个玄学问题，因为现在的代码就是这么写的

**Comment by Qing-Novel** [comment]
> 之所以是一个玄学问题，因为现在的代码就是这么写的

啊这，确实很玄学

**Comment by qixiaoo** [comment]
好像和 https://github.com/qixiaoo/masiro/issues/17 这个是同一个问题。

具体原因是进入 App 内应用的主题和开屏页应用的主题不是同一套，需要为开屏页单独设置 `LaunchTheme`。

**Comment by Qing-Novel** [comment]
> 好像和 [qixiaoo/masiro#17](https://github.com/qixiaoo/masiro/issues/17) 这个是同一个问题。
> 
> 具体原因是进入 App 内应用的主题和开屏页应用的主题不是同一套，需要为开屏页单独设置 `LaunchTheme`。

原来如此，总算不是玄学问题了（

**Comment by Predidit** [comment]
@qixiaoo 

感谢你的回复。在真白萌的对应提交中似乎没有修改 launchTheme。我还是没有找到合适的解决方案。您有兴趣提交一个PR吗。

**Comment by qixiaoo** [comment]
> @qixiaoo
> 
> 感谢你的回复。在真白萌的对应提交中似乎没有修改 launchTheme。我还是没有找到合适的解决方案。您有兴趣提交一个PR吗。

我和大佬的 SDK 版本不太一样，目前不太方便。

至于修改 `LaunchTheme` 的提交是 [这个](https://github.com/qixiaoo/masiro/commit/738247cce9f0cd973ae20279927e1c725726538d)。

**Comment by Predidit** [comment]
@Qing-Novel 

尝试这个构建 https://github.com/Predidit/Kazumi/actions/runs/12093221597/artifacts/2255953590

**Comment by Qing-Novel** [comment]
> @Qing-Novel
> 
> 尝试这个构建 https://github.com/Predidit/Kazumi/actions/runs/12093221597/artifacts/2255953590

我试试看

**Comment by Qing-Novel** [comment]
> @Qing-Novel
> 
> 尝试这个构建 https://github.com/Predidit/Kazumi/actions/runs/12093221597/artifacts/2255953590
可以了

**Comment by Qing-Novel** [comment]
签名貌似变了，我装到之前装过的设备上就提示签名有变化（
正式版签名应该不会变吧

**Comment by Predidit** [comment]
正式版的签名是一致的，每个测试版都是不同的签名

下个正式版可能要稍微等一等，现在累计的更新不足以发布一个新版本

最近比较摸，溜 Pixiv 上的 mygo 二创溜大了

**Comment by Qing-Novel** [comment]
> 正式版的签名是一致的，每个测试版都是不同的签名
> 
> 下个正式版可能要稍微等一等，现在累计的更新不足以发布一个新版本
> 
> 最近比较摸，溜 Pixiv 上的 mygo 二创溜大了

彳亍
然后这个问题oneanime也有，要不那个也更新下吧（顺带连更新提示是英文的问题一起）

**Comment by Predidit** [comment]
1.4.5 已经发布

**Comment by Qing-Novel** [comment]
希望oneanime也修复下
