### ISSUE TITLE
[Bug]: 日期排列好像不对哦

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#281]
### 在使用的时候发生了什么 Bug ？

如图
![image](https://github.com/user-attachments/assets/fc46f113-8593-4ccf-b724-fe029644d17e)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

WIndow10

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by YCZ01111** [comment]
都应该减一年

**Comment by Predidit** [comment]
这只是一个习惯问题。
