### ISSUE TITLE
引入bangumi评分

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#282]
### issue 内容

也许可以在番剧详情页引入bangumi评分？或者点击番剧编号直接跳转bangumi番剧详情页？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这也需要一次额外的API请求

目前会显示排名，也许足够了？

**Comment by YCZ01111** [comment]
也许吧
