### ISSUE TITLE
同步历史记录时出现错误

### ISSUE THREAD

**Issue by cz-97** [Predidit/Kazumi#286]
### issue 内容

我用坚果云同步历史记录，有时会出现点开一条记录后是历史记录中另一个番剧的情况

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by cz-97** [comment]
在我关闭同步功能和清除历史记录几天后，这个bug再次出现了，也许这个bug与同步无关

**Comment by Predidit** [comment]
是的， 这应该是 #287 

但是这个幽灵bug无法稳定复现，我没有办法修复它

**Comment by stevei5mc** [comment]
关于这个bug我也遇到过

https://github.com/user-attachments/assets/6c3bc41f-e050-4e93-94ab-048b77693f68

**Comment by stevei5mc** [comment]
关于这个bug我也遇到过

https://github.com/user-attachments/assets/6c3bc41f-e050-4e93-94ab-048b77693f68

**Comment by Predidit** [comment]
我想我已经知道问题在哪了，稍后会提交一个补丁

**Comment by Predidit** [comment]
1.3.7 已经修复此问题

已有的错误记录需要清空
