### ISSUE TITLE
排期表

### ISSUE THREAD

**Issue by Fo1ever** [Predidit/Kazumi#288]
### issue 内容

希望在排期表继续显示之前季度未完结正在更新的番剧

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
排期表依赖 bangumi 开放 ,这个功能实现不了

**Comment by Fo1ever** [comment]
那能在番剧封面加正在更新和已完结的标识吗

**Comment by Predidit** [comment]
不能，这也是 bangumi API 的限制
