### ISSUE TITLE
可以加个对所有视频源的一键测速功能吗

### ISSUE THREAD

**Issue by twcgzgs** [Predidit/Kazumi#289]
对所有视频源的在线解析视频测速，选择最快的以动漫源获得最好体验。类似隔壁这样的服务器测速。
![Screenshot_2024-10-11-08-08-48-827_com.bilibili.app.in.jpg](https://github.com/user-attachments/assets/6e8d6549-eb82-4d33-8804-072416917934)

![Screenshot_2024-10-11-08-09-59-081_com.bilibili.app.in.jpg](https://github.com/user-attachments/assets/719589af-e293-41e9-9135-3a4351abc331)

**Comment by Predidit** [comment]
这个功能做不了，视频源本身都没有可靠的方法检测资源有效性

**Comment by twcgzgs** [comment]
> 这个功能做不了，视频源本身都没有可靠的方法检测资源有效性
https://github.com/user-attachments/assets/451de1f8-bf4a-478b-a8ac-b2f3cc17b80f
那像隔壁ani这样这只是测试一下这个视频源能不能用，可以不
