### ISSUE TITLE
正在使用局域网，网络异常

### ISSUE THREAD

**Issue by 2665195570** [Predidit/Kazumi#29]
只有用梯子才能播放

**Comment by Predidit** [comment]
那条规则播放不了呢。


可能是对应的源站域名被屏蔽了，这样的话应该修正一下规则，有兴趣的话您也可以提交一下PR。没有的话就由我来更正。

**Comment by chenbihao** [comment]
> 哪条规则播放不了呢。
> 
> 可能是对应的源站域名被屏蔽了，这样的话应该修正一下规则，有兴趣的话您也可以提交一下PR。没有的话就由我来更正。

应该不是某条规则的问题，点击番剧时都会弹出来，我试着移除掉在最前面的规则几次，也会弹窗提升正在使用局域网，但是不影响播放
