### ISSUE TITLE
[Bug] 软件解码模式下进度定位漂移

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#290]
### issue 内容

如标题所示，想要让其中一条规则指定是否启用或关闭硬件解码，而不是关闭硬件解码是全部规则跟着一起关闭。
指定其中一条规则是否启用会方便很多，不需要一直重复的到播放设置里面启用和关闭硬件解码。
请问能否添加个这样的功能？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
1.3.5 及以后的版本可以禁用硬件解码而不妨碍任何视频的播放。

阻止部分视频在软件解码模式下播放的问题已经被解决了。

**Comment by bug333555** [comment]
> 1.3.5 及以后的版本可以禁用硬件解码而不妨碍任何视频的播放。
> 
> 阻止部分视频在软件解码模式下播放的问题已经被解决了。

主要是有一部分播放源如果不使用硬件解码的话，在用内置播放器的时候，如果网络卡顿或者说在加载没完成之前拖动进度条的话，会出现卡进度的情况。
比如说，进度条从1分钟走到3分钟这个时间点，如果这1分钟还没完全加载成功的情况下，强行拖动进度条到3分钟，这个时候加载成功后自然会显示3分钟进度条，但这个时候再返回后退进度条到2分钟的话，会跳过中间的2分钟直接跳到1分钟，这就是在关闭硬件解码的时候偶尔会碰到的bug。
通常会在网络卡顿或者在播放源还没完全加载成功后强行拖动进度条后会出现

**Comment by bug333555** [comment]
> 1.3.5 及以后的版本可以禁用硬件解码而不妨碍任何视频的播放。
> 
> 阻止部分视频在软件解码模式下播放的问题已经被解决了。

所以我就想着，能不能添加个这样的功能？
让可以被硬件解码的规则走硬件解码，让硬件解码无法解析的走软件解码。

这个功能是否可以实现？

**Comment by Predidit** [comment]
计划是在修复以上定位错误之后，修改 iOS/macOS 的硬件解码实现。

硬件解码和软件解码都将基于 ffmpeg 。而不是现在这样, 硬件解码基于 Apple AVPlayer。ffmpeg 一样可以支持硬件加速，并且不会有 AVPlayer 的格式支持问题。

**Comment by Predidit** [comment]
1.4.5 已经发布
