### ISSUE TITLE
[Bug]: 主界面（包括搜索）提示 “服务器异常”

### ISSUE THREAD

**Issue by faq0** [Predidit/Kazumi#293]
### 在使用的时候发生了什么 Bug ？

进入 Kazumi 主界面及搜索时提示 “服务器异常”。

复现步骤：

1. 打开 Kazumi “推荐” 页面。
2. 点击任意分区。
3. “服务器异常” 提示弹出。

![image](https://github.com/user-attachments/assets/b22d3c92-9441-486e-a7e6-fed691ff02ee)

* 已尝试 Windows 客户端 及 iOS 客户端 1.3.6 最新版，均能够复现。

### 您在使用哪个操作系统？

Windows 及 iOS

### 请具体提供设备、版本号等信息。

Windows 11 23H2 (22635.4300) @ Lenovo 20VE,
iOS 18.1 @ iPhone 15.

### 日志信息

```shell
**2024-10-12 18:45:15.925295** 
 Resolve bangumi list failed type 'Null' is not a subtype of type 'Iterable<dynamic>' 
 null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
Bangumi 的 API 挂了, 等他们修吧

测试地址: https://api.bgm.tv/v0/subjects/265391

**Comment by faq0** [comment]
> Bangumi 的 API 挂了, 等他们修吧

似乎修复了，谢谢回复。
