### ISSUE TITLE
安卓10&9/荣耀手机等不能正常播放

### ISSUE THREAD

**Issue by oldsento** [Predidit/Kazumi#295]
是因为窝手机老还是系统老了啊，就算是解析成功了也都不能播放，这软件真的兼容安卓10吗？安卓9就不指望，目前为止窝都没正常观看过，看来窝还是老老实实用浏览器看得了

**Comment by oldsento** [comment]
从1.3.3更新到1.3.6了都

**Comment by Predidit** [comment]
@oldsento 

此问题和 #248 重复

华为全系 android10 系统的 vulkan 驱动有缺陷，导致硬件解码不可用，在播放设置中手动禁用硬件解码即可播放
