### ISSUE TITLE
[Bug]: 清除缓存功能失效

### ISSUE THREAD

**Issue by bugjump1** [Predidit/Kazumi#297]
### 在使用的时候发生了什么 Bug ？

关于界面中清除缓存功能失效(点击“确认”无反应)，安卓及iOS最新版均有该问题，只能通过手机系统自带清除缓存功能清除。希望尽快修复
![Screenrecorder-2024-10-12-00-40-26-916](https://github.com/user-attachments/assets/e4a8217c-cabb-46c8-8550-91f0786860de)

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

Xiaomi 13   Android14
iPad Air 3   iOS 15.4

### 日志信息

```shell
点击清除后无错误日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这个功能应该没有正确工作过。

cache_network_image 库的缓存机制很复杂，正常的缓存清理手段似乎不起作用，我要想想解决方案。

**Comment by LeetaoGoooo** [comment]
> 这个功能应该没有正确工作过。
> 
> cache_network_image 库的缓存机制很复杂，正常的缓存清理手段似乎不起作用，我要想想解决方案。

我觉得有个简单的方案就是直接删除这个缓存目录

```dart
    final Directory tempDir = await getTemporaryDirectory();
    final Directory libCacheDir = Directory("${tempDir.path}/libCachedImageData");
    await libCacheDir.delete(recursive: true);
```

需要的话，我可以提个 PR

**Comment by ErBWs** [comment]
@Predidit 最新的发行版中这条的Contributor写错了

**Comment by Predidit** [comment]
已经修正
