### ISSUE TITLE
希望增强方向键控制能力

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#299]
### issue 内容

希望增加的能力如下：
1. 当播放时间小于等于10秒时，按下左方向键可以将播放时间设置为0。
2. 长按右方向键时，视频倍速播放，松开右方向键恢复正常播放速度。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
1. 是的，我们需要这个功能，现在的行为是 Bug

2. 这稍微有点复杂。因为并没有原生方案可以捕获键盘的长按事件，虽然可以通过定时器做到，但有些不优雅。

**Comment by Predidit** [comment]
快捷键播放进度置零已在 1.3.7 完成

**Comment by Predidit** [comment]
在 1.4.3 完成
