### ISSUE TITLE
“刮削”？

### ISSUE THREAD

**Issue by timelic** [Predidit/Kazumi#3]
> 基于自定义规则的番剧 _刮削_ APP，支持流媒体在线观看，支持弹幕。

这里是否有一点问题？

**Comment by Predidit** [comment]
唔，您觉得更恰当的表述是？

**Comment by timelic** [comment]
显然应该是索引或者采集等词语，刮削这个生造的翻译词实在太劣质了，第一眼甚至以为是错字。

参考 https://www.appinn.com/what-is-scraper/

**Comment by Predidit** [comment]
感谢您的提议，已经更改。
