### ISSUE TITLE
历史记录优化

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#300]
### issue 内容

1. 部分番剧同一视频源下具有多个不同番剧，希望可以在历史记录中以不同的名字进行记录。如下图
![image](https://github.com/user-attachments/assets/f651be4d-4b91-4ce8-b98f-3cc4acfdf7d6)
2. 希望可以修改历史记录界面右下角的图标，目前的图标与其实际作用不强相关，且没有二次确认，容易误操作
3. 希望可以跨设备同步追番内容

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
1. 因为架构原因做不到。
 
2. 这个图标是符合其语义的，这是 Android 图标库中为 clear 这一动作准备的图标。此图标在原生 Android 也用于清理通知栏。不过我们可以为其添加确认对话框。

3. 和 #54 重复。
