### ISSUE TITLE
关于Kazumi的视频解析原理

### ISSUE THREAD

**Issue by hualiong** [Predidit/Kazumi#302]
### issue 内容

您好，我是隔壁同类型番剧采集APP“[Miru](https://github.com/miru-project/miru-app)”的拓展插件开发者。我很好奇Kazumi是如何做到仅获取到番剧的播放页链接就能成功解析出番剧的播放直链。因为Miru的拓展需要手动解析网页并抓取直链，有时甚至涉及到js逆向，开发一个拓展的成本很高，难度不低，所以我对只用5条XPath规则就能完成一个拓展插件的开发表示惊讶和好奇。（起初我还以为只靠5条XPath规则留给开发者的可操作空间太小了，以至于效果不是很好🤣）
您能稍微跟我解释一下是如何做到的吗？🤔

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by hualiong** [comment]
哦，我好像看到了类似的议题 #117 

那这么设计是不打算考虑直接通过API的方式来获取信息和直链了吗？

**Comment by Predidit** [comment]
JS的执行环境是不安全的，其标准方法是可以被篡改的。

无论解析接口如何加密，最终还是需要XHR来请求直链，我们篡改了XHR相关函数，检查每个请求是否包含 m3u8 视频流中的关键字，符合的话即为直链。

核心实现大概就是这样的，但是因为有CORS的存在，实际上复杂一些。

具体实现在 /lib/pages/webview/webview_controller_impel.dart 下面。

**Comment by Predidit** [comment]
#117 目前在搁置。

主要是这种扩展已经有miru在做了，而且与kazumi希望尽可能方便编写规则的目标冲突。

而且额外打包 js runtime 也不是我们想要的。

**Comment by hualiong** [comment]
也有道理，这样确实会降低一些自由度，不过也确实大大降低了门槛。不过我还是好奇它是如何精确定位播放页内嵌的播放器的呢？而且播放直链也不一定会有像.m3u8这种明显的关键字特征》这又是怎么处理的呢？

**Comment by Predidit** [comment]
只检查URL的话就不用这样做了，实际上挂钩XHR标准方法是为了检查所有请求的响应内容。

m3u8 视频流必然以 #EXTM3U 开头。

**Comment by Predidit** [comment]
cloudflare 反爬处理不了。

iframe 标签精准定位不了，但是可以穷举。

**Comment by hualiong** [comment]
这样啊，虽然有些场景处理不了，但大多数影视站都是CMS模板结构差不多，这套方案设计通用性比较强，没啥大碍。不过我也没想到插件的门槛这么低，规则仓库的贡献者却没我想象中的那么多。🤔
最后还是得说，这个设计是真的不错👍

**Comment by hualiong** [comment]
hh，确实。不过Miru已经停更很久了，也不知道啥时候能更新😢，你们虽然起步比Miru晚，但星标已经比他们多了，证明还是有很多人喜欢这个项目的。祝你们越做越好👏
