### ISSUE TITLE
[Bug]: macOS端在全屏的时候按esc会直接退出软件

### ISSUE THREAD

**Issue by SkyLeech** [Predidit/Kazumi#303]
### 在使用的时候发生了什么 Bug ？

macOS端在全屏的时候按esc会直接退出软件

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

MacBook Air

### 日志信息

```shell
null
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
非全屏模式下按 Esc 会退出程序吗

**Comment by SkyLeech** [comment]
不会

**Comment by Predidit** [comment]
这应该是窗体管理插件的问题 [leanflutter/window_manager#403](https://github.com/leanflutter/window_manager/issues/403)

我没有 macOS 设备用来测试, 这个问题可能需要其他人来解决

**Comment by SkyLeech** [comment]
这个问题仍然存在，具体表现在视频加载成功后，在任意界面按esc都会退出整个程序，不管是不是全屏

**Comment by Predidit** [comment]
这个补丁已经提交到仓库，但还没发布新的版本。

预期 1.4.0 会包含此补丁

**Comment by Predidit** [comment]
1.4.0 已经发布
