### ISSUE TITLE
能否在播放页面或播放器中添加切换硬解软解的功能

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#307]
### issue 内容

能否在播放页面或播放器中添加切换硬解软解的功能，不影响全局设置，与单条历史记录绑定

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这个功能暂时没有计划，就像之前说过的那样。后续会通过ffmpeg解决iOS硬件解码的问题。这样最优雅，也不会增加复杂度。
