### ISSUE TITLE
1.3.7版本似乎有问题，但并不确定是不是bug

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#310]
### issue 内容

我更新了1.3.7之后，排期表那里似乎出现了问题，能够明显的感觉到似乎正在异常的占用运存？我的手机运行存储的容量是4g，平常的可用剩余空间大约为1.5g，用来运行kazumi是完全没问题的，至少在1.3.7版本之前。
而更新了1.3.7版本之后，进入排期表就出现了异常占用运存的情况，出现了很严重的卡顿，并且还因为过量占用运存加上运存不足强行卡退了，目前仅在排期表会出现这种情况。
请问这是什么原因导致的？以及是否是bug？
（注：我并没有启用低内存模式，毕竟在1.3.7版本之前是完全没必要的，现在或许要启用了吧？）

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
1.3.7 为了修复详情页背景闪烁而引入的新的缓存机制导致了严重的内存泄露。

我会尽快发布一个版本进行回滚。

**Comment by Predidit** [comment]
1.3.8 已经发布
