### ISSUE TITLE
[Bug]: CliCli规则解析的外部播放地址无法正常播放

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#311]
### 在使用的时候发生了什么 Bug ？

写macOS平台外部播放功能时发现的，CliCli无法正常外部播放，软件本体可以播放，复制外部播放链接到浏览器显示403 Forbidden，目前还没发现其他规则无法播放的现象

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

任何操作系统应该都无法播放
比如下面的链接
[链接](https://wakigfl.cnmdm.top/2003/03/xsjfyzs2003/23.mp4?verify=1729214798-ojK2naS2i2p2fWTbhMdt%2B%2F3itKIDCp%2FzCM2O0ohhBsM%3D)

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是预期行为，clicli有反盗链设置，需要设置 http 请求头的 referer 字段。

外部播放器没法这样做。
