### ISSUE TITLE
[Bug]: 手机开全屏的时候没有画面是白屏，但是有声音

### ISSUE THREAD

**Issue by fgh083139** [Predidit/Kazumi#312]
### 在使用的时候发生了什么 Bug ？

在看番的时候，进去是正常播放的，但是放成全屏的时候就是白屏，无法操控，只能退出，但是有声音

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

redmi k50

### 日志信息

```shell
**2024-10-18 16:55:06.736225** 
卸载播放器错误 Null check operator used on a null value
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
尝试禁用硬件解码

**Comment by stevei5mc** [comment]
关于这个bug我遇到的是仅在部分视频遇到过。

补充
硬件解码是关闭的

**Comment by Predidit** [comment]
这是全平台的，上个版本发布太着急了，有代码写错了

**Comment by Predidit** [comment]
在 1.3.9 修复
