### ISSUE TITLE
[Bug]: 1.3.8出现了个无法全屏播放的bug

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#313]
### 在使用的时候发生了什么 Bug ？

无法全屏播放，不论哪个番剧都是如此，点开全屏就是白屏，点击手机返回键后直接退出番剧详情页面。
已尝试禁用了硬件解码，但依旧是白屏。
感觉是内置播放器出现了问题？

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

安卓版本是8.1.0

### 日志信息

```shell
**2024-10-18 17:23:36.271717** 
卸载播放器错误 Null check operator used on a null value
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
我服了，看上去又要发新版了

**Comment by Predidit** [comment]
@bug333555 

给我一个例子，好像只有特定规则和视频会触发

**Comment by bug333555** [comment]
> @bug333555
> 
> 给我一个例子，好像只有特定规则和视频会触发

因为我使用的规则比较少，一般只会频繁的使用经常使用的几种规则，经过我的尝试中，常用的规则中有3个出现了播放页白屏的问题
LMM
软件解码模式下的 yishijie
xfdm

**Comment by Predidit** [comment]
@bug333555 

在 1.3.9 修复
