### ISSUE TITLE
请问可以提供英语选项吗？谢谢！

### ISSUE THREAD

**Issue by Akin-S-Dev** [Predidit/Kazumi#318]
### issue 内容

我喜欢这个应用程序！但是，如果能够提供一个英语选项，那就太好了。这将帮助更多的用户使用这个应用，特别是那些不懂中文的用户。非常感谢开发团队的努力！

我不会说中文，但我使用 ChatGPT 将英语翻译成中文，所以我希望翻译得不错。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这个应用程序中所有的番剧资料都以中文形式提供，这些资料来自外部API，没有非中文版本。

所以要在此应该程序上实现i18n本地化是非常困难的，也许你可以试试另一个类似项目 miru
