### ISSUE TITLE
（windows）窗口缩放和播放列表功能

### ISSUE THREAD

**Issue by WEICurrant** [Predidit/Kazumi#32]
### 问题

1. win1.1.6版本似乎未适配150%的缩放与布局
2. 播放列表功能不好用

### 详情
系统屏幕缩放设置在150%的情况下，
- 默认窗口大小，播放列表不可见
- 调整宽度后才可见
- 全屏模式中无法呼出播放列表

### 期望改进
希望能适配150%缩放的同时，把播放列表（选集）功能做方便一点

### Screenshots
![kazumi 2024_7_3 3_06_20](https://github.com/Predidit/Kazumi/assets/168351570/b540f6a9-815d-4a4c-bef5-d04e77d4685b)
![kazumi 2024_7_3 3_06_43](https://github.com/Predidit/Kazumi/assets/168351570/3d3d5e6b-a018-42d3-999d-0369effc1ae6)

**Comment by Predidit** [comment]
屏幕分辨率是多少呢？

**Comment by WEICurrant** [comment]
> 屏幕分辨率是多少呢？

1920×1080

**Comment by quyaoning** [comment]
+1

**Comment by Predidit** [comment]
在我找到理想的解决方法之前，这个问题需要暂时搁置。

flutter 只能操作逻辑像素(也就是经过缩放的物理像素)。并且 flutter 没有获取显示器物理分辨率或者系统当前缩放比例的方法。

这意味着我没有办法判断程序是否运行在低分辨率，且缩放比例较高的环境里。

如果为了适配低分屏幕而统一调整窗体大小，程序在现在流行的高分屏上的显示效果会非常不理想。

可能的解决方法是通过 MethodChannel 调用 win32 API 来绕过 flutter 框架获取物理分辨率与缩放比例，这个解决方案很脏并且编写的心智负担较高。

我会保持这个 Issue 为打开状态并在这里更新进展。

如果有比较好的处理方法，也欢迎在这里提出来或是直接提交PR。

**Comment by Predidit** [comment]
windows 低分辨率设备的视频在 1.2.3 版本完成。
