### ISSUE TITLE
[Bug]: macOS/iOS无法拉起外部播放界面

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#320]
### 在使用的时候发生了什么 Bug ？

Debug版本如果通过点击遮罩的方式关闭外部播放弹窗会导致无法第二次拉起。
与该PR有关#317 ，现在通过屏蔽点击遮罩关闭方法修复此bug，希望有其他修复方式

Release版本完全无法拉起：已在该PR修复 #322 

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

MacBook Pro 14‘ 2021, iPhone16 Simulator

### 日志信息

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Address already in use, errno = 48), address = 0.0.0.0, port = 1900
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2566:15)
<asynchronous suspension>
#2      DLNAManager.start (package:dlna_dart/dlna.dart:513:22)
<asynchronous suspension>
#3      RemotePlay.castVideo (package:kazumi/utils/remote.dart:25:16)
<asynchronous suspension>
```

尝试`lsof -i:1900`结果如下
```
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
kazumi  88390     me   33u  IPv4 0xc11410f84f48337c      0t0  UDP *:ssdp
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
@ErBWs 

在合并了 #317 的现在， Release版本可以正确拉起吗

**Comment by ErBWs** [comment]
很遗憾，貌似并不行，目前发现的确是由dlna导致的问题，将`final dlna = await searcher.start();`移动到“搜索”按钮的onPressed中可以正常拉起，但这时报错变成了`(OS Error: Operation not permitted, errno = 1)`

**Comment by Predidit** [comment]
也许我们这里可以用 try-catch 简单做一个 workaround。

作为这部分代码的所有者 @WhiteXero 你觉得呢？

**Comment by Predidit** [comment]
此外debug和relese的表现不一样，可能是 macOS/iOS 的权限声明问题，可能我们只声明了 client 。没有声明 server 。

**Comment by ErBWs** [comment]
的确是权限声明问题，但点击遮罩关闭的问题依然没有解决。iOS没有机器进行release测试

**Comment by WhiteXero** [comment]
> 也许我们这里可以用 try-catch 简单做一个 workaround。
> 
> 作为这部分代码的所有者 @WhiteXero 你觉得呢？

没意见

dlna在ios设备上能正常工作吗？不能的话可以先禁用掉

**Comment by Predidit** [comment]
如果权限声明可以解决第一次拉起的问题，方面提交一个PR吗

**Comment by ErBWs** [comment]
> dlna在ios设备上能正常工作吗？不能的话可以先禁用掉

我没有物理iOS设备进行dlna测试，所以我也无法确定

**Comment by ErBWs** [comment]
> 如果权限声明可以解决第一次拉起的问题，方便提交一个PR吗

好的
