### ISSUE TITLE
希望 小横条 沉浸

### ISSUE THREAD

**Issue by huanglinfeng18** [Predidit/Kazumi#324]
### issue 内容

安卓版本这个地方的小横条不沉浸，能不能弄成这样啊，作者大大
![img_4](https://github.com/user-attachments/assets/e083e15e-31e0-4d26-b66a-d2c5d5828cb8)
![Screenshot_20241019-144436_Kazumi](https://github.com/user-attachments/assets/69db6c8f-a3bf-4fab-97a3-70db53297861)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
现在的才是正确的沉浸啊

**Comment by huanglinfeng18** [comment]
![Screenshot_20241019-203831_Kazumi~2](https://github.com/user-attachments/assets/5e3fad52-729a-4c3a-a719-6bf2472b104a)
你是说这样的才算是正确的沉浸？这和我认识的不一样

**Comment by Predidit** [comment]
是的，这才是符合 material 规范的沉浸，也就是小白条和主题同色，这里是黑色，所以不明显。

小白条进入了选项卡并遮挡了一部分内容不是预期行为，是之前的一个错误。

**Comment by huanglinfeng18** [comment]
原来如此，选项卡遮挡一部分内容这个错误可不可以修复？

**Comment by ErBWs** [comment]
@huanglinfeng18 你可以试试这个构建
https://github.com/ErBWs/Kazumi/actions/runs/11424332631/artifacts/2078744768
可能修复了小白条遮挡问题

**Comment by Predidit** [comment]
我的意思是小白条融入选项卡是之前的一个错误。

我们不应该这么做，这会增加点按下部选项时误触小白条的概率。

**Comment by ErBWs** [comment]
事实上可能更多人会愿意增加误触概率而选择小白条无遮挡，毕竟iOS的小白条沉浸一直为人津津乐道

**Comment by Predidit** [comment]
突然觉得很有道理，愿意为此提交一个PR吗？

**Comment by ErBWs** [comment]
可以在题主测试安卓构建后进行PR，iOS端应该是没有问题。
