### ISSUE TITLE
[Bug]: A RenderFlex overflowed by 10.0 pixels on the right.

### ISSUE THREAD

**Issue by LeetaoGoooo** [Predidit/Kazumi#325]
### 在使用的时候发生了什么 Bug ？

本地运行代码时出现  RenderFlex overflowed  的问题

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

Iphone 16 Plus

### （选填）一些与 Bug 相关的硬件信息。

https://github.com/Predidit/Kazumi/blob/8948b3204835542bb79b9c7691fe28eeb4c58b61/lib/pages/popular/popular_page.dart#L121-L132

<img width="970" alt="image" src="https://github.com/user-attachments/assets/d20e9f94-f582-4a22-b1ba-2a685854263c">

### 日志信息

```shell
The following assertion was thrown during layout:
A RenderFlex overflowed by 10.0 pixels on the right.

The relevant error-causing widget was: 
  Row Row:file:///Users/leetao/workspace/flutter-workspace/Kazumi/lib/pages/popular/popular_page.dart:121:23
The overflowing RenderFlex has an orientation of Axis.horizontal.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是符合预期的，我没有找到更好的方法处理这个图标

**Comment by LeetaoGoooo** [comment]
> 这是符合预期的，我没有找到更好的方法处理这个图标

我在想，直接通过 

```dart
Padding(
                        padding: const EdgeInsets.all(10),
                        child: ClipOval(
                          child: Image.asset(
                            'assets/images/logo/logo_android.png',
                          ),
                        ),
                      )
```
这个组件去处理，效果是这样子的

![image](https://github.com/user-attachments/assets/a531781b-64b8-4830-b7ca-de59a66cfd84)

当然这个异常不是什么大问题

**Comment by Predidit** [comment]
这样会让图标变小, 我一直没在这里找到合适的解法

**Comment by LeetaoGoooo** [comment]
> 这样会让图标变小, 我一直没在这里找到合适的解法

我这里用的是padding all ，如果只 only left 的话，就不会导致图标缩小

<img width="416" alt="image" src="https://github.com/user-attachments/assets/ace4951c-c420-47ba-aee7-d5be549dbcda">

**Comment by Predidit** [comment]
这样就不是圆形了

**Comment by LeetaoGoooo** [comment]
> 这样就不是圆形了

哈哈 懂你意思了，我来试试有没有更好的解决方案
