### ISSUE TITLE
追番#收藏#弹幕

### ISSUE THREAD

**Issue by qiye7766** [Predidit/Kazumi#336]
看日本的番剧全是繁体，很让人体验拉胯，我下载了所有引擎，自己终于找到有汉化字体的番剧收藏，我点开番剧收藏却是第一个AEG的，那我收藏或者追番的意义何在，我要是几个番剧汉化在不同的线路我又要一个个的测试点击打开，希望收藏或者追番直接是选择好的线路，下次点开直接进到相关线路。
弹幕也有问题，看第一集弹幕有，第二集又没有，重新搜索，弹幕不可以持续连续集数播放，每看一集都要重新打开或者搜索

**Comment by Predidit** [comment]
历史记录里是选择好的。

弹幕匹配没有办法，大部分番剧的匹配应该是没有问题的，少数因为译名或是总集篇的原因需要手动匹配。
