### ISSUE TITLE
忽略webDav同步的证书错误

### ISSUE THREAD

**Issue by studylessshape** [Predidit/Kazumi#337]
### 在使用的时候发生了什么 Bug ？

配置好之后，保存配置报出了这个错误。

![IMG_20241023_233843](https://github.com/user-attachments/assets/f0548896-1941-4235-8f6b-9c1fd0738c00)

之后尝试取添加了用户 CA 凭证，还是一样的报错。

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

Redmi K50u, Android 14

### 日志信息

```shell
**2024-10-23 23:21:20.458012** 
webDav backup diretory create failed 
 
**2024-10-23 23:21:21.038910** 
同步观看记录失败 DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)) 
 
**2024-10-23 23:22:00.523692** 
webDav backup diretory create failed 
 
**2024-10-23 23:22:01.118529** 
同步观看记录失败 DioException [unknown]: null
Error: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)) 
 
**2024-10-23 23:22:05.441978** 
webDav backup diretory create failed 
 
**2024-10-23 23:32:41.440652** 
webDav backup diretory create failed
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是 android 的安全机制。

要使自定义用户CA生效，除了在系统中安装之外，还需要在应用开发者在应用程序中声明信任用户CA。

如果真的想用自签证书的话，建议安装到系统CA。

**Comment by studylessshape** [comment]
> 这是 android 的安全机制。
> 
> 要使自定义用户CA生效，除了在系统中安装之外，还需要在应用开发者在应用程序中声明信任用户CA。
> 
> 如果真的想用自签证书的话，建议安装到系统CA。

可以强制信任吗？MixPlorer 可以配置信任，另外 Joplin 的 WebDav 同步也可以忽略证书错误。

**Comment by Predidit** [comment]
原生 android 应用可以做到。但是 flutter 应用没有优雅的方式来忽略证书错误。DIO组件并不支持这样操作。

可以通过一些hack来实现，但使用hack来实现这一功能没有必要并且会降低稳定性。
