### ISSUE TITLE
Windows端功能优化

### ISSUE THREAD

**Issue by EVOKF** [Predidit/Kazumi#34]
是否可以在右上角位置加一个正常的最小化和最大化窗口的选项，每次打开后想要最小化和最大化都不太习惯
![图片1](https://github.com/Predidit/Kazumi/assets/124335005/25743877-59eb-46fb-a21a-5bf7bea62cc2)

**Comment by Predidit** [comment]
这个程序不适合最大化，很多地方没有适配，会导致布局错误。

我个人觉得最大化应该被全屏选项代替。所以暂时没有计划添加最大化按钮。

**Comment by EVOKF** [comment]
那全屏按钮也行
