### ISSUE TITLE
是不是AGE LMM 和mandao都用不了了

### ISSUE THREAD

**Issue by startx2233** [Predidit/Kazumi#342]
### issue 内容

kazumi内不能播放同时网站也无法使用
AGE中提示已迁移
LMM中提示Request:Could not find any IP that can be successfully connected. (The remote certificate was rejected by the provided RemoteCertificateValidationCallback.) (The remote certificate was rejected by the provided RemoteCertificateValidationCallback.) (yun.366day.site:443)大意：未找到可用ip
mandao中提示503 Service Unavailable.

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
我看了一下，LMM 和 mandao 现在不是都能用吗，AGE 倒是离线了，不过这些视频源本来就是这样，偶尔会不可用

**Comment by Rstoroniomi** [comment]
我用VPN用不了，我开的是南韩节点

**Comment by Predidit** [comment]
那是IP风控的问题，我们解决不了

**Comment by bug333555** [comment]
> 我用VPN用不了，我开的是南韩节点

你那是属于节点风控太高太危险，网站检测到这些高危险的ip就会主动屏蔽这些ip的，你能做的只有去更换安全的节点才能够进入网站。
你如果可以看到自己所使用的节点的dns或者ip地址的话，可以使用这个网站来检测这个节点是否是高风险节点，ping0.cc 如果看不到自己节点的ip地址的话，可以去搜索叫 ipip 的这个东西，用它来检测自己的节点ip即可，但是要注意免费的每天使用次数有限。
