### ISSUE TITLE
弹幕匹配优化

### ISSUE THREAD

**Issue by will5933** [Predidit/Kazumi#344]
### issue 内容

![图片](https://github.com/user-attachments/assets/6faa0813-4208-4eda-b9ae-665bc27d7b5c)

类似与这种番，会找不到匹配的弹幕。希望能加一个 自动用当前名称搜索列出几个比较匹配的选项 的功能，这样不用每一集都输入关键词查找一下了。感谢大佬❤️

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
和 #229 重复
