### ISSUE TITLE
莫名其妙在后台播放

### ISSUE THREAD

**Issue by Alpha-Qian** [Predidit/Kazumi#35]
应该是点进去没加载完，回到主页后从后台切到其他应用。在其他应用的时候突然就开始播发放番剧声音了。切回kazumi后只显示主页没看到播放画面只有声音，无法暂停。

**Comment by Predidit** [comment]
有比较详细的复现步骤吗，例如使用了 webview 源还是 native 源

**Comment by Predidit** [comment]
我好像找到原因了，这个问题发生在 windows 平台还是 android 平台

**Comment by Alpha-Qian** [comment]
Uploading Screenrecorder-2024-07-05-02-58-40-862.mp4…

Android，就添加了三个示例规则，那个webview和native源是什么意思？反复加载返回两三次就能复现

**Comment by Predidit** [comment]
修复补丁已经提交到仓库。

等待下个版本发布。

webview源使用webview播放视频，播放器也是从源站爬下来的网页播放器。native源使用本项目内置的播放组件播放视频，效率高一些，而且有弹幕。
