### ISSUE TITLE
[Bug]:软件解码模式下，像剧场版这样超长时长的番剧，容易出现进度条卡进度的问题

### ISSUE THREAD

**Issue by bug333555** [Predidit/Kazumi#353]
### 在使用的时候发生了什么 Bug ？

使用的规则是 yishijie 用软件解码观看类似剧场版这样超长番剧的时候，容易出现无法往后退的情况，只能往前，并且连往前都很困难。
举个例子，如果我进度条卡在2:00无法往后退，那么这时候要往前走得把进度条拉到2:15否则进度条依然卡在两分钟，并且不仅如此，伴随着卡进度出现的还有马赛克，就是播着播着突然画面全部变成马赛克，这两个几乎一同出线，只要出现卡进度过个1~2分钟或者更久必定会出现全画面变成马赛克的情况。

请看一下下面这个视频，由于限制视频大小的问题，这个视频我只录制了进度条卡进度的问题。
希望能有解决办法，要不然剧场版之类的这样超长时长的番，就无法在软件解码的模式下观看了。

https://github.com/user-attachments/assets/b363e2ed-4004-4a54-91be-d40aeaf9034c

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

安卓版本8.1.0

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是 [wang-bin/fvp#160](https://github.com/wang-bin/fvp/issues/160)

硬件解码不使用 fvp 。所以没有这个问题。

这个问题只能通过禁用高级缓存来缓解, 需要等待 fvp 修复。

**Comment by Predidit** [comment]
1.4.5 已经发布
