### ISSUE TITLE
[Bug]: macOS 硬件解码会出现帧表现不正常，如跳帧，重复帧等问题

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#358]
### 在使用的时候发生了什么 Bug ？

如题

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

macOS 15.1 Apple Silicon

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by ErBWs** [comment]
如果不单独配置硬件解码模式的字段的话，应该是直接使用 video_player 的 AVPlayer 进行解码而不是 fvp 的 VT 进行解码，所以 macOS 硬件解码也会出现 #238 的问题，关于 #353 我并没有在macOS观察到，iOS还在尝试复现

**Comment by Predidit** [comment]
> 如果不单独配置硬件解码模式的字段的话，应该是直接使用 video_player 的 AVPlayer 进行解码而不是 fvp 的 VT 进行解码，所以 macOS 硬件解码也会出现 #238 的问题，关于 #353 我并没有在macOS观察到，iOS确实会出现这个问题

这部分参考 fvp 的文档，当声明在 macOS/iOS 上使用 fvp 而声明解码器时会使用 VT。当没有声明 macOS/iOS 上使用 fvp 实现时自然是 AVPlayer

实际上从 fvp 迁移到 media_kit 是我一直想做的事情, 这将解决视频方面几乎所有的问题

**Comment by ErBWs** [comment]
看来这个问题我无能为力。我会在 macOS 上将硬件解码声明为 fvp 并使用一段时间，目前看起来 fvp 的问题出在移动端，而macOS 貌似没有问题，因为我已经在 macOS 上使用软件解码相当长一段时间了

**Comment by Predidit** [comment]
在 1.4.2 版本合入以上修复

**Comment by bug333555** [comment]
> 在 1.4.2 版本合入以上修复

@Predidit 
问一下关于我的https://github.com/Predidit/Kazumi/issues/353这个问题，修复了吗？

**Comment by Predidit** [comment]
@bug333555 

相关 Issue 还没关闭就是还没修复
