### ISSUE TITLE
[Bug]: 不能自动播放其他播放列表的下一集

### ISSUE THREAD

**Issue by Suomm** [Predidit/Kazumi#359]
### 在使用的时候发生了什么 Bug ？

- 打开番剧点击右上角切换播放列表（默认是播放列表1，切换到播放列表2）
- 播放列表2的第一集，当第一集播放完后会自动播放下一集
- 这时候播放的第二集是 **播放列表1** 中的第二集，并不是 **播放列表2** 中的第二集

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

无

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
1..4.1 已经发布
