### ISSUE TITLE
［功能请求］能否加入云同步功能？

### ISSUE THREAD

**Issue by LaolunsiG** [Predidit/Kazumi#36]
主要是为了多端同步历史记录和规则库

**Comment by Predidit** [comment]
我最近在考虑云同步的具体实现。

我希望尽可能地避免引入由我管理的服务器作为后端。

这样可以保持这个项目的独立与开放。

我在考虑使用aniList或者bangumi作为同步源，你有什么想法和建议吗。

**Comment by Mydong** [comment]
> 我最近在考虑云同步的具体实现。
> 
> 我希望尽可能地避免引入由我管理的服务器作为后端。
> 
> 这样可以保持这个项目的独立与开放。
> 
> 我在考虑使用aniList或者bangumi作为同步源，你有什么想法和建议吗。

咱就添加webdav支持就好了，这样一众支持webdav的网盘都可以用来同步，坚果云、123网盘，以及终极大杀器alist

**Comment by LaolunsiG** [comment]
同上😂

**Comment by Predidit** [comment]
听上去是个好主意，如果没有其他意见的话，我会尝试用webdav实现云同步。

**Comment by yixiaojiu** [comment]
能简单介绍一下实现方案吗？有点好奇😁

**Comment by Predidit** [comment]
> 能简单介绍一下实现方案吗？有点好奇😁

我目前的想法是用户保存自己的webdav凭据到Kazumi，历史记录储存在用户自己的储存空间中。Kazumi会在webdav下面建立一个 kazumiSync 目录储存同步用的文件。

当观看记录更新时，将 Hive 中的 `histories` 对象序列化并写入本地临时文件，然后覆写云端上的同名文件，删除本地临时文件。(全量更新)

当APP启动时，从webdav获取文件，写入本地临时文件目录，读取并反序列化。然后和本地已有的观看记录对比并更新本地记录，删除临时文件。(差分更新)

从云端同步只发生在APP启动时，APP启动不会上传历史记录到webdav，上传到webdav只发生在观看番剧导致历史记录变动的场合。

你有什么其他的想法和方案吗。

其实这里有一个小问题，公共 webdav 服务一般有rate limit。Kazumi目前的历史记录是每秒更新一次以记录精确的观看时间。每秒调用一次 webdav 是无法接受的。观看番剧时每分钟同步一次进度可能好一些，但是那样偏差又有些太大了。

**Comment by yixiaojiu** [comment]
哇，好详细。不用每秒都更新吧，在退出当前观看的番剧、当前应用进入后台和app关闭时更新，这样会有什么问题吗？

**Comment by Predidit** [comment]
> 哇，好详细。不用每秒都更新吧，在退出当前观看的番剧、当前应用进入后台和app关闭时更新，这样会有什么问题吗？

之前是考虑到安卓平台上的操作习惯，手动杀后台来退出APP是很常见的操作。

但这个操作导致的退出是无法被handle的。

为了在这种情况下也能记录进度，使用了每秒同步一次的做法。

也许保留更新每秒更新一次本地hive记录，但在你上面提到的场合提交到webdav是恰当的做法。

**Comment by Predidit** [comment]
基于WebDav的观看历史记录已经在 1.1.8 加入

**Comment by YUZU-384** [comment]
可以用网盘云同步吗，我找不到合适的webdav，例如蓝奏什么的，我可以提供蓝奏的直连获取demo

**Comment by yixiaojiu** [comment]
> 可以用网盘云同步吗，我找不到合适的webdav，例如蓝奏什么的，我可以提供蓝奏的直连获取demo

网盘不太合适吧。webdav，坚果云不能用吗？

**Comment by YUZU-384** [comment]
未成年的原因
