### ISSUE TITLE
以前的观看模式更好一些，现在太敏感了

### ISSUE THREAD

**Issue by Rstoroniomi** [Predidit/Kazumi#361]
![image](https://github.com/user-attachments/assets/8f6f3a4e-e1bb-48d8-b374-9ed997be9222)
![image](https://github.com/user-attachments/assets/dbc3ed85-95ff-4f6f-b3f0-af87445282f1)

**Comment by ErBWs** [comment]
太敏感了是指？

**Comment by Predidit** [comment]
在 1.4.2 中改进
