### ISSUE TITLE
是否可以将设置中的“历史记录”独立出来

### ISSUE THREAD

**Issue by hollywuchi** [Predidit/Kazumi#362]
### issue 内容

在日常的追番过程中，我更趋向于点击“历史记录”去继续追番，而不是点击“追番”按钮。因此我希望可以将“历史记录”单独作为一个按钮，它值得

### 提交前确认

- [x] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
在 1.4.2 修复
