### ISSUE TITLE
1.4.1为什么报毒？

### ISSUE THREAD

**Issue by ssincxv** [Predidit/Kazumi#363]
### issue 内容

![QQ20241103-153614](https://github.com/user-attachments/assets/1e402ed1-25dc-4a9a-a719-928320e26395)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这看上去是启发式引擎的误报，可以尝试误报反馈

1.4.1 之前的版本有这个问题吗

**Comment by ssincxv** [comment]
没有

**Comment by Predidit** [comment]
启发式的误报一直很迷，你可以尝试向 360 提交误报反馈，并提到该程序来自开源项目，并黏贴本项目的地址。相信他们很快会解除误报。

**Comment by Predidit** [comment]
从 1.4.6 开始，我们为 windows 可执行文件附件标准代码签名。

从 1.4.6 开始应该不再可能出现误报。
