### ISSUE TITLE
关于1.4.1平板横屏ui

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#366]
### issue 内容

如题

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by YCZ01111** [comment]
![IMG_0905](https://github.com/user-attachments/assets/797f0c22-e9f8-4abb-b7bf-c4bbb96993cb)
![IMG_0906](https://github.com/user-attachments/assets/f481ff9f-6425-4c55-a6f6-c31f12253668)
现在平板横屏时全屏和非全屏的区别只有系统栏的显示，以及非全屏状态下无法使用亮度和音量手势，还有锁定。
是否可以在全屏时也显示系统栏并且让其透明？并且同播放器ui同时唤出或隐藏？
非全屏时希望回退以前的样子，现在真的很难受

**Comment by ErBWs** [comment]
也许让平板横屏时始终保持全屏状态是个好主意，状态栏不知道什么原因。

我有时间研究一下，之前写这部分的时候没有在平板上进行过测试

**Comment by Predidit** [comment]
顺滑地实现状态栏同播放器ui同时唤出或隐藏是不现实的，最多让两者重叠在一起，然后同时唤出或隐藏，那样效果也不好

**Comment by YCZ01111** [comment]
> 也许让平板横屏时始终保持全屏状态是个好主意，状态栏不知道什么原因。
> 
> 我有时间研究一下，之前写这部分的时候没有在平板上进行过测试

重点不在这里，我认为在全屏状态时唤出选集列表是丝毫没有意义的行为，如果想要回到上一集不如添加一个上一集按钮。
这个设计使得平板在横屏非全屏状态下也和全屏时一样会使画面受到遮挡，如果想保留这个设计，那么能否让平板横屏非全屏时不要使用该设计，而是像以前一样
![IMG_0871](https://github.com/user-attachments/assets/eea6a5ab-f60b-4257-b983-466b58827206)

**Comment by YCZ01111** [comment]
并且全屏时唤出选集列表改为黑色半透明才不会显得突兀，虽然我还是觉得该设计没有使用场景

**Comment by YCZ01111** [comment]
> 顺滑地实现状态栏同播放器ui同时唤出或隐藏是不现实的，最多让两者重叠在一起，然后同时唤出或隐藏，那样效果也不好

直接在现有ui上方添加一窄行获取系统时间，电量，网络状态等如何，也就是说使其作为ui的一部分。不知道其他平台是如何实现的

**Comment by YCZ01111** [comment]
> > 顺滑地实现状态栏同播放器ui同时唤出或隐藏是不现实的，最多让两者重叠在一起，然后同时唤出或隐藏，那样效果也不好
> 
> 直接在现有ui上方添加一窄行获取系统时间，电量，网络状态，蓝牙耳机电量等如何，也就是说使其作为ui的一部分。不知道其他平台是如何实现的

**Comment by ErBWs** [comment]
我来解释一下我这样设计的原因吧

1. 原来的设计在电脑端非正常比例软件窗口时选集列表会变得特别大或者特别小，看起来很难受，pad看起来就是列表比较小的例子。为什么覆盖在视频上是因为我不认为会有人看视频时还需要把选集列表一直显示着，这样体验很差，选集结束后关闭选集列表就行

2. 全屏时能够呼出选集表单对我来说是非常重要的功能，尤其是手机端。毕竟切换集数不只有前/后切换一集，而我不想为此每次都要把手机从横屏换成竖屏，电脑端则是不想每次都要切换全屏

3. 选集的每个方格颜色是跟着主题走的，如果背景设置为黑色半透明浅色主题下会非常丑

**Comment by ErBWs** [comment]
我来解释一下我这样设计的原因吧

1. 原来的设计在电脑端非正常比例软件窗口时选集列表会变得特别大或者特别小，看起来很难受，pad看起来就是列表比较小的例子。为什么覆盖在视频上是因为我不认为会有人看视频时还需要把选集列表一直显示着，这样体验很差，选集结束后关闭选集列表就行

2. 全屏时能够呼出选集表单对我来说是非常重要的功能，尤其是手机端。毕竟切换集数不只有前/后切换一集，而我不想为此每次都要把手机从横屏换成竖屏，电脑端则是不想每次都要切换全屏

3. 选集的每个方格颜色是跟着主题走的，如果背景设置为黑色半透明浅色主题下会非常丑

**Comment by YCZ01111** [comment]
> 我来解释一下我这样设计的原因吧
> 
> 1. 原来的设计在电脑端非正常比例软件窗口时选集列表会变得特别大或者特别小，看起来很难受，pad看起来就是列表比较小的例子。为什么覆盖在视频上是因为方便固定大小，做动画，而且我不认为会有人看视频时还需要把选集列表一直显示着，这样体验很差，选集结束后关闭选集列表就行
> 2. 全屏时能够呼出选集表单对我来说是非常重要的功能，尤其是手机端。毕竟切换集数不只有前/后切换一集，而我不想为此每次都要把手机从横屏换成竖屏，电脑端则是不想每次都要切换全屏
> 3. 选集的每个方格颜色是跟着主题走的，如果背景设置为黑色半透明浅色主题下会非常丑

关于1，pad端能否保留原来非全屏的ui？如果不能，能否在横屏状态下进入播放器时自动全屏，并且通过历史记录进入时自动隐藏列表。
关于3，不可以单独为全屏状态下的选集列表单独设计颜色吗

**Comment by ErBWs** [comment]
我认为pad端横置时自动全屏是更好的方案，历史记录进入时不显示列表我认为没什么必要，完全可以在等待解析时点一下直接关闭。

颜色不一定好改，跟随主题我认为没什么不妥

**Comment by YCZ01111** [comment]
> 我认为pad端横置时自动全屏是更好的方案，历史记录进入时不显示列表我认为没什么必要，完全可以在等待解析时点一下直接关闭。
> 
> 颜色不一定好改，跟随主题我感觉没什么不妥
在全屏时选集列表就像是播放器ui的一部分，众多平台在全屏时的所有ui颜色也都是一致的，也就是黑色通明，这很符合直觉。现在的全屏状态下的选集列表与播放器ui有极强的割裂感，其应该跟随播放器ui颜色而不是主题颜色。当然，这只是我的建议，是否采纳还得看你们。

**Comment by Predidit** [comment]
现在的方案挺好的，如果要单独在平板上回滚为以前的界面，需要写很多意义不明的代码

自动全屏是一直有缺陷的功能，也许我们现在可以想想怎么解决。

之前横屏自动全屏，竖屏自动退出全屏的逻辑会导致手动切换全屏失效，或手动切换全屏后自动切换失效。

我们似乎没有很好的方法来在特定情况下阻止重力传感器向应用发送状态。

**Comment by YCZ01111** [comment]
> 现在的方案挺好的，如果要单独在平板上回滚为以前的界面，需要写很多意义不明的代码
> 
> 自动全屏是一直有缺陷的功能，也许我们现在可以想想怎么解决。
> 
> 之前横屏自动全屏，竖屏自动退出全屏的逻辑会导致手动切换全屏失效，或手动切换全屏后自动切换失效。
> 
> 我们似乎没有很好的方法来在特定情况下阻止重力传感器向应用发送状态。

也许不用考虑切换，只在进入播放器时对当前的屏幕比例进行识别。

**Comment by Rstoroniomi** [comment]
我也是觉得以前的更好

**Comment by ErBWs** [comment]
可以试一下这个构建，因为自动全屏所以选集列表任何时候都不会自己打开

https://github.com/ErBWs/Kazumi/actions/runs/11678943336/artifacts/2145091755

**Comment by YCZ01111** [comment]
> 可以试一下这个构建，因为自动全屏所以选集列表任何时候都不会自己打开。没有修改颜色，因为播放器右上角的呼出菜单的颜色也是随主题变化的
> 
> https://github.com/ErBWs/Kazumi/actions/runs/11678943336/artifacts/2145091755

还不错
顺便一提，wedm网页的证书过期了，其网页可以强行访问，但是在kazumi中无法使用

**Comment by Predidit** [comment]
此修改已在 1.4.2 发布
