### ISSUE TITLE
windows版_应用窗口缩放导致窗口全黑

### ISSUE THREAD

**Issue by XukuFuku** [Predidit/Kazumi#37]
正常打开
![1](https://github.com/Predidit/Kazumi/assets/125424302/538114fc-bcff-4082-a089-6b29b49020ad)
进行缩放/全屏播放
![2](https://github.com/Predidit/Kazumi/assets/125424302/7d281129-dd2a-4370-8ad6-e1656ae07c9f)
但是声音和关闭按钮依旧可用
尝试过重启,换皮肤,都没用

**Comment by Predidit** [comment]
系统版本和GPU型号

**Comment by XukuFuku** [comment]
Windows 11 专业版

**Comment by XukuFuku** [comment]
Windows 11 22H2
4070

**Comment by Predidit** [comment]
我怀疑是播放组件的问题。

桌面应用一般是运行在核显上。核显是什么型号。

关闭播放设置里的硬件解码功能后还会黑屏吗。

作者的另一个项目oneAnime使用了不同的播放组件，可以测试一下那个项目有类似的问题吗。

**Comment by XukuFuku** [comment]
我的CPU没有核显
关闭硬件解码后缩放: 前几次不黑, 全屏依旧黑 , 并且全屏后?(黑过之后)重启软件窗口缩放都会黑 ,重启系统似乎可以解决这个问题 
关闭硬解
![1](https://github.com/Predidit/Kazumi/assets/125424302/ca579788-e017-4911-8d50-75a0dca6d360)
问题依旧
![2](https://github.com/Predidit/Kazumi/assets/125424302/c4b4ea63-9f5e-4694-b570-b0e494a2bb0e)

我尝试在一个win10系统的虚拟机(hyperV)上运行kazumi , 结果即使不关闭硬件解码可也以全屏播放,并且可以窗口缩放
成功全屏:
![4](https://github.com/Predidit/Kazumi/assets/125424302/9edf0d70-6034-4a9f-a4b1-6cf17b436e67)
虚拟机系统:
![5](https://github.com/Predidit/Kazumi/assets/125424302/997604a9-6ecf-464d-b940-503103a15de7)
也许与系统版本有关?

**Comment by Predidit** [comment]
应该不是的，按照我的理解，这应该是GPU的兼容性问题。

虚拟机环境下的GPU和本地GPU的行为是不同的。

你的显卡驱动程序版本是？尝试更新过驱动吗。屏幕分辨率是？

**Comment by XukuFuku** [comment]
现在电脑不在身边无法查看驱动版本，稍后我会尝试更新驱动，物理机与虚拟机分辨率都为2560*1440

**Comment by XukuFuku** [comment]
原驱动版本为555.85 , 更新后版本为556.12(当前官网最新) ,问题依旧未解决

**Comment by Predidit** [comment]
我现在对这个问题感到非常困惑。

我没有 4070 显卡的台式机来测试。

最接近的是一台 4070 的笔记本电脑，但是我未能在这台设备上复现你的问题。

我现在怀疑这是一个 flutter 引擎中的问题，此前他们多次搞砸过 NVIDIA 显卡的兼容性。

我会保持此问题为打开状态，当有更多的信息时我会进行更新。

**Comment by XukuFuku** [comment]
感谢你 , 我非常喜欢这个项目 
特别是它的自定义规则功能, 它让我能够更加自由的观看自己想要浏览的站点 
我自己尝试着定义了一个规则 , 现在我想把它分享出来 (使用代理可能会无法访问

kazumi://eyJhcGkiOiIxIiwidHlwZSI6IjEiLCJuYW1lIjoiUGlnIiwidmVyc2lvbiI6IjEiLCJtdWxpU291cmNlcyI6dHJ1ZSwidXNlV2VidmlldyI6dHJ1ZSwidXNlTmF0aXZlUGxheWVyIjpmYWxzZSwidXNlckFnZW50IjoiIiwiYmFzZVVSTCI6Imh0dHBzOi8veWluZ2h1YS5lZS8iLCJzZWFyY2hVUkwiOiJodHRwczovL3lpbmdodWEuZWUvc28uaHRtbD93ZD1Aa2V5d29yZCIsInNlYXJjaExpc3QiOiIvL2RpdlszXS9kaXYvZGl2WzJdL2Rpdi9kaXYvZGl2WzFdL2Rpdi9kaXZbMl0vZGl2L3VsLy9saSIsInNlYXJjaE5hbWUiOiIvL2Rpdi9kaXYvZGl2WzJdL2RpdlsxXS9hIiwic2VhcmNoUmVzdWx0IjoiLy9kaXYvZGl2L2RpdlsyXS9kaXZbMl0vYSIsImNoYXB0ZXJSb2FkcyI6Ii8vZGl2WzNdL2RpdlsyXS9kaXYvZGl2L2RpdlsyXS9kaXYvZGl2WzFdL2RpdlsyXS8vZGl2IiwiY2hhcHRlclJlc3VsdCI6Ii8vZGl2L2Rpdi91bC9saS9hIn0=

**Comment by Predidit** [comment]
你可以在[规则仓库](https://github.com/Predidit/KazumiRules)提交PR，我们一起让这个项目变得更好。

**Comment by XukuFuku** [comment]
由于别的故障,我尝试重新安装了系统(win11 22H2)
现黑屏问题已修复
