### ISSUE TITLE
[Bug]: 全屏播放切屏回来之后黑屏？

### ISSUE THREAD

**Issue by Suomm** [Predidit/Kazumi#371]
### 在使用的时候发生了什么 Bug ？

- 全屏播放番剧；
- （**番剧正在播放的状态下**）打开平板后台；
- 切换到其他应用；
- 回到 Kazumi 应用，发现画面黑屏，等好长时间才会播放（有时会一直不播放）

![Screenshot_2024-11-06-14-11-28-182_com predidit k](https://github.com/user-attachments/assets/9cb90258-bb19-48eb-b3c3-1a8aa39d7fb0)

### 您在使用哪个操作系统？

Android

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这是 [flutter/flutter#154602](https://github.com/flutter/flutter/issues/154602)

这个问题本来已经修复，flutter 在安卓上迁移到新的 Impeller 渲染引擎后出现了回归。

我怀疑这和新的 SurfaceProducer API 相关，我会调查此问题，问题应该来自 flutter 本身。

**Comment by Predidit** [comment]
1.4.5 已经发布

仍然会黑屏，但是单击黑屏区域可以立即点亮播放器
