### ISSUE TITLE
[问题]：当番剧加载失败时，我该如何正确的重新加载？

### ISSUE THREAD

**Issue by Suomm** [Predidit/Kazumi#372]
### issue 内容

当我打开番剧观看的时候，可能由于一些原因，番剧可能会加载失败，这时候需要重新加载番剧。例如，我想观看第一集，但是他没有加载出来。我的做法是，我会点击第二集，然后再点击第一集，这样让他重新加载（试过直接点击第一集，但是好像没有重新加载的效果）。如果还是没有加载出来，继续**重复**上述操作。

如果是之前的播放 UI（图片1），我直接在右侧的播放列表点击操作即可，但是当前的  UI（图片2），每当我点击选集之后，他会自动收回去，也就是说我需要先打开播放列表，然后再选集。这样当我试图重新加载这个第一集的时候，我需要打开播放列表，选择第二集（会自动收回），然后再点开播放列表，再点击第一集，这样来进行重载。

显然对于我的做法，新播放 UI 有些不太友好，我该如何正确的重新加载？

链接：https://github.com/Predidit/Kazumi/issues/366 https://github.com/Predidit/Kazumi/issues/361 https://github.com/Predidit/Kazumi/issues/351 

图片1：之前的播放 UI

![image](https://github.com/user-attachments/assets/57ccb6fa-e0af-4c97-bf34-ff411dd9b1e3)

图片2：当前的播放 UI

![image](https://github.com/user-attachments/assets/c6f95694-788b-4285-aac3-7468cf57650a)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
在 1.4.2 中新增了重试按钮
