### ISSUE TITLE
[Bug]: 偶现弹幕播放器卡住

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#380]
### 在使用的时候发生了什么 Bug ？

偶尔出现顶部弹幕长时间不消失的情况，暂不清楚触发条件
由于当时没有其他弹幕，推测可能是弹幕卡住了，但不知道原因

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
1.4.1 吗

1.4.1 改了弹幕实现，理论上应该是 1.4.1 修复了此问题。1.4.1 之前可能有此问题才对

**Comment by YCZ01111** [comment]
> 1.4.1 吗
> 
> 1.4.1 改了弹幕实现，理论上应该是 1.4.1 修复了此问题。1.4.1 之前可能有此问题才对

嗯，昨天触发了一次，我用的是1.4.1，看起来好像是整个弹幕播放器卡住了的原因，当时也没有其他滚动弹幕，不好判断

**Comment by YCZ01111** [comment]
关闭弹幕再打开就恢复正常了

**Comment by Predidit** [comment]
在 1.4.2 中修复
