### ISSUE TITLE
[Bug]: 播放器内部错误（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#383]
### 在使用的时候发生了什么 Bug ？

ipad偶尔会卡在这个界面并显示“播放器内部错误………….”，很快就消失了所以没看全
![IMG_0913](https://github.com/user-attachments/assets/5b88a14d-0674-490d-9872-2b28f5a177fc)
刷新后即可恢复正常

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
需要详细的报错

**Comment by YCZ01111** [comment]
![IMG_0914](https://github.com/user-attachments/assets/3cb9f70f-6030-462c-a9ad-b6be64a18bc8)
最后两条都是提示播放器内部错误

**Comment by Rstoroniomi** [comment]
我這裡是yishijie播放器錯誤

**Comment by Predidit** [comment]
看保存是网络问题，播放器加载视频直链超时了

**Comment by Rstoroniomi** [comment]
yishijie播放器内部出错，日志是这样的：
![image](https://github.com/user-attachments/assets/409b17a7-3626-456f-9470-d1ab30af3dd5)
