### ISSUE TITLE
[bug]：ios长按屏幕倍速播放时屏幕比例会强制改变且无法恢复

### ISSUE THREAD

**Issue by Nice2cu711** [Predidit/Kazumi#387]
### 在使用的时候发生了什么 Bug ？

iOS长按屏幕进行倍速播放 会百分百概率将屏幕比例变为1:1 且倍速仍然是一倍速 画质严重受损

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

iPhone13pro ios18.2

### 日志信息

```shell
无法找到这类的错误信息日子
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
Kazumi 是最新版吗

**Comment by Nice2cu711** [comment]
> Kazumi是最新版吗

是的我刚刚从1.4.1更新到了1.4.2 然后这个现象好像已经消失了 但是发现在我用倍速看视频时 拖动进度条或者快进快退或者长按倍速播放取消后 我原来的倍数会被恢复从一倍速 我得重新设置倍速才会按我原来的继续播放 这个问题能改进一下吗 很早之前的版本到现在都一直是这个问题

**Comment by Predidit** [comment]
看上去和 #386 重复

**Comment by Nice2cu711** [comment]
> 看上去和 #386 重复

似乎是这样 能帮忙解决这类问题吗 还有就是能登录账号之类的就好了 电脑端和手机端不同步有点难受
