### ISSUE TITLE
请求加入软件内的缩放倍率设置选项

### ISSUE THREAD

**Issue by kamikaze211** [Predidit/Kazumi#388]
### issue 内容

我在archlinux上安装的aur版本，以及在release中下载最新的均没找到相应设置选项。
因为一些原因，我的显示器只能全局保持100%缩放，否则总会出现各种奇怪的问题。
我参考archlinux wiki的hidpi页面，尝试过qt和gtk的环境变量均未能成功缩放。
不知道kazumi该用什么环境变量或者参数来指定缩放倍率

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
flutter 在 linux 上的底层是 gtk3

gtk 环境变量会对其生效

现在的窗体出现了什么问题吗，过大以至于超出屏幕？

**Comment by kamikaze211** [comment]
> flutter 在 linux 上的底层是 gtk3
> 
> gtk 环境变量会对其生效
> 
> 现在的窗体出现了什么问题吗，过大以至于超出屏幕？

我根据archwiki： https://wiki.archlinuxcn.org/zh-hans/HiDPI#GDK_3_(GTK+_3) 进行设置
```
GDK_SCALE=4 /home/ice/APP/Kazumi_linux_1.4.2_amd64/kazumi
```
但不管我将 GDK_SCALE= 设为多少，缩放都没有任何变化

**Comment by Predidit** [comment]
在 Kazumi 内部实现自定义缩放倍率是不现实的。

因为这本应该由 flutter 引擎管理，我们没有办法从上层设定缩放倍率。可能的 workaround 是写一些平台相关的代码获取系统当前 DPI 缩放比例，并为低缩放比例的设备单独准备一套页面布局。但这一实现相当脏，并且非常麻烦。

现在的窗体出现了什么问题吗，过大以至于超出屏幕？

**Comment by kamikaze211** [comment]
> 在 Kazumi 内部实现自定义缩放倍率是不现实的。
> 
> 因为这本应该由 flutter 引擎管理，我们没有办法从上层设定缩放倍率。可能的 workaround 是写一些平台相关的代码获取系统当前 DPI 缩放比例，并为低缩放比例的设备单独准备一套页面布局。但这一实现相当脏，并且非常麻烦。
> 
> 现在的窗体出现了什么问题吗，过大以至于超出屏幕？

既然不好通过软件内部的方式来实现缩放，那我暂时通过设置全局缩放来使用，目前还好。
没有遇到奇怪的问题。
但有一些桌面环境中的其他问题，我试着从其他方面去解决下，麻烦你了。
这个issue需要继续开着以供讨论，还是关了比较好呢？
