### ISSUE TITLE
[Bug]: 暂停播放时弹幕开关不起作用

### ISSUE THREAD

**Issue by chr431** [Predidit/Kazumi#389]
### 在使用的时候发生了什么 Bug ？

如题，在暂停播放后点击播放器右下角的弹幕开关，并不会立刻生效，要恢复播放后才会生效
这个还挺影响观看体验的，有时候大段文字被弹幕挡住了，暂停之后关弹幕并不会立刻生效，要恢复再暂停才能看清

### 您在使用哪个操作系统？

Android

### 请具体提供设备、版本号等信息。

Honor 80 GT 和Matepad pro 12.2上都存在这个问题 

### 日志信息

```shell
没有相关的错误日志
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by bggRGjQaUbCoE** [comment]
`canvas_danmaku`中的`shouldRepaint`得做个判断是否显示弹幕或者弹幕列表长度

**Comment by Predidit** [comment]
在 1.4.6 修复
