### ISSUE TITLE
目前大部分规则都错误访问

### ISSUE THREAD

**Issue by HL-Light** [Predidit/Kazumi#39]
不知道是不是我网络还是服务器问题，大部分动画都显示服务器异常，我挂梯子也没用

**Comment by HL-Light** [comment]
![Screenshot_2024-07-05-19-47-57-422_com predidit kazumi](https://github.com/Predidit/Kazumi/assets/116658416/2dae5b5c-5b67-4acd-b2d0-e3e464a0f176)
如图这样，绿的但加载不出来，测试了一下今天更新列表里面只有两个能加载出来

**Comment by Predidit** [comment]
这动画的更新时间是今天。

而且热度排名是0 (也就是数据少到热度统计不出来)。

大部分视频源应该还没更新个动画。

新的季度刚开始时，这种情况是正常的。字幕组们也会先挑自己喜欢的来做。撞车的太多了才会考虑冷门动画。有些冷门动画第二周更新时能出带字幕的资源就不错了。
