### ISSUE TITLE
[Bug]: 音量显示问题（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#390]
### 在使用的时候发生了什么 Bug ？

当通过手势调节音量后，通过音量键调节音量将不会显示系统音量条。重启播放器无法解决，必须重启软件。
希望在按音量键时至少显示系统音量或播放器音量之一

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
在 1.4.6 修复
