### ISSUE TITLE
【功能建议】收藏同步功能

### ISSUE THREAD

**Issue by Z1552091115** [Predidit/Kazumi#391]
### issue 内容

因为我同时在PC和手机上使用这个软件，发现收藏的番剧不会通过WEBDAV同步。

所以希望收藏的番剧也能通过Webdav同步，这样多设备之间的使用会更方便

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
和 #54 重复
