### ISSUE TITLE
引入分集评论区，增加评论源，如bangumi/bilibili的评论

### ISSUE THREAD

**Issue by Dome-World** [Predidit/Kazumi#396]
### issue 内容

能否增加评论区，使用bangumi的源就可以，有分集评论，如果能获取到b站的评论区源就更好了

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
我在 Bangumi 的仓库提交了 private API 的使用申请，如果可以通过的话，我们可以集成 Bangumi 评论区

**Comment by ErBWs** [comment]
> 有分集评论

@Predidit 也许我们还应该为每集增加评论区？不过播放器右上角图标有点多了，也许可以将追番按钮或者 cast 按钮放进右边的 PopMenu 中

**Comment by ErBWs** [comment]
考虑到每个规则的视频数、排序方式不同等问题使用计数去匹配评论也不是很优雅，或许可以考虑在sheet中增加集数选择去匹配评论。

可惜的是 private API 貌似没有提供番剧整体的评论 API 而只提供了吐槽 API ，现在详情页面的评论看起来有些许奇怪

**Comment by Predidit** [comment]
我还没想好 sheet 怎么调整，现在的视觉效果有些糟糕。

我本来的计划是在 sheet 顶部增加一个声优相关的选项卡，可以在评论选项卡和声优选项卡之间切换，这样评论滑出视图时的割裂感不会那么强。

换成分集评论应该也可以，但是那样的话顶部选项卡是不是太多了。

**Comment by Predidit** [comment]
评论区已添加到刚发布的 1.4.3 版本

我们现在需要考虑分集评论的实现

**Comment by Dome-World** [comment]
> 评论区已添加到刚发布的 1.4.3 版本
> 
> 我们现在需要考虑分集评论的实现

吐槽箱在平板上窗体表现不佳，希望扩大一下上下显示面积 ><

**Comment by Predidit** [comment]
> > 评论区已添加到刚发布的 1.4.3 版本
> > 
> > 我们现在需要考虑分集评论的实现
> 
> 吐槽箱在平板上窗体表现不佳，希望扩大一下上下显示面积 ><

提供一下截图，我们需要知道现在的布局有什么问题

**Comment by Dome-World** [comment]
![Screenshot_20241116_154413_com.predidit.kazumi.jpg](https://github.com/user-attachments/assets/72d0f978-e4e6-4625-ae9b-7a861477b739)

@Predidit 窗体太小了，别的没啥问题

**Comment by Predidit** [comment]
在 1.4.4 完成
