### ISSUE TITLE
对软件使用方面上的建议

### ISSUE THREAD

**Issue by azxcvn** [Predidit/Kazumi#4]
开发者你好，首先感谢您开源此项目，作为一名路人我用的很开心，实现了我想把几个网站聚集到一个app内的梦想，奈何我·没有任何编程基础，更别提app开发了，不过我在参考了你的规则仓库以及自己研究了两天之后，总算是研究明白了。但是我在自定义规则以及使用的过程中，还是遇到了以下无法解决的问题
1.某些规则参数全部正确，可以搜索，可以加载出章节数，唯独视频播放不了，无论是否打开app内的内置播放器，视频都无法播放，但是在浏览器上直接访问该网站却可以正常播放，我猜可能是模拟器内核的原因，不知道开发者下一步打不打算在app内塞一个浏览器内核进去，我不太懂
2.app内的规则管理里面，可不可以新增一个长按拖动排序的功能，这样可以把自己较喜欢的规则排在最前面，或者将右下角的加号放在右上角，这样最后一个规则的编辑按纽不会被遮挡
![Screenshot_20240623_164154](https://github.com/Predidit/Kazumi/assets/90583891/b20be5ca-871c-47e9-8c29-113c501ce875)
3.一些网站启用内置播放器后就无法加载视频了，只能用网站自带的播放器，但使用网站自带的播放器的话，在手机横屏播放时就不能隐藏状态栏与底部的导航栏（我习惯使用三大金刚按钮）
![Screenshot_20240623_164330](https://github.com/Predidit/Kazumi/assets/90583891/e117ff32-14d0-40d5-8429-ab38ec0f8568)
4.是否可以考虑做一个用户自己输入关键词，然后在各个网站搜索并呈现出结果，目前软件的逻辑是先搜索关键词，比如紫罗兰，然后得到搜索结果包括紫罗兰永恒花园，用户点击这个后，再把紫罗兰永恒花园这几个字拿给网站搜索，可不可以直接实现，用户搜索紫罗兰，直接把紫罗兰这几个字拿给网站搜索，这样不仅可以搜索番剧，一些电视剧电影也可以搜索，用户只需要提前自定义好对应的影视资源网站规则即可
5.可否在章节选择的界面增加一个“倒序/正序”的功能，因为某些章节列表会把最新的一集比如“12”集放在最前面，这样按照规则导入到app内就是“第一话”，这样是不对的

最后，以上问题只是我个人希望开发者改进的，因为本人没有这方面的经验，只能寄希望于开发者了，并且只是建议，您完全可以不采纳。期待您的答复，祝您生活愉快

**Comment by Predidit** [comment]
能收到那么详实的反馈，作为开发者真的相当开心。

1. 有这个问题的是不是 AGE 或者依赖于 AGE 视频源的站点。这是无法解决的问题，原因是 AGE 奇葩的现状，AGE 大量使用了混合内容(也即HTTP视频源呈现在HTTPS页面上)，在现代的web安全策略中，这一用法是被默认禁止的，所以会出现刮削不到的问题。如果是其他的站点，欢迎给我反馈，可能是来自插件解释器的问题。

2. 可拖动的列表是个好主意，不过这个没有原生控件可以用，我要想一想怎么实现，尽量在下个版本加入。

3. 这个问题很奇怪，您确认在使用内置播放器时没有问题吗。进入全屏和退出全屏调用的函数是完全相同的。这似乎是和系统有关的问题，我这边个人使用的设备是 Pixel ，调试用的模拟器也是原生Android。都没有办法复现。能告诉我你的系统是哪个厂商的吗，对应的安卓版本是多少。可以的话，再尝试一下三大金刚键禁用时，状态栏能否正确隐藏。

4. 这会增加规则编写的负担，这样的话需要额外的规则来获取视频封面等信息。所以暂时没有计划。

5. 这确实是一个问题，我会在下个版本中尝试修复。尽量不引入正序/倒序开关，我会尝试能不能自动识别。

PS: 如果有好用的规则，也欢迎贡献到规则仓库，让这个项目变得更好

**Comment by azxcvn** [comment]
感谢回复，您的回复已收到，期待您的下个新版本。就第三点您可能理解错了，使用内置播放器是完全没有问题的，我的意思是：某些站点的视频必须禁用内置播放器，否则无法播放，可如果禁用内置播放器，站点的视频在横屏时就会出现无法隐藏状态栏和三大金刚按键的问题，但这个问题我在使用手机浏览器时没有遇到，在浏览器上直接访问站点，观看视频横屏时可以隐藏状态栏与导航栏。

最后，虽然我很久之前注册了github，但没怎么用过，我复刻了你的规则仓库，并尝试在main分支添加了两个规则，并且拉取了请求，您可能需要在您的规则仓库里查看一下拉取请求，有两条，我不太懂这样是否是正确的规则贡献方式

**Comment by Predidit** [comment]
第三点是这样的，app内部hook了站点视频播放器的全屏按钮，当全屏按钮按下时，会调用app内部自己的全屏逻辑，而不是站点播放器的实现，这个逻辑和内置播放器的逻辑是相同的。所以我怀疑是ROM的问题，您可以告知我您的系统版本吗？

这是正确的贡献方式，感谢您的贡献。不过就像我在PR里说的那样，PR可能要修改。修改PR并不需要在网页上操作，也不需要关闭或重新发起PR，修改您复刻的分支，更新会自动同步到打开的PR里。

**Comment by azxcvn** [comment]
明白了，就第三点的问题做补充说明：我发现，点击站点播放器的全屏按钮后，播放器全屏了，但是视频没有自动横过来，我是人为解除了手机的横屏锁定，然后手动把手机横过来，就会出现我一开始说的问题，按照您的方法，导航栏更改为全面屏手势以后，依旧不生效，具体表现在状态栏没隐藏，全面屏手势的白条还在。我的系统是origin os 4 安卓14，手机型号为iqoo neo9

**Comment by azxcvn** [comment]
不知道为什么，图片上传不了，我上传到图床了https://pic.imge.cc/2024/06/23/6677f737a1d31.jpg

**Comment by Predidit** [comment]
感谢您的反馈，我已经定位到问题了，hook因为某些原因没有生效，我稍后会尝试修复。

**Comment by azxcvn** [comment]
感谢，期待新版。我按您所说，将新添加的三个规则改为了拼音，避免了中文可能带来的不必要麻烦，并且在index文件内新增了三个规则的信息，您看这样是否可行，若可行，我后续再把其他站点的规则上传上来，若不可行我再修改

**Comment by Predidit** [comment]
PR已经合并，感谢您让这个项目变得更好。

如果您要发起新的PR，尽量先删除已有的fork，然后重新建立fork，不然您的新PR可能包含本次PR的内容。

如果提交的规则里有无法使用内置播放器的规则，请设置他们的 useNative 字段为 false

**Comment by Predidit** [comment]
1.1.3 版本已经发布
1. 漫岛经过确认不是规则解释器的问题，漫岛的架构比较特殊，看上去是为了防止自身资源被引用设计的，暂时没有解决方法。

2. 可拖动列表的实现推迟，因为存在程序重启后保留插件顺序的问题，相关模块可能需要重构。 

3. 全屏问题应该完美修复了，是否可用可以给我反馈。

4. 暂无计划

5. 缺乏测试用例

**Comment by azxcvn** [comment]
感谢开发者的更新，仅测试，全屏功能已经可用，这对我来说非常有用，再次表示感谢！
![Screenshot_20240624_212902.jpg](https://github.com/Predidit/Kazumi/assets/90583891/d7949b73-9dfe-4141-81ac-c99bd8203e2f)


关于规则拖动排序的功能可以慢慢做，软件目前已经很好用了！

后续若有其他建议我会及时反馈，要是发现了其他好用的动漫网站也会制作成规则

（不过有一说一，我感觉市面上主流的动漫网站现在规则仓库内已经都有了，其他网站要么是另一个网站的套壳，要么加载速度极慢，且资源不稳定，大量失效，要，要么像age那样采样https与http混着用，导致导入了规则也无法播放，更有像漫岛TV这样的，我怎么也想不到它还留了防止自己资源被爬取这一手）

（目前考虑的是转向去寻找影视网站，不再局限于仅看番剧的网站，如可可影视，网飞猫，茶杯狐这类综合影视网站）

最后是有关增加排序倒序的功能，我在找网站的过程中确实没有发现实际的例子，所以这个功能可以放一放，大部分网站也不会做这样反人类的设计，我提出这个想法也是之前在github上发现类似的软件有这个功能（忘记是哪个app了，不是knk就是纯纯看番）所以就提了一下

最后再次感谢更新，期待软件越来越好的那一天！

**Comment by Predidit** [comment]
感谢你的反馈。

看上去这个 Issue 里涉及的所有问题已经解决了。我会关闭这个 Issue ，如果有其他问题，欢迎打开新的 Issue 进行交流。

**Comment by Predidit** [comment]
对了，Kazumi 主仓库的 /assets/plugins 目录存放着示例规则，也即软件第一次启动时加载的默认规则，他们应该是优秀的规则，不包含广告，加载速度快。

您上次提交的规则都很棒，特别是MT，所以我把他加入了默认规则，替换掉了ant。

我还没来得及仔细检查所有的规则，如果你觉得已有规则中有符合无广告，加载速度快的条件的，可以向主仓库提交相关的PR，成为主仓库的贡献者。

默认规则应该维持三条，现在相对较差的应该是kimani。
