### ISSUE TITLE
深色模式下搜索框内文字为黑色

### ISSUE THREAD

**Issue by albertexye** [Predidit/Kazumi#40]
Windows 11 1.1.7 版本在深色模式下搜索框内文字为黑色，影响使用。
![screenshot](https://github.com/Predidit/Kazumi/assets/111392956/21840d20-9c69-42dd-8cdb-442c9244aacb)

**Comment by Predidit** [comment]
1.1.6 版本有这个问题吗

**Comment by albertexye** [comment]
不知道，只测试了1.1.7

**Comment by xsfx0313** [comment]
同有这个bug，1.14 1.15 1.16都有

**Comment by XiaoMian2** [comment]
Android1.1.7也有该问题

**Comment by Predidit** [comment]
这个问题已经由 @yixiaojiu 提交的PR修复。

等待下个版本发布。

**Comment by Predidit** [comment]
1.1.8 已经发布。
