### ISSUE TITLE
与官方app视频质量存在差异

### ISSUE THREAD

**Issue by huanglinfeng18** [Predidit/Kazumi#401]
### issue 内容

我注意到在同一个动漫片源网站上，官方应用播放的清晰度似乎比Kazumi播放的要高，尽管两者的分辨率都设置为1080P。这让我感到困惑，难道是我的错觉？

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这可能不是你的错觉，但没有什么解决方法。

Kazumi 的视频都是从网页获取的。一些站点的app和网页使用不同的播放源，app源的质量可能好一点。

**Comment by Predidit** [comment]
我们在 1.5.2 引入了基于 Anime4K 的实时超分辨率

启用相关设置后查看是否有改善
