### ISSUE TITLE
[Bug]: 无法调整进度的bug（ios软解）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#404]
### 在使用的时候发生了什么 Bug ？

https://file.uhsea.com/2411/ca0f634c893e9c8446c343361e24a9b4U8.mp4
无论是通过手势还是直接拖动进度条，播放的内容都不受影响，进度条的时间为拖动后的时间且停止，不知道如何触发的。

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
这本质上是 #353 的另一种表现，触发条件是在缓存未完成时连续调整进度，越长的视频越容易触发

在 #353 追踪
