### ISSUE TITLE
想要x86_64架构的安卓安装包

### ISSUE THREAD

**Issue by madoka773** [Predidit/Kazumi#41]
既然没linux版我可以用安卓版凑合一下

**Comment by Predidit** [comment]
android x86_64 的用户实在是太少了，且在虚拟机环境下的播放器有奇怪的尚未解决的问题，所以目前没有提供相关二进制文件的计划。

不过你可以尝试自行编译，如果觉得在本地安装相关环境过于麻烦的话，也可以fork本项目，微调本项目的github workflows文件，从而使用github actions实现云构建。

**Comment by madoka773** [comment]
> android x86_64 的用户实在是太少了，且在虚拟机环境下的播放器有奇怪的尚未解决的问题，所以目前没有提供相关二进制文件的计划。
> 
> 不过你可以尝试自行编译，如果觉得在本地安装相关环境过于麻烦的话，也可以fork本项目，微调本项目的github workflows文件，从而使用github actions实现云构建。

那我觉得应该在release里apk的文件名加上对应的架构名，以免有人误会下错了。

**Comment by Predidit** [comment]
Linux 测试版现在有了

在 #15 您可以测试一下吗。

**Comment by madoka773** [comment]
等我把fedora装回来，据说 media_kits 在linux非常的灵车

**Comment by Predidit** [comment]
新版本不是 media_kit 了

确实很灵车

**Comment by madoka773** [comment]
> Linux 测试版现在有了
> 
> 在 #15 您可以测试一下吗。

#94
