### ISSUE TITLE
clicli解析資源失敗😔

### ISSUE THREAD

**Issue by Rstoroniomi** [Predidit/Kazumi#410]
### 在使用的时候发生了什么 Bug ？

![Uploading IMG_0528.png…]()

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

iOS17.1.2

### （选填）一些与 Bug 相关的硬件信息。

之前可以解析，現在不行❌

### 日志信息

```shell
**2024-11-19 14:44:43.356275** 
RangeError (length): Invalid value: Valid value range is empty: 0
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Rstoroniomi** [comment]
![image](https://github.com/user-attachments/assets/768ccb55-fc87-4218-add5-ebb17ca731ef)

**Comment by Predidit** [comment]
@KotaHv 

我在 Android 上的测试没有问题，有兴趣测试一下 iOS 吗，也许是 #360 的回归

**Comment by KotaHv** [comment]
> @KotaHv
> 
> 我在 Android 上的测试没有问题，有兴趣测试一下 iOS 吗，也许是 #360 的回归

iOS测试正常，我想应该是视频源的问题。

**Comment by Rstoroniomi** [comment]
现在我把插件卸了重安就好了❤️
