### ISSUE TITLE
再次提出追番列表排序问题（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#421]
### issue 内容

我不知道其他端如何，但在ipad上，追番列表既不是按番剧上映时间排序，也不是按追番时间排序，也不是按首字母排序，可以说是绝对无序。我认为根据添加追番的时间排序会比较好，即新添加的追番显示在最前面。又或者可以自由切换排序方式。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by bggRGjQaUbCoE** [comment]
`Once we have a box, it's time to fill it with sweet data! At its core, a box is just a key-value store. String keys are mapped to arbitrary primitive values. You can think of a box as a persisted Map<String, dynamic>.`

可以加个时间戳数据段

**Comment by Predidit** [comment]
在 1.4.7 实现

**Comment by bggRGjQaUbCoE** [comment]
> 在 1.4.7 实现

`collect_page` 没排序？

**Comment by Predidit** [comment]
@bggRGjQaUbCoE 

没有，因为分类之后列表长度短了很多，似乎没有排序的必要 ~~主要是懒~~

有兴趣可以PR
