### ISSUE TITLE
[Bug]: ios硬件解码偶发长按倍速固定的情况

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#426]
### 在使用的时候发生了什么 Bug ？

长按倍速后松手，小概率出现固定二倍速的情况，每次触发没有关联

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
1.4.5 已经发布
