### ISSUE TITLE
[Bug]: windows视频资源解析中

### ISSUE THREAD

**Issue by zaw510** [Predidit/Kazumi#427]
### 在使用的时候发生了什么 Bug ？

RT，无限循环此故障，无法正常使用。已尝试操作如下：
1、网络排查，同网络下安卓能用，windows无法使用。手机共享热点给电脑也无法使用。上了VPN后仍然无法使用。
2、首页推荐及时间表图片加载完全正常。
3、尝试切换多个源及播放列表，均无效果。
4、用浏览器去对应的网站上面直接播放完全正常（如age)。
希望大佬能抽空看看，不胜感激！
![微信截图_20241130101216](https://github.com/user-attachments/assets/7318c943-36c5-40a3-ad27-dcaaf5b6318f)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

Windows 10 22H2

### 日志信息

```shell
因为只是不能播放，没有出错，所以无错误信息
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
参考 #175

**Comment by zaw510** [comment]
> 参考 #175

确实，安装了webview2后正常使用了，感谢解惑！
