### ISSUE TITLE
电脑端总时长显示错误

### ISSUE THREAD

**Issue by xfljy** [Predidit/Kazumi#43]
![IMG_20240706_180549.jpg](https://github.com/Predidit/Kazumi/assets/134601450/8596b45a-d60c-484b-b912-fc710783cd67)

**Comment by Predidit** [comment]
这看上去是m3u8视频流清单文件中的错误。

简单说这是一个来自视频源的问题，导致视频时长计算错误的不是Kazumi而是视频源本身。

对于这种问题，我只能建议你更换其他视频源观看。
