### ISSUE TITLE
安卓版本收藏夹在手机里的哪个位置？

### ISSUE THREAD

**Issue by fred-cwj** [Predidit/Kazumi#430]
### issue 内容

换手机的时候想把收藏夹一起复制过去，但没找到位置，请大佬帮忙指点一二~

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
现在 Android 的应用目录不 root 的话是访问不了的。手机自带的一键换机可以迁移。
