### ISSUE TITLE
关于加载缓慢、播放卡顿的咨询

### ISSUE THREAD

**Issue by YOBOSO** [Predidit/Kazumi#431]
### issue 内容

有没有好的解决卡顿问题的方法；部分规则解析失败。希望能得到大家的建议。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by bug333555** [comment]
加载缓慢播放卡顿，大部分跟规则本身的网址有关，牵连到很多东西，其中主要来自于地区运营商的限制，比如说福建这个地区，这个地区的墙非常高，大部分国内能进的网址福建都进不去，因此福建这个地区极其依赖 vpn 否则 github 都进不了的

以及还有一点，你能进得去网址不代表你能播放网址中的播放源。

说完了原因，说说解决办法，目前来说没有好解决办法，唯一的解决办法是开个质量好的速度快的 vpn 而且还必须要安全，风控值不高的节点，否则节点ip会被网址屏蔽也进不去网址。

如果你想知道自己地区的墙高不高，测一测 Kazumi 里面的规则有多少是跳绿色有多少是跳红色的，随便点个番剧进去就行，如果少量跳红色说明墙不高，因为少量跳红色大概率是网址本身有问题进不去了，如果大量跳红色说明墙很高，这时候就跟规则无关了是地区运营商的限制，这时候就必须要重度依赖 vpn 

Kazumi 里面规则绝大部分国内都是能直连的，只是像福建这样墙非常高的地区，根本就连不上去而已
总结，最好的解决办法：质量好的，安全的，速度快的，稳定的vpn可解决一切。 别来找我哦，我也缺这种vpn

**Comment by YOBOSO** [comment]
感谢解答
