### ISSUE TITLE
播放列表操作位置不统一

### ISSUE THREAD

**Issue by snhun** [Predidit/Kazumi#432]
### issue 内容

加载中的播放列表在右上角
![1](https://github.com/user-attachments/assets/687351a3-e928-4939-abfe-5a5b128ce2a1)
播放中的播放列表在右下角
![2](https://github.com/user-attachments/assets/b95b1d0b-d889-42ee-a3bf-72e56b91b4f9)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
这是预期行为
