### ISSUE TITLE
[Bug]: 关于硬解和软解（ios）

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#433]
### 在使用的时候发生了什么 Bug ？

首先，硬解的缓存过少，在看剧场版等比较长的单集时，倍速很容易卡顿。此时低内存模式正处于关闭状态。
而软解若不开启低内存模式，在看长集时很容易爆内存导致闪退。
所以有两个问题，一是硬解缓存过少是否为bug，二是能否自由设定缓存的大小或时长。

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
硬解基于 Apple AVPlayer 。没有调整视频缓存策略的接口，也就是我们无法控制硬解要缓存多少视频。硬解模式下的低内存开关是无效的，也符合预期。

软件基于 fvp 插件，但是这个插件播放 hls 流时的重连策略有问题，单次网络波动会导致视频无法继续缓存，所以尽可能多的缓存视频以避免可能的中断。

#429 会解决这些问题，但是 #429 很庞大，我不知道什么时候才能完成。

**Comment by Predidit** [comment]
1.4.5 已经发布
