### ISSUE TITLE
希望可以修复一下安卓端播放时状态栏在左侧显示的问题。
如图，安卓端全屏播放情况下在左侧状态栏位置会显示一块主题色。

### ISSUE THREAD

**Issue by Gasolcloudteam** [Predidit/Kazumi#44]
![S40707-14344720_com.predidit.kazumi.png](https://github.com/Predidit/Kazumi/assets/77867479/976fa2a9-f975-47e7-a33d-ac10071626b6)

**Comment by Predidit** [comment]
我这边复现不了这个bug。

这是Native源还是Webview源。手机的ROM是？

**Comment by Gasolcloudteam** [comment]
> 我这边复现不了这个bug。
> 
> 这是Native源还是Webview源。手机的ROM是？

源？我这是用软件自带规则获取的，不太清楚。
手机是魅族的Flyme11内测系统
![S40708-03100471_com.android.settings.png](https://github.com/Predidit/Kazumi/assets/77867479/edfc7e71-55a1-48ec-89f5-88180d411acf)

**Comment by Predidit** [comment]
我对这个问题感到很困惑，因为我没有魅族的设备，无法复现这个问题。

看上去这个问题和 ROM 相关。

我怀疑这是flyme内测版本中的一个Bug，也许你可以向魅族官方报告这个Bug。内容可以是使用flutter开发的应用，状态栏沉浸不生效。

**Comment by Predidit** [comment]
这个问题被报告可以在 iOS 上复现，所以我在1.2.3版本提交了一个相关补丁。

检查问题是否继续存在。
