### ISSUE TITLE
[Bug]: 不知道爲啥點不開連接了 

### ISSUE THREAD

**Issue by Marcus0910** [Predidit/Kazumi#446]
### 在使用的时候发生了什么 Bug ？

![image](https://github.com/user-attachments/assets/669f208b-6cef-4cc9-b6d4-807170b49d3a)

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

windows 11

### 日志信息

```shell
沒有
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
试试其他规则
