### ISSUE TITLE
bug?: windows 下跳 '网络连接超时，请检查网络设置'

### ISSUE THREAD

**Issue by FairyOwO** [Predidit/Kazumi#45]
windows下 打开软件即跳出 `'网络连接超时，请检查网络设置'`
搜索框 搜索的时候也跳出 `'网络连接超时，请检查网络设置'`
设置-其他设置-github镜像 打不打开都会跳这个 (开关网络代理也一样)
使用手机流量的热点成功加载
疑似是不走系统代理 在代码中 `lib/request/request.dart` 下注释掉 `setProxy()` 相关内容, 可能与这个有关
是否可以由用户在 ui 自行添加 `proxy` 相关设置

**Comment by Predidit** [comment]
和这些没有关系。

 `setProxy()` 从来没有被调用过。

这个方法本来是用来让 Kazumi 走系统代理的，一般的桌面应用并不会走系统代理。

Github镜像的实现和系统代理无关，他的实现在 `lib/request/interceptor.dart` 下面。

就像自述文件里提到的那样，番剧的元数据都来自 Bangumi 开放API。他们在使用Cloudflare的CDN。可能你的宽带到Cloudflare的质量不是很好。

我不是很想添加系统代理支持，因为这会导致额外的麻烦，视频源经常拒绝来自数据中心IP的请求，他们对国内IP的策略则是相当宽松，配置代理在大部分情况下会起反作用。

**Comment by FairyOwO** [comment]
感谢回复
