### ISSUE TITLE
[Bug]: 手势进度调节循环

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#456]
### 在使用的时候发生了什么 Bug ？

https://file.uhsea.com/2412/2247161b0b1f0fffbc407327d7c138f3Y7.mp4
往左拉过头会跳到后面

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
无
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
在 1.4.6 修复
