### ISSUE TITLE
[Bug]: 在链接lnfiniCloud的webdav同步时报错

### ISSUE THREAD

**Issue by utbili** [Predidit/Kazumi#458]
### 在使用的时候发生了什么 Bug ？

在链接lnfiniCloud的webdav同步时报错，可能是安全证书报错，不清楚是网盘原因，还是软件的原因

### 您在使用哪个操作系统？

Windows

### 请具体提供设备、版本号等信息。

win1022H2
内部版本号：19045.5198

### 日志信息

```shell
**2024-12-08 13:15:36.063233** 
webDav backup directory create failed 
 
测试失败 DioException [unknown]: null
Error: HandshakeException: Handshake error in client: (OS Error:
CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
```

### 提交前确认

- [X] 我正在使用最新版本的 Kazumi
- [X] issue 列表中，没有我发现的这个 Bug

**Comment by Predidit** [comment]
证书错误我们是解决不了的，这一般是网盘的问题

**Comment by utbili** [comment]
行吧，辛苦了

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Flameorange67** [comment]
挂载在本地一次就可以正常同步了
