### ISSUE TITLE
bug?点开exe直接白屏无反应，怎么回事

### ISSUE THREAD

**Issue by Loplayer** [Predidit/Kazumi#46]

**Comment by Predidit** [comment]
可能是重复打开了Kazumi。重复打开会导致本地储存初始化失败，程序无法继续运行下去。这个地方缺乏报错和提示，可能以后会加上。

如果不是重复打开导致的话，我需要更多地信息，包括硬件，操作系统版本之类的东西。

**Comment by Loplayer** [comment]
重新下载再打开也还是白屏，cpui7-10875H win10
