### ISSUE TITLE
PC端的弹幕字体可以更改吗？

### ISSUE THREAD

**Issue by Kumikov0** [Predidit/Kazumi#464]
### issue 内容

pc的弹幕字体圆圆的，看着不是很清爽，想问问能不能更换字体。
![PC端弹幕字体](https://github.com/user-attachments/assets/74615c25-9af9-4e62-8d0c-343bebdcd0b6)
![手机端弹幕字体](https://github.com/user-attachments/assets/9f87a0e5-401a-43a0-af3b-14fbec7bf626)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
Kazumi 没有内嵌字体，使用的是系统默认字体

**Comment by Predidit** [comment]
在几乎所有场合下，系统默认字体在 windows 上都是黑体

我不知道为什么会变成这样，可能是使用了奇怪的方法安装外部字体导致的

**Comment by Kumikov0** [comment]
嗯好的，谢谢
