### ISSUE TITLE
[Bug]: 锁屏后再打开播放器出现错误提示

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#467]
### 在使用的时候发生了什么 Bug ？

![IMG_0966](https://github.com/user-attachments/assets/0baa9cd8-eab2-40d8-ba42-7f8d4ca54916)
出现上述提示，但没有其他异常

### 您在使用哪个操作系统？

macOS / iOS

### 请具体提供设备、版本号等信息。

ipad8

### 日志信息

```shell
**2024-12-12 12:24:53.863344** 
Player intent error: tcp: ffurl_read returned 0xffffffc7 https://fsi9dub4h8.senhewenhua.com:11451/cache/5q+U5a6H5a6Z5pu06L+c55qE5Zyw5pa5LTAyLm1wNA==.mp4?verify=1733976436-lpj3VYMz%2BLTkxjXtjm%2BtRcjiVouIg1Rf3%2Fyp05EIuQk%3D 
 
**2024-12-12 12:25:27.413831** 
Player intent error: tcp: ffurl_read returned 0xffffffc7 https://fsi9dub4h8.senhewenhua.com:11451/cache/5q+U5a6H5a6Z5pu06L+c55qE5Zyw5pa5LTAyLm1wNA==.mp4?verify=1733976436-lpj3VYMz%2BLTkxjXtjm%2BtRcjiVouIg1Rf3%2Fyp05EIuQk%3D
```

### 提交前确认

- [X] issue 列表中，没有我发现的这个 Bug
- [X] 我正在使用最新版本的 Kazumi

**Comment by Predidit** [comment]
看上去是连接中断了，尝试重连的提示

其他规则有这一问题吗

**Comment by YCZ01111** [comment]
> 看上去是连接中断了，尝试重连的提示
> 
> 其他规则有这一问题吗

测试了三个，其中girlgirl和cyc有这个错误，wedm没有

**Comment by Predidit** [comment]
libmpv 将其视为错误，没有太好的办法在上层解决

**Comment by Predidit** [comment]
是的，因为最新版本才换成 libmpv 

在 iOS 上的主要好处是可以在启用硬件解码的情况下播放所有视频，并且不会出现之前的进度冻结现象。

**Comment by YCZ01111** [comment]
那么接下来要处理的问题应该就和#462 一样了，现关闭此问题
