### ISSUE TITLE
适配 flutter 3.27

### ISSUE THREAD

**Issue by Predidit** [Predidit/Kazumi#472]
### issue 内容

看上去 flutter 团队搞砸了一些事情

flutter 3.27.0 相较于上一个稳定版本 3.24.5 (我们的位置) 出现了明显的性能衰减

从 flutter 仓库的 Issue 中可以看到，新版本还在一些设备上出现了渲染错误

我们应该跳过 3.27.0 并希望可以在 3.27.1 进行迁移

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by WhiteXero** [comment]
先回退咯

**Comment by Predidit** [comment]
已经适配 3.27.1
