### ISSUE TITLE
关于新的追番功能的图标颜色

### ISSUE THREAD

**Issue by ErBWs** [Predidit/Kazumi#478]
### issue 内容

一个小问题，新的追番功能的图标看着好白，和整体色调比有点突兀的感觉
<img width="188" alt="image" src="https://github.com/user-attachments/assets/4367072f-d53a-45a1-bf51-3b0a103b3608" />

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
我在亮色模式下调试的，没有注意到暗色模式的配色问题

这是一个自定义的按钮，位置在 /bean/widget/collect_button.dart

你有兴趣调整一下吗

**Comment by Predidit** [comment]
我尝试修复了一下，补丁已经提交了，不过还是有一点色差

主要问题是这是一个 Icon , Icon 的默认行为本来就是这样的，和 IconButton 的配色方案是不同的，应该可以再微调一下实现完全的一致。

**Comment by Predidit** [comment]
突然发现这里还有一个严重的 bug，当追番状态改变时，导致部分番剧被从当前选项卡移除时，后续的其他番剧的状态会出现混乱

头疼

**Comment by bggRGjQaUbCoE** [comment]
> 突然发现这里还有一个严重的 bug，当追番状态改变时，导致部分番剧被从当前选项卡移除时，后续的其他番剧的状态会出现混乱
> 
> 头疼

可以重写 `didUpdateWidget`

**Comment by Predidit** [comment]
应该修好了

**Comment by ErBWs** [comment]
> 我尝试修复了一下，补丁已经提交了，不过还是有一点色差
> 
> 主要问题是这是一个 Icon , Icon 的默认行为本来就是这样的，和 IconButton 的配色方案是不同的，应该可以再微调一下实现完全的一致。

@Predidit 准确颜色应该是 onSecondaryContainer

**Comment by Predidit** [comment]
确实是这样，感谢你的提醒

因为只有一行代码，我已经把这个修改提交到仓库

看上去这个 Issue 已经完成了？

**Comment by ErBWs** [comment]
的确
