### ISSUE TITLE
获取以前季度番剧时只能获取20个

### ISSUE THREAD

**Issue by xxfttkx** [Predidit/Kazumi#479]
### issue 内容

`lib/request/bangumi.dart`中
```
final res = await Request().post(Api.bangumiRankSearch,
          data: params,
          options: Options(
              headers: bangumiHTTPHeader, contentType: 'application/json'));
      final jsonData = res.data;
      final jsonList = jsonData['data'];
      for (dynamic jsonItem in jsonList) {
        if (jsonItem is Map<String, dynamic>) {
          bangumiList.add(BangumiItem.fromJson(jsonItem));
        }
      }
```
时间表中，点击2024夏或2024春等季度时jsonList中词条只有20个，会导致冷门番遗失。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by xxfttkx** [comment]
> 这听上去是 bangumi API 分页参数的问题，也许我们可以使用更大的分页参数
> 
> 此外我们一直会忽略冷门到未出排名的条目，也就是rank为0，以避免混入一些冷门到几乎没有资源的ova/副音轨

意思是只要改变params里的参数吗，白天我想尝试进行修复。感谢告知rank的作用！

**Comment by xxfttkx** [comment]
`static const String bangumiRankSearch = 'https://api.bgm.tv/v0/search/subjects?limit=100';`api中分页参数是100但只能获取到20个，试了别的数，20以下都能正常获取，20个以上只返回20个。另外不清楚返回的20个是怎么排的序，比如《败犬女主太多了！》是2024夏的番，我以为排名应该挺前的，但获取不到。

**Comment by Predidit** [comment]
应该是 Bangumi API 的行为发生了变化

这部分代码在我编写是是可以正确运行的

我大概看了一下 Bangumi 现在的 Public API 和 Private API 文档，看上去没有其他适合这一场景的API

我们可以在 params 中添加 "sort": "rank", 来使其按照排名排列以防止丢失热门番剧

或者我们可能需要重构这部分代码，进行多次网络请求

你觉得哪种方案合适一些，有兴趣提交PR吗

**Comment by xxfttkx** [comment]
使用"sort": "rank"解决了丢失热门番剧的问题。

看了[api文档](https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/searchSubjects)，该api是实验性 API，挺担心做了没必要的事，但我还是想尝试进行重构，想多获取些番剧数据。

**Comment by Predidit** [comment]
有兴趣的话可以尝试提交一个PR进行重构，

不过因为这个API本身已经很慢了。我们可能需要在控制器层处理分页，确保每次网络请求完成后的结果可以及时反映在屏幕上。

**Comment by xxfttkx** [comment]
好，我试着写写，到时候还请麻烦指出我写的不好的地方
