### ISSUE TITLE
弹幕搜索建议

### ISSUE THREAD

**Issue by liueggy** [Predidit/Kazumi#484]
### issue 内容

希望手动搜索弹幕时，可以自动填充番剧名

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
为什么有这个需求呢

自动匹配使用的就是番剧标题，有误的话应该自己键入其他译名

**Comment by AoEiuV020** [comment]
赞同， 
一方面， 不知道是网络问题还是啥的，有时候弹幕会加载失败，退出重新进来就能加载，
如果有自动填充番名的话就可以当成手动刷新弹幕了，
一方面，可能是翻译有多种， 或者有符号的影响， 有些番自动搜索就是找不到弹幕，但是搜索标题部分内容就能找到， 
比如“辉夜大小姐想让我告白：初吻不会结束”就搜不到弹幕， 如果有自动填充， 可以删除多余的后缀，保留“辉夜大小姐想让我告白”，就能搜到“辉夜大小姐想让我告白-初吻不会结束-"选这个可以正常加载弹幕，
另外这番在历史记录里又是”辉夜大小姐想让我告白-让人迷糊-“
