### ISSUE TITLE
【新功能】希望可以出一个可以自由选择安装位置的安装包

### ISSUE THREAD

**Issue by bilibili-CLY** [Predidit/Kazumi#485]
### issue 内容

目前windows的.msix格式安装包默认安装到c盘且无法选择，希望能够找到方法让我们自由选择安装路径

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
msix的安装位置是和 windows store 中的软件安装位置一致的，可以在windows设置中的储存器相关选项卡方便地更改。

如果已经安装了，也可以通过windows设置中的应用相关选项卡进行移动，这也是 windows store 应用才有的快速迁移体验。

我们不会维护第三种windows包，msix的体验已经很完美，而且更多的安装包格式会让很多事情变得麻烦起来。
