### ISSUE TITLE
您好，我是软件图标的作者

### ISSUE THREAD

**Issue by yquan1919180** [Predidit/Kazumi#49]
希望能添加图片来源
🍃 | Yuquanaaa #pixiv https://www.pixiv.net/artworks/116666979

**Comment by Predidit** [comment]
非常非常抱歉，未经授权使用了您的作品。

感谢您的宽容，我可以获得在此开源项目中使用 https://www.pixiv.net/artworks/116666979 授权吗。

关于具体的形式，您希望在 README 里添加还是在 APP 的关于页面中单开一栏呢，您希望对应的标识链接到您的哪个地址呢。

如果您方便的话，也可以直接开启一个包含修改的PR。如果不是很方便的话，我可以带您完成。

**Comment by Predidit** [comment]
项目自述文件的修改已经完成。您现在就可以查看。

对APP本体的修改也已经提交，但是这部分修改可能要到下个版本发布才能体现出来。

APP内的效果大概是这样的，您看可以吗。

![screenshoot_4243245](https://github.com/Predidit/Kazumi/assets/34627277/2d8b4a9a-5ba9-4431-a922-0f0f773fdb0e)

点按会链接到您的 Pixiv 主页。

**Comment by yquan1919180** [comment]
可以！辛苦啦

Predidit ***@***.***> 于 2024年7月11日周四 21:02写道：
