### ISSUE TITLE
设置选项卡改进

### ISSUE THREAD

**Issue by Predidit** [Predidit/Kazumi#494]
目前我们的设置选项卡在移动设备上很漂亮, 但是在桌面设备上看上去非常空旷。

我们也许可以在移动设备上保持现状，并为桌面设备实现类似 [settings_ui](https://pub.dev/packages/settings_ui) 中的效果。

也就是为设置选项添加卡片包裹，并添加图标。

这部分和其他模块的耦合度很低，欢迎有兴趣的参与者进行这项工作。

在本 Issue 下留言以防止其他参与者进行重复的工作。

**Comment by ErBWs** [comment]
桌面端如果可以分栏显示并且限制 card 最大宽度会比较好看，类似 telegram 这样。但 router 还是最大的问题

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/7b749d7d-eb75-4c20-b7ef-eb41d3b0b2ad" />

**Comment by Predidit** [comment]
上面提到的包，在 pub.dev 上有效果图

大概就是类似的思路

我们可以先不考虑路由的问题，可能限制宽度，居中，卡片包裹，添加图标就已经足够了

**Comment by ErBWs** [comment]
我做了点尝试。话说为什么不直接使用 settings_ui

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/801d5f16-c8ae-4bff-b5c7-021a0f678517" />

**Comment by Predidit** [comment]
因为这个包已经过时了，很久没有更新过了，似乎已经无法在最新版本的 flutter 上运行。

可能为选项添加副标题会让其没那么拥挤，视觉效果会好一点

移动端可以维持现状？

**Comment by ErBWs** [comment]
如果足够好看我觉得可以一并修改移动端的显示，文件结构会比较简单。不过现在的卡片太丑了

考虑可复用性感觉可以直接自己写个包了，还从来没写过库（

**Comment by Predidit** [comment]
你可以试试先在这里进行原型设计，可以大概看看效果。

效果不错的话简单封装一下，封装良好的组件打包成库是很方便的，发布也很方便，有 Google 账号就可以了。

我也觉得 Material Icon 很丑，Material Icon 需要配比较大的字体和宽一些的间隙。如果字体比较小又挤成一团就完全看不了了。

**Comment by ErBWs** [comment]
现在看着还行，感觉再改改间距就可以了

<img width="592" alt="image" src="https://github.com/user-attachments/assets/ada18d9d-85fd-47d2-bf39-2a8c10104a29" />
<img width="398" alt="image" src="https://github.com/user-attachments/assets/1daa5aa1-62b6-48ea-baf5-95b77c7aa2a2" />

```dart
child: Scaffold(
  appBar: const SysAppBar(title: Text('我的')),
  body: SettingsList(
    sections: [
      SettingsSection(
        title: Text('Common'),
        tiles: <SettingsTile>[
          SettingsTile.navigation(
            onPressed: (_) {
              Modular.to.pushNamed('/settings/history');
            },
            leading: Icon(Icons.history),
            title: Text('历史记录'),
          ),
          SettingsTile.switchTile(
            onToggle: (value) async {
              val = value ?? !val;
              await setting.put(SettingBoxKey.playResume, val);
              setState(() {});
            },
            initialValue: val,
            title: Text('自动跳转'),
            description: Text('自动跳转至上次播放位置'),
          ),
        ],
      ),
    ],
  ),
```

**Comment by Predidit** [comment]
看上去很棒

**Comment by Predidit** [comment]
此问题最终由 @ErBWs 在 #537 完成
