### ISSUE TITLE
安卓平板适配

### ISSUE THREAD

**Issue by weijianxian** [Predidit/Kazumi#5]
![Screenshot_2024-06-25-20-27-52-286_com predidit kazumi](https://github.com/Predidit/Kazumi/assets/33548986/f5505510-d1e5-431c-a088-bb2a04b7e2f7)
横屏下ui似乎和手机是一模一样的，希望能改一下

或许可以参考一下https://github.com/wgh136/PicaComic

**Comment by Predidit** [comment]
安卓平板的适配我尽量在下个版本中完成，目前的目标是和 windows 版本一致。

话说这个程序应该在平板上也是竖屏的才对，看上去系统忽略了程序设置的偏好，这是哪个ROM呢。

**Comment by Predidit** [comment]
适配安卓平板的补丁已经提交到了仓库。

在发布新版本之前，我希望您可以测试一下在您的设备上，这个补丁是否生效，因为安卓平台差异巨大，我不知道补丁是否适合所有情况。

包含补丁的构建为
 
[tablet.zip](https://github.com/user-attachments/files/15985195/tablet.zip)

Issue 页面不能直接上传apk，解压这个 .zip 文件可以得到apk

**Comment by weijianxian** [comment]
![Screenshot_2024-06-26-18-06-03-250_com predidit kazumi](https://github.com/Predidit/Kazumi/assets/33548986/f909d00f-ab3b-4566-b1a5-b832d403c596)
可以了
![Screenshot_2024-06-26-18-06-26-777_com android settings](https://github.com/Predidit/Kazumi/assets/33548986/b29a4ca7-25ca-43a2-b09d-a48c281ba7ca)

**Comment by Predidit** [comment]
1.1.4 版本已经发布，包含安卓平板适配。
