### ISSUE TITLE
安卓版本搜索无结果

### ISSUE THREAD

**Issue by Sabuee** [Predidit/Kazumi#50]
搜索影片时会显示重试或者一直加载。如果是重试的情况，点击重试会显示首页的推荐动漫，这时随便在首页点一个推荐动漫后，会显示刚刚搜索的动漫结果
![Screenshot_20240711_232926](https://github.com/Predidit/Kazumi/assets/144978218/e46fcfb1-c18f-47e3-9858-6945843ece5b)
。
![Uploading Screenshot_20240711_232937.jpg…]()

**Comment by Predidit** [comment]
感谢您的报告，点击重试出现推荐影片，以及搜索结果与影片不符都是bug。后续会修复。

不过搜索 死神 这一关键字得不到结果并不是Kauzmi的bug。

搜索功能使用了bangumi开放API。我很奇怪为什么这一关键字的搜索结果为空。

当我取得进展时会在这个Issue里更新。

**Comment by Sbuee** [comment]
> 感谢您的报告，点击重试出现推荐影片，以及搜索结果与影片不符都是bug。后续会修复。
> 
> 不过搜索 死神 这一关键字得不到结果并不是Kazumi的bug。
> 
> 搜索功能使用了bangumi开放API。我很奇怪为什么这一关键字的搜索结果为空。
> 
> 当我取得进展时会在这个Issue里更新。


不光只有搜索 死神 会得不到结果，今晚尝试了很多次，不管搜索什么内容都是这样的问题。感谢开发者这么晚回复

**Comment by idmixx** [comment]
Windows 版本也一样。

**Comment by Predidit** [comment]
Bangumi的搜索API发生了变动，导致搜索失败。

我已经将补丁提交到了仓库，正在打包包含此补丁的 1.1.9 版本。

**Comment by Predidit** [comment]
1.1.9 版本已经发布，检查是否还有问题

**Comment by Sabuee** [comment]
> 1.1.9 版本已经发布，检查是否还有问题

已无问题
