### ISSUE TITLE
规则更新相关优化

### ISSUE THREAD

**Issue by xxfttkx** [Predidit/Kazumi#507]
### issue 内容

目前当有规则可以更新时，无法在“规则管理”页面中完成更新，需手动进入“规则仓库”中进行更新。

是否可以为”规则管理“页面中需要更新的规则设置更新按钮，以简化用户操作。

另外，有无必要在”规则管理“页面表明，当前规则是来自规则仓库或是用户手动编辑的；可否在”规则管理“中增加一个”更新全部”按钮，对现有所有能够更新的规则进行更新。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
听上去很棒

有兴趣进行 PR 吗

**Comment by xxfttkx** [comment]
ok，我稍后提交pr

**Comment by Predidit** [comment]
我建议在规则管理中为需要更新的规则标注 tag

然后在 DropButton 中添加更新按钮

**Comment by xxfttkx** [comment]
感谢建议

**Comment by Predidit** [comment]
在 1.4.8 完成
