### ISSUE TITLE
当季新番或未完结番能否显示集数

### ISSUE THREAD

**Issue by YCZ01111** [Predidit/Kazumi#510]
### issue 内容

时间表或追番页面又或是历史记录中的新番和未完结番能否显示当前最新集数

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
不能，因为 bangumi API 没有方便的方法批量拿更新进度

**Comment by ErBWs** [comment]
其实可以做，做在番剧详情页里，不过需要增加一个 episode info 请求。

在 BangumiItem 里面加一个 List 用来存每集的上映时间，然后进详情页的时候就把 List 和 当前日期做一次判断来显示已完结或者连载中

如果可以，还可以在详情页找个地方增加一个小的更新按钮，可以全量更新一次 BangumiItem

之前做 modify info page PR 的时候想的

**Comment by Predidit** [comment]
这样的判断并不精准，番剧由于排期冲突停播一周是很常见的事情

而且批量更新对API的压力很大

**Comment by YCZ01111** [comment]
https://github.com/open-ani/ani
该项目也用的bangumiAPI，不知道他们是如何实现的

**Comment by ErBWs** [comment]
> 这样的判断并不精准，番剧由于排期冲突停播一周是很常见的事情
> 
> 而且批量更新对API的压力很大

增加一个手动更新按钮，或者直接每次进入详情页都更新一次

在每个番剧详情页里点开再请求一次，应该还好

**Comment by Predidit** [comment]
与其显示不精准的更新进度，我觉得不如不显示。

各个番剧源的更新进度也是有差异的。

**Comment by ErBWs** [comment]
> https://github.com/open-ani/ani 该项目也用的bangumiAPI，不知道他们是如何实现的

就是用的 episode info api，不过他们做了些很复杂的判断。他们的文件逻辑好绕，跳来跳去才能看懂
