### ISSUE TITLE
电脑版希望能增加放大软件界面到全屏的按键和缩小按键，就跟windows的窗口那样

### ISSUE THREAD

**Issue by Qing-Novel** [Predidit/Kazumi#516]
### issue 内容

电脑版希望能增加放大软件界面到全屏的按键和缩小按键，就跟windows的窗口那样

https://github.com/user-attachments/assets/ae5aed5f-0600-4c7e-ae22-422ec6c9e12d

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by ErBWs** [comment]
和 #253 重复了。看来是共通的，我想给 macOS 加控制按钮，也有人想要  Windows 的按钮（

**Comment by Qing-Novel** [comment]
> 和 #253 重复了。看来是共通的，我想给 macOS 加控制按钮，也有人想要 Windows 的按钮（

反正都是这几个功能就是了（）

**Comment by Predidit** [comment]
在 #253 追踪
