### ISSUE TITLE
首页全屏功能键缺失？

### ISSUE THREAD

**Issue by liueggy** [Predidit/Kazumi#531]
### issue 内容

Windows 用 msix 安装，主页右上并没有全屏键，还是说就是如此设计的
![17354536024002397971597468730360](https://github.com/user-attachments/assets/629a4fe1-7883-4491-a63d-058c5db8b078)

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
就是如此设计的
