### ISSUE TITLE
LinearProgressIndicator的显示问题

### ISSUE THREAD

**Issue by xxfttkx** [Predidit/Kazumi#538]
### issue 内容

LinearProgressIndicator只在顶部刷新时显示
![image](https://github.com/user-attachments/assets/b2a71ed7-c5f5-4041-9ffb-575b19c32f63)
往下拉刷新番剧时并不显示，就是这样的设计吗，需要修改吗

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
是这样设计的，这样还稍微麻烦一些

**Comment by xxfttkx** [comment]
行，那我close了
