### ISSUE TITLE
在安装过新版本Kazumi的电脑上无法回退使用旧版本Kazumi，这是原设计还是Bug？（.msix文件安装）

### ISSUE THREAD

**Issue by dai-din** [Predidit/Kazumi#542]
### issue 内容

在安装过新版本Kazumi的电脑上无法回退使用旧版本Kazumi，这是原设计还是Bug？
（使用v1.4.8、v1.4.7、v1.4.6进行测试，通过.msix文件安装）

打开旧版Kazumi会提示“存储初始化错误：检测到另一个Kazumi实例已在运行，请勿重复启动该程序。（0x02）”，即使只有一个Kazumi在运行。
尝试卸载新版本后再安装旧版本、重启电脑后问题依旧存在。

### 提交前确认

- [X] issue 列表中，没有我的新功能需求 / 问题

**Comment by Predidit** [comment]
新版本的储存结构和老版本不一样了

新版本向下兼容之前的储存结构，并转换为新的结构

老版本不能识别新储存结构

如果一定要回退老版本，需要清除新版本产生的所有用户数据，位置应该在 %AppData%/com.example/kazumi

**Comment by dai-din** [comment]
谢谢解答
