### ISSUE TITLE
可否添加搜索电视剧

### ISSUE THREAD

**Issue by LnYo-Cly** [Predidit/Kazumi#55]
好像只能搜索到动漫，想看电视剧没办法了。

我写了一个电视剧网站的规则：kazumi://eyJhcGkiOiIxIiwidHlwZSI6IjEiLCJuYW1lIjoiaWppdWppIiwidmVyc2lvbiI6IjEuMCIsIm11bGlTb3VyY2VzIjp0cnVlLCJ1c2VXZWJ2aWV3Ijp0cnVlLCJ1c2VOYXRpdmVQbGF5ZXIiOnRydWUsInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDEwLjA7IFdpbjY0OyB4NjQpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMjYuMC4wLjAgU2FmYXJpLzUzNy4zNiBFZGcvMTI2LjAuMC4wIiwiYmFzZVVSTCI6Imh0dHBzOi8vdi5panVqaXR2LmNjLyIsInNlYXJjaFVSTCI6Imh0dHBzOi8vdi5panVqaXR2LmNjL3NlYXJjaC8tLS0tLS0tLS0tLS0tLmh0bWw/d2Q9QGtleXdvcmQiLCJzZWFyY2hMaXN0IjoiLy9kaXZbMl0vZGl2L2RpdlsyXS9kaXZbMl0vZGl2L3VsL2xpIiwic2VhcmNoTmFtZSI6Ii8vZGl2L2gzL2EiLCJzZWFyY2hSZXN1bHQiOiIvL2Rpdi9oMy9hIiwiY2hhcHRlclJvYWRzIjoiLy9kaXZbMl0vZGl2L2RpdlsyXS9kaXZbM10vZGl2WzJdL2Rpdi9kaXYvdWwiLCJjaGFwdGVyUmVzdWx0IjoiLy9saS9hIn0=

既然规则里面有searchurl，那么搜索的时候是不是可以直接改成从每一个规则进行search，然后把结果放到搜索页显示

![image](https://github.com/user-attachments/assets/35fbc234-9467-4edd-b6ea-a9d9c23657c2)

**Comment by Predidit** [comment]
程序现在的设计需要一个公开API提供的元数据作为索引。

Bangumi开放API只提供动漫相关的元数据，包含影视剧的公开API据我所知是没有的。所以这个问题是解决不了的。

如果有好的解决方案，也欢迎继续留言。

**Comment by YunnrEX** [comment]
豆瓣有几乎所有电视剧的信息，能否通过爬虫把豆瓣的数据保存到本地或某个服务器中，然后通过调用服务器里的数据返回给客户端，处理逻辑是：查询本地数据库->有返回数据，没有现爬数据并存储。另外加个定时爬取一次数据。但是豆瓣貌似有反爬虫系统，可以尝试增加ip代理池（不过服务器毫无疑问添加了很多成本，暂时没想到替代方法）

**Comment by Predidit** [comment]
使用爬虫是非常不稳定的，我希望在这种场合使用正常的HTTP API
