### ISSUE TITLE
升级软件之后，kazumi在播放任何视频前都会闪退

### ISSUE THREAD

**Issue by qwChenXing** [Predidit/Kazumi#57]
系统版本是 Windows 10.0.19045，软件版本是1.2.0
在闪退时没有报错

**Comment by qwChenXing** [comment]
在使用 1.1.9 时，软件表现的一切正常

**Comment by Predidit** [comment]
系统版本太老了，新版本有一个 Visual Studio C++ Runtime 的兼容性问题。

**Comment by Predidit** [comment]
不升级系统的话，单独升级 Visual Studio C++ Runtime 应该也行

**Comment by wang-bin** [comment]
问题在webview_windows_plugin.dll，安装最新的vcredist，或者c++项目用最新编译器编译时定义宏_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR就行

**Comment by Predidit** [comment]
> 问题在webview_windows_plugin.dll，安装最新的vcredist，或者c++项目用最新编译器编译时定义宏_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR就行

感谢您的指点

**Comment by Predidit** [comment]
这个问题应该在刚发布的 1.2.1 版本中修复

**Comment by wang-bin** [comment]
还是有问题，没pdb看不到挂在哪里。用老版本的webview_windows_plugin.dll替换没问题。你可以把老版本里的msvcp140.dll复制过来验证新编译的有没有崩溃问题

**Comment by Predidit** [comment]
真奇怪，我应该已经在 https://github.com/Predidit/flutter-webview-windows/commit/58deb21bd13292ebf04303f51682064da1c07780 修复了这一问题才对。

我还是先把发布版本替换为本地较低版本的MSVC构建的版本吧。

我的运行时版本比较高，您可以上传一下您用来测试的 msvcp140.dll 吗。

**Comment by wang-bin** [comment]
1.1.9的包里带了老的msvcp140.dll，可以用这个测

**Comment by Predidit** [comment]
github actions 构建的 1.2.2 版本经测试已经没有问题。
