### ISSUE TITLE
功能请求 清晰度

### ISSUE THREAD

**Issue by AnRamRan** [Predidit/Kazumi#58]
希望加上清晰度显示的功能(标题上）有些源画质模糊  很否则很浪费时间

**Comment by Predidit** [comment]
作为一个类似爬虫的程序，网页上得不到的信息我们自然也是拿不到的。

既然视频源网页的文本中没有标注清晰度，我们自然也无法在视频流被播放器解析之前得知其清晰度。

所以这个功能无法实现。
