### ISSUE TITLE
功能请求 自动更新&在托盘运行

### ISSUE THREAD

**Issue by Takenforgranted** [Predidit/Kazumi#59]
软件能否增加一键开启在打开软件时检查更新并自行进行下载更新的功能和在托盘中运行的功能？这样关于软件更新的情况就不需要上GitHub了，并且在视频播放时不会出现意外退出的状况了。

**Comment by Takenforgranted** [comment]
顺便问一下，这些本地个人用户数据（订阅的源、likes之类的）是存储在documents(win)里面的吗

**Comment by Predidit** [comment]
windows 上的本地数据按照惯例储存在 `C:\Users\username\AppData\Roaming\` 我觉得存在 Documents 里非常古怪。

自动更新功能会加入在下个版本中，目前的打算是默认禁用，似乎有些使用者不希望被自动更新打扰。

在 windows 平台上保留托盘的目的是？我有些没有搞清楚，因为在我看来最小化已经可以满足需求了。

视频播放意外退出指的是？有复现方法吗。

**Comment by Takenforgranted** [comment]
> windows 上的本地数据按照惯例储存在 `C:\Users\username\AppData\Roaming\` 我觉得存在 Documents 里非常古怪。
> 
> 自动更新功能会加入在下个版本中，目前的打算是默认禁用，似乎有些使用者不希望被自动更新打扰。
> 
> 在 windows 平台上保留托盘的目的是？我有些没有搞清楚，因为在我看来最小化已经可以满足需求了。
> 
> 视频播放意外退出指的是？有复现方法吗。

存在documents里面的也有其实……
自动更新倒是期待其实，毕竟检查版本的功能直接丢到About里面，貌似藏得太深了。
我的意思是可能视频播放一会儿后有啥事要pause一下，然后把页面×掉了发现就直接退出了，最小化到托盘可以考虑。

还有对于规则里面的源应该是有审核的吧？目前来看没有发现什么异常规则源里面刷新出来的番都是正常的。会不会有人拿里番网站做规则源直接？不过即使是里番bangumi也是有相关信息的。

**Comment by Predidit** [comment]
那存在 documents 里还是现在的位置更好呢，理由是什么呢。

最小化到托盘似乎是个不错的注意，但是用快捷键而不是按钮是不是更加合理一点。

提交到仓库的公开规则会审核的。

**Comment by Takenforgranted** [comment]
> 那存在 documents 里还是现在的位置更好呢，理由是什么呢。
> 
> 最小化到托盘似乎是个不错的注意，但是用快捷键而不是按钮是不是更加合理一点。
> 
> 提交到仓库的公开规则会审核的。

存在哪里其实随意，我不太想争论这一点。
其实点页面上的×就可以最小化到托盘了，那个快捷键应该就是所谓的老板键吧。

**Comment by Predidit** [comment]
1.2.2 已经发布，包含以上功能。
