### ISSUE TITLE
PC端历史记录&同步设置存在问题

### ISSUE THREAD

**Issue by hoppinging** [Predidit/Kazumi#61]
本人纯小白，在云服务器上搭建了Webdav服务试图实现多端同步看番的功能。
虽然软件连接成功后在服务端生成了kazumiSync文件夹，也给了读写权限，但是观看记录同步一直失败，一看历史记录才发现虽然看了但是没有生成观看记录。
不知道有没有人和我遇到同样的问题，该如何解决。

**Comment by Predidit** [comment]
从视频观看页面回退到视频详情页面时会触发同步。

尝试进行这个操作，然后检查 webdav 中kazumiSync 下面的 histories.tmp 文件的时间戳是否有变化。

**Comment by hoppinging** [comment]
kazumiSync下没有文件，是否是由于没有观看记录导致的。事实上我有观看过影片但软件未生成观看记录。

**Comment by Predidit** [comment]
这看上去是一个webdav权限相关的问题，你可以换一个公共 webdav 服务看看是否解决问题，如果解决的话，可以确定是自建 webdav 的问题

**Comment by hoppinging** [comment]
出现了同样的情况，使用坚果云也能生成kazumiSync文件夹，但没有任何内容。问题应该存在于无法正常生成观看记录，我反复进入播放页面并在观看一段时间后点击左上角返回，还是没有任何记录。

**Comment by hoppinging** [comment]
尝试用管理员模式启动，能够生成历史记录。

**Comment by Predidit** [comment]
看上去似乎程序被安装在了非管理员不可写的目录里。移动到正常的位置应该可以修复。

**Comment by hoppinging** [comment]
程序安装在D盘，这没什么问题，因为所有本地用户都可写入。
看之前的issue，数据存储的目录似乎在`C:\Users\username\AppData\Roaming\`中？但我无法通过名称找到。
目前我的解决办法是令快捷方式以管理员启动。

**Comment by Predidit** [comment]
username 需要替换为你的用户名。

我没有办法复现这个问题，我会保持这个 Issue 为开启状态，如果有其他人遇到这个问题，欢迎在这里回复。

**Comment by hoppinging** [comment]
替换过了的，，无法通过名称找到的意思是我不知道数据存储文件夹确切的名称

**Comment by WhiteXero** [comment]
> 替换过了的，，无法通过名称找到的意思是我不知道数据存储文件夹确切的名称

数据存储文件夹的位置是 `%APPDATA%\com.example\kazumi` 。

**Comment by 3234874524** [comment]
我也遇到这个问题了
![2T(~PO){V~Y007KXPXFNPSY](https://github.com/user-attachments/assets/ca58cf7d-db53-43a1-bc4d-c702a6f6e530)

**Comment by 3234874524** [comment]
手机端就可以正常同步，但是电脑就会这样
