### ISSUE TITLE
能不能出个规则写法的教程

### ISSUE THREAD

**Issue by shiyun0001** [Predidit/Kazumi#63]
看着这个实例规则，没看懂，希望作者大大能出单独个教程演示下

**Comment by shiyun0001** [comment]
作者大佬，能不能单独对一个规则弄个简单的教程，b站上有，但学了一点不知道那些对应的咋找，希望软件首页可以搞成也是list的形式，可以选择不同的网站作为首页，有对应的网站的分类选择，像我下方图片那样子的，
<img width="750" alt="{3C37ACBE-97EE-4678-B53D-7FBDC96703A5}" src="https://github.com/user-attachments/assets/eb010f7e-afb0-4220-90aa-a2d280fc1f81">
类似这种规则首页写法的
var rule = {
  title: '樱之空',
  host: 'https://www.skr2.cc/',
  url: '/vodshow/fyclass--------fypage---.html',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
   class_name: '全部&国漫&日漫&美漫&桜歌&桜剧',
   class_url: '1&47&46&85&3&32',
  play_parse: true,
  lazy:``,
  limit: 6,
  推荐: '*',
  double: true,
  一级: 'body&&.ranklist_thumb;a&&title;a&&data-original;.text_right&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.star_tips&&Text',
    img: '.lazyload&&data-original',
    desc: '.data:eq(1)&&Text;.data:eq(2)&&Text;.data:eq(3)&&Text',
    content: '.desc&&Text',
    tabs: 'body&&.play_source_tab&&a:not(:contains(排序))',
    tab_exclude:'',
    lists: '#playlistbox:eq(#id)&&li',
    url:".m_background&&style",
  },
  搜索: 'body&&.searchlist_item;h4&&Text;a&&data-original;.text_right&&Text;a&&href',
}，感觉会比现在随机的首页好点，直接把网站的首页分类给搬来了

**Comment by Predidit** [comment]
现在的方案是为了尽可能简化规则的编写。

现在的xpath选择器只需要5行，图中这样的话就相当麻烦了。
