### ISSUE TITLE
希望可以加一个追番的状态，类似于B站

### ISSUE THREAD

**Issue by HBlihaoyu** [Predidit/Kazumi#64]

**Comment by Predidit** [comment]
这个功能做不了，视频源不可能为我们提供番剧更新相关的订阅或是回调。

我们唯一可以检测当前更新进度的方式是主动连接各个视频源，这一过程的性能开销很大，并且会有超高的请求频率，会阻塞视频源，或是被视频源拉黑IP。

**Comment by Predidit** [comment]
在 1.4.7 实现
