### ISSUE TITLE
界面兼容性有问题，希望能适配一下平板

### ISSUE THREAD

**Issue by lizc2333** [Predidit/Kazumi#65]
如下所示，有两个界面显示异常，侧边栏也随机隐藏

https://github.com/user-attachments/assets/34414bcc-746b-4325-9a60-ba9e1b54df8a

**Comment by Predidit** [comment]
安卓平板是对横屏适配的，把平板横过来效果就很好了，我不知道 ROM 为什么没有自动横屏，你的系统是？

可以左右滑动来切换选项卡是一个Bug，我会在下个版本中修复。

**Comment by Predidit** [comment]
1.2.2 已经发布，包含以上修复。

**Comment by lizc2333** [comment]
> 1.2.2 已经发布，包含以上修复。

谢谢，辛苦了
