### ISSUE TITLE
关于视频播放出了一些小问题

### ISSUE THREAD

**Issue by Takenforgranted** [Predidit/Kazumi#67]
我在最近使用kazumi观看番剧**しかのこのこのここしたんたん**的过程中，有时候视频源的加载会出现一些卡顿。加载时间过长后我会直接叉掉视频界面然后重进。
然后问题就出在这里，我在每次没加载出来播放一半卡在那里后叉掉了视频界面打算重进，但是页面出现了卡顿，软件出现了闪退。
希望这个bug能得到修复。

**Comment by Predidit** [comment]
有比较详细的复现方法吗，我复现了几次没复现出来。android 还是 windows 呢。

**Comment by Takenforgranted** [comment]
WINDOWS的，有的时候视频播放放着放着然后加载卡了，然后就进度条直接拉满跳转到下一集了，或者是在我叉掉之后kazumi就卡了闪退了。可能是软件或者规则源的问题，也有可能是我打开的其他软件造成的冲突。

**Comment by Takenforgranted** [comment]
> 有比较详细的复现方法吗，我复现了几次没复现出来。android 还是 windows 呢。

WINDOWS的，有的时候视频播放放着放着然后加载卡了，然后就进度条直接拉满跳转到下一集了，或者是在我叉掉之后kazumi就卡了闪退了。可能是软件或者规则源的问题，也有可能是我打开的其他软件造成的冲突。

**Comment by xsfx0313** [comment]
@Predidit 有没有可能视频编码问题，如果视频网站上是 AV.1 的编码。而某些用户设备不支持的话可能会出问题？（仅为一个无知的外行的猜测）

**Comment by Predidit** [comment]
@Takenforgranted 这个问题已经在今天发布的 1.2.5 版本中解决。

@xsfx0313 原因不是编解码支持的问题，如果是不支持的格式，那么影片根本不会开始播放。

这个问题来自 fvp 插件对 ffmpeg 编解码库的错误默认配置。

一些视频源在每加载完一个片段就会主动终止连接，直到客户端发起重连，这种行为一般很少见，但是是很多小型视频站点的常规行为。

fvp 插件默认配置为被主动终止连接时不重连，这导致了后续的一系列问题。

至于为什么只影响 windows/linux 因为这两个平台没有flutter官方视频播放器支持，其视频播放依赖fvp插件。

**Comment by xsfx0313** [comment]
谢谢解答我的问题😄

**Comment by roincode** [comment]
windows1.7.5.0视频卡顿，加载太慢，把它扔后台里才能加载的快一点，能不能尽快搞定一下
