### ISSUE TITLE
无法显示搜索结果

### ISSUE THREAD

**Issue by azxcvn** [Predidit/Kazumi#68]
开发者你好，许久未见

我今天尝试更新规则，发现在浏览器内可正常访问网站，搜索结果正常，在软件内却读取不到结果

举个例子

girigirilove网站   https://anime.girigirilove.com/   ，浏览器内可打开，软件内读取不到搜索结果

是否语法有了更新，searchlist不再是这样填写，故旧版语法读取不到结果
![bug反馈](https://github.com/user-attachments/assets/a92ecdb8-1e97-4021-839c-07b5b6d00eda)

期待你的回复

**Comment by azxcvn** [comment]
gl如下
![fk](https://github.com/user-attachments/assets/57888b5d-41a4-4695-b01a-c0c44c8b4877)

**Comment by azxcvn** [comment]
抱歉，没注意到稀饭与girilove均需要梯子，国内直连无法加载，搜索结果加载不出也是情理之中了
![image](https://github.com/user-attachments/assets/bb0c53b6-6f30-430d-8fde-571abc6adcf8)
不过我gua挂了梯子后软件内还是找不到搜索结果，是软件不支持代理吗

**Comment by Predidit** [comment]
我没有更新规则语法。

按照我这边的测试， girigirilove 是可以直连访问的，也可以正确得到搜索结果。

girigirilove的规则需要更新的原因是在你那边无法得到任何检索结果吗。

**Comment by Predidit** [comment]
关于代理的问题。

App默认都是不走系统代理的。图中使用的那个流行的代理程序设置的系统代理。一般遵守系统代理设置的只有浏览器。

我不知道你那边直接访问 girigirilove 会不会弹验证码，如果有验证码也是搜索不了的。

网络环境也可以测试一下，例如手机给电脑开热点能不能正常检索。

**Comment by azxcvn** [comment]
已找到问题，我的ip被封禁

我尝试了一下连接国内其他节点ip

稀饭，Girilove均可正常浏览器访问

使用本机WiFi或者流量直连均无法打开网站

**Comment by azxcvn** [comment]
问题解决，我关闭此议题
