### ISSUE TITLE
一些建议和发现的问题

### ISSUE THREAD

**Issue by ymqng** [Predidit/Kazumi#69]
## 我用的设备是华为的平板，先说问题:

1.  **这里设置界面的标签在横屏模式下被挡住了最后一个的一半，虽然把屏幕竖起来就能看到了，但还是希望可以滑动设置界面来看到被挡住的部分**

https://github.com/user-attachments/assets/a03e4b77-e833-443d-ba16-fc2f5cb05ba1

2.**在历史记录界面，横屏模式下的[番剧信息]会超出绿色框的范围，如下图**

![横屏展示](https://github.com/user-attachments/assets/531e4687-a337-4bc4-aa0b-f7ab2805cb30)

**竖屏界面如下图:**

![竖屏展示](https://github.com/user-attachments/assets/f11fa1e6-418b-4502-b9be-fd781a233c8c)

补充:经过实测，即使退出软件并删掉后台，以竖屏模式再次进入后打开历史记录界面依然如此。

3.在很多界面中，将屏幕向右滑会进入一些奇怪的界面，例如:

- 在推荐页向右划会进入一个纯灰色的界面，继续右划就会切换到左下角导航栏的下一界面。
- 在播放页或番剧的详情页左右滑动会进入……描述不出来，看视频吧

https://github.com/user-attachments/assets/8dab8daa-c853-4fe4-a376-0376751d72ca

### 共同点
不论那种情况，只要右划，左下角的导航页就会消失。如果想返回就只能退出软件再重进。不小心手滑还是很麻烦的。

3.刚才录视频和截屏的时候又发现了一个问题，不知道什么原因，总之是进了软件胡乱点了几下。结果左下角的导航栏按键锁定在设置了，能正常的通过导航栏切换页面，也有按钮被点击的画面，但没有按钮切换的动画，就一直是锁定在设置上。刚才又试了几次都没有复现，应该是概率事件。视频如下:

https://github.com/user-attachments/assets/07e4184b-be01-4987-9f4d-d7d39503b45a

##再提一点小小的建议

- 建议全屏播放模式下加一个双击暂停的功能，个人感觉这个功能还是很实用的。

**Comment by Predidit** [comment]
这台平板的分辨率是多少

**Comment by ymqng** [comment]
> 这台平板的分辨率是多少

1920×1200

**Comment by Predidit** [comment]
这台平板的分辨率比现在主流平板低。主流的2K屏幕平板没有历史记录溢出的问题。

我会尝试修复这一问题，但不保证补丁可用。

导航栏相关问题的补丁已经提交到仓库，等待下个版本发布。

**Comment by ymqng** [comment]
> 这台平板的分辨率比现在主流平板低。主流的2K屏幕平板没有历史记录溢出的问题。
> 
> 我会尝试修复这一问题，但不保证补丁可用。
> 
> 导航栏相关问题的补丁已经提交到仓库，等待下个版本发布。

谢谢
