### ISSUE TITLE
webdav同步

### ISSUE THREAD

**Issue by FENG6565** [Predidit/Kazumi#72]
webdav同步是只能同步历史记录吗？能不能把收藏的番剧也同步一下，求

**Comment by Predidit** [comment]
和 #54 重复

**Comment by FENG6565** [comment]
> 和#54重复

好吧，那存放追番列表的文件在电脑的哪个位置啊？我能不能手动同步呢？

**Comment by Predidit** [comment]
数据目录在 `%APPDATA%\com.example\kazumi`

这个目录下面的 /hive/favorites.hive 是追番数据。

**Comment by zhang-ziang** [comment]
请问安卓端这个文件放在哪个目录下面？我先装的安卓端😂

**Comment by Predidit** [comment]
> 请问安卓端这个文件放在哪个目录下面？我先装的安卓端😂

/data/user/0/com.predidit.kazumi/files/hive

**Comment by zhang-ziang** [comment]
感谢。这个目录的话，好像没root的话得插线连电脑才能访问了

**Comment by Predidit** [comment]
> 感谢。这个目录的话，好像没root的话得插线连电脑才能访问了

新的 android 储存机制是这样的，这个目录一般只能由相应的应用程序或具有适当权限的系统进程访问。

**Comment by zhang-ziang** [comment]
没有root访问和替换都还是很麻烦，以后会考虑出一个类似tachiyomi那样的导出配置的功能吗🤣

**Comment by Predidit** [comment]
> 没有root访问和替换都还是很麻烦，以后会考虑出一个类似tachiyomi那样的导出配置的功能吗🤣

会考虑的
