### ISSUE TITLE
希望可以增加一个“收藏”的界面

### ISSUE THREAD

**Issue by SCP-XC** [Predidit/Kazumi#73]
目前只有一个“追番”界面，我理解的意思是目前正在追的番剧，看完了就可以取消掉了。
所有我想是否可以增加一个界面，可以展示自己曾经看过了的番。
目前加入“追番”界面的流程是：在主页搜索番剧名称，找到对应的番剧图片点进去后，在详情页的番剧图片的右下角会有一个“小心心”，点击就可以加入“追番”界面列表。我的想法是在这个“小心心”旁边增加一个“五角星”，就像b站的收藏按钮一样，点击后加入新增的“收藏”界面。

**Comment by xsfx0313** [comment]
其实也可以像目前b站一样允许添加手动一个标记：

想看 正在看 看过

同时可以在追番界面通过标签筛选，默认筛选和选择正在看。我认为这也是一个不错的方案。

我认为可以在进入番的详情页中的“小心心”的右侧添加一个下拉框来修改标签，在追番界面用md3原生的筛选器来筛选，默认选择正在看的筛选模式。如果能在外部添加一个小条直接展示目前的追番选择就更好了。（如图）
![IMG_20240725_144849.jpg](https://github.com/user-attachments/assets/bb26a170-20e9-4a7c-afe8-d9f4dd992aba)

**Comment by zeoxion** [comment]
如果有这种需求用 bangumi 不是更好咩 [doge]

**Comment by Predidit** [comment]
在 1.4.7 实现
