### ISSUE TITLE
新增视频控制面板锁定

### ISSUE THREAD

**Issue by baihengaead** [Predidit/Kazumi#76]
- 增加播放器控制栏锁定功能
- 增加可以 导入/导出 历史播放记录与收藏列表 的功能

**Comment by baihengaead** [comment]
请问能否在追番页面 添加类似B站的〖想看〗〖在看〗〖看过〗Tab标签 的功能，方便管理追番列表

**Comment by YCZ01111** [comment]
> 请问能否在追番页面 添加类似B站的〖想看〗〖在看〗〖看过〗Tab标签 的功能，方便管理追番列表

你应该新开一个issue～

**Comment by YCZ01111** [comment]
锁定功能还没出（哭）

**Comment by baihengaead** [comment]
> 锁定功能还没出（哭）

导致看番的时候都不敢随便碰屏幕QAQ

**Comment by Predidit** [comment]
锁定功能不出意外地话将出现在 1.3.6 中

**Comment by Predidit** [comment]
锁定功能在 1.3.6 实现

导入导出功能在 #167 追踪
