### ISSUE TITLE
关于IOS版全屏横屏异常的问题

### ISSUE THREAD

**Issue by 10020099** [Predidit/Kazumi#77]
https://github.com/user-attachments/assets/fb8a0174-72da-4b87-8b8e-ecdb29c0a15f

如视频展示，ios版在进入软件后第一次全屏观看可以正常横屏，而一旦退出播放或者取消全屏，就再也无法横屏，除非重启应用，希望这个问题能够修复一下

**Comment by Predidit** [comment]
ios版本是多少，kazumi版本是多少

**Comment by Predidit** [comment]
这和用什么方法退出无关吗，就是无论点按全屏按钮退出，还是使用手势退出，都会触发bug吗

**Comment by 10020099** [comment]
ios版本为前段时间新发布的ios18公测版，kazumi版本是1.2.2，这个bug的话，无论什么退出方式都会引发这种情况，除非是重启软件，不然还会一直保持这种状态

**Comment by Predidit** [comment]
补丁已经提交到仓库，等待 1.2.3 版本发布。
