### ISSUE TITLE
希望可以出一个电视版

### ISSUE THREAD

**Issue by perperG** [Predidit/Kazumi#79]
尝试直接在电视安装安卓版，失败了，电视是安卓9版本。如果电视也能用kazumi就完美了，现在没找到可以看弹幕的追番软件

**Comment by Predidit** [comment]
最低支持版本是安卓5，虽然建议使用 andorid10 以上的版本，但是低一些也不应该有问题的。

报错是什么样的呢。

**Comment by perperG** [comment]
应用不兼容此设备
请下载其他版本应用后重试，错误码:(-113)

**Comment by Predidit** [comment]
这确实是一个兼容性问题，按照我对这个错误提示的理解，这是试图在 32 位设备上安装 64 位应用。

看上去这台电视有些过时了，32位设备现在已经很少见了。

这个项目可以构建兼容 32 位安卓设备的版本，但因为32位设备已经过时了，所以我并没有发布32位版本。

如果你确实需要的话，可以尝试自行构建，如果本地没有构建环境的话，可以直接分叉此项目，对 workflow 文件稍做修改，使用 github actions 进行远程构建。
