### ISSUE TITLE
电视端无法选集

### ISSUE THREAD

**Issue by perperG** [Predidit/Kazumi#80]
我重新构建了一个32位版本的apk,电视可以安装使用。但是有一个致命问题，在播放界面无法像手机一样选集和选择播放列表，并且无法仅通过使用遥控器打开弹幕按钮，也无法使用暂停按钮。
除此之外，主界面番剧海报过大，只能显示一半。

**Comment by Predidit** [comment]
android TV 不是 flutter 的目标平台，适配的心智负担很高。所以暂时没有适配 androidTV 的计划。

不过我可以告诉您以上问题的大概解决方案，如果您有兴趣的话。

主界面番剧海报过大的问题，这应该是由于电视相对于平板电脑比较特殊的分辨率比例，导致程序误判为手机而非平板电脑，如果程序判定为平板电脑，界面即可正常呈现。对应逻辑在 `/lib/utils/utils.dart` 的 `isCompact()` 函数，您可以将其改为一直返回 false 来强制启用非紧凑布局。

接受遥控器指令可以使用 `RawKeyboardListener` 控件。此外要使遥控器方向键工作，需要重新处理程序的焦点，并为主要控件添加被选中时的动画。这非常繁琐。
