### ISSUE TITLE
pc端图标显示有锯齿

### ISSUE THREAD

**Issue by rcyuuki** [Predidit/Kazumi#81]
pc端图标在桌面和开始中显示有锯齿，看起来不太美观，希望可以调整一下
![image](https://github.com/user-attachments/assets/721e5689-e569-46f0-92fa-99a0f1bd1fdd)

**Comment by Predidit** [comment]
这个问题只能更换图标解决，这个图标本身对比度不高，缩放时无论原图质量怎么样都会变成这样。
