### ISSUE TITLE
播放视频不开全屏的话，会有闪屏花格，闪一下就没了，win端，播放的是散华礼弥，不知道是播放原问题还是显示bug？

### ISSUE THREAD

**Issue by apmggv** [Predidit/Kazumi#83]

**Comment by Predidit** [comment]
如果全屏和非全屏模式下表现不一致，那就不是播放源的问题，我倾向于这是一个显示bug。

这种问题一般涉及驱动和硬件，您的CPU和显卡是？

您是否尝试过升级驱动？

**Comment by apmggv** [comment]
我的显卡是4070s u的话是13600kf 显示器分辨率2k

**Comment by Predidit** [comment]
此问题在 1.2.3 版本修复
