### ISSUE TITLE
我们是girigiri爱动漫网的希望拉你们入伙开发项目🥺💌

### ISSUE THREAD

**Issue by girigirilove2022** [Predidit/Kazumi#85]
📧联系邮箱：girigirilove2022@gmail.com
💮大佬的技术真的很强，希望可以一起搭建最棒的追番体验

**Comment by Predidit** [comment]
感谢您的认可。我是爱站的资深用户，爱站的追番体验真的超棒，清晰度可以说独树一帜，感谢你们那么长时间的运营维护。

我不是很清楚其他贡献者的想法，但就我个人而言，由于精力问题，不是很有动力再开坑一个新的 flutter 项目。每个人的业余时间都是有限的，非常抱歉不能参与到你们的项目中来。

**Comment by girigirilove2022** [comment]
好的，如果有空了随时欢迎你们❤️

**Comment by girigirilove2022** [comment]
另外我看软件是默认有爱站的视频源，因为我们也是用爱发电的组织，担心服务器开销会加大，如果可以的话希望可以适当在软件推广一下我们的网站，感激不尽🙇‍♀️

**Comment by Predidit** [comment]
您希望是什么样的形式呢

**Comment by girigirilove2022** [comment]
![QQ截图20240723142922](https://github.com/user-attachments/assets/ac36d42d-7a0d-4454-83fc-0d19735c57dd)
在首页左上角置顶加入我们的海报和文案点击为介绍和网站网址 我们会提供和现有番剧封面一样的尺寸的海报

**Comment by girigirilove2022** [comment]
不知能否实现

**Comment by Predidit** [comment]
这种磁贴式的方式侵入性比较高。

我可以在APP的关于页面和仓库README文件中为您添加致谢，或者将您移出默认规则。

**Comment by girigirilove2022** [comment]
没有其他方案了吗🤣

**Comment by girigirilove2022** [comment]
![QQ截图20240723145500](https://github.com/user-attachments/assets/028055ae-a282-49ec-a38a-b351d158fee8)
bi'r比如这里加个 星野爱 的q版 然后鼠标移动是爱站宣传，点击跳转（也可以不要）
![QQ截图20240723145653](https://github.com/user-attachments/assets/b2e7aebb-9872-44b3-b46a-03f631c136e1)
像是这样的

**Comment by Predidit** [comment]
如果这个项目是爱站的第三方客户端，那您的任何要求我都会尽量满足，包括添加贴片广告。

但这个项目其实更依赖Bangumi API和DandanPlayer 开放API。

首页呈现的内容理论上和爱站完全没有关系，添加在这里是不合理的。我可以为您在番剧详情页面，爱站相关选项卡下添加跳转到爱站的按钮，这样可以吗。

**Comment by girigirilove2022** [comment]
这样可以的，拜托啦

**Comment by girigirilove2022** [comment]
打扰了，开发者朋友，由于带宽费用增加过高达到了10天1万rmb的程度，麻烦您将我们移出默认规则，拜托了

**Comment by girigirilove2022** [comment]
这样下去我们站将无法存活QAQ
