### ISSUE TITLE
ios上怎么用啊

### ISSUE THREAD

**Issue by 1075725846** [Predidit/Kazumi#9]
有教程吗，想在平板上看🥺🥺🥺

**Comment by Predidit** [comment]
本项目使用 flutter 开发，且代码中已经做好了 iOS 的适配。

但是现在 iOS/iPadOS 安装未签名 ipa。非常非常麻烦，并且经常失效。

由于大部分使用者应该不能安装 ipa，所以本项目没有提供 iOS/iPadOS 的编译产物。

如果您非常想在平板上使用，并且能解决签名问题的话，可以参考 flutter 编译指南进行编译，而后自行签名安装。
