### ISSUE TITLE
规则制作问题

### ISSUE THREAD

**Issue by YunnrEX** [Predidit/Kazumi#91]
请问一下，以search.php为搜索url的网页该如何制作规则

**Comment by Predidit** [comment]
举个例子？

**Comment by YunnrEX** [comment]
http://agedm5.com/search.php
这个网站搜索只会显示这个网址

**Comment by YunnrEX** [comment]
> 举个例子？

http://agedm5.com/这个网站不会显示搜索结果，只会在网址后面加search.php这个后缀，不知道如何用url方式来直接调用他

**Comment by Predidit** [comment]
这种使用 POST 传参的站点暂不支持，后续会加入支持。

**Comment by xuze1993** [comment]
顶  也遇到了

**Comment by Predidit** [comment]
1.3.0 版本开始支持 POST 传参的检索

启用高级选项的POST传参，在 searchURL 中按照 GET 传参的方式拼接 URL 即可，参考规则仓库中的 mandao 规则

**Comment by oldsento** [comment]
> 1.3.0 版本开始支持 POST 传参的检索
> 
> 启用高级选项的POST传参，在 searchURL 中按照 GET 传参的方式拼接 URL 即可，参考规则仓库中的 mandao 规则

具体怎么这整啊，
