### ISSUE TITLE
美观且可隐藏的日志输出

### ISSUE THREAD

**Issue by Silicon7921** [Predidit/Kazumi#92]
1.
![D88BD6781228DB337365E352387A5539](https://github.com/user-attachments/assets/02da0a9d-77cd-451e-9bd9-9f3d92f97919)
希望这些奇怪的输出能够不要贴脸（比较影响观感，而且上面的输出会被下面的顶掉也不方便查看），而是在软件的关于-日志处输出。这些报错似乎也拖慢了视频加载速度。
2.希望能记住弹幕开关状态，不必每次都手动打开弹幕。
3.配色方案支持动态取色会很酷（笑）比如根据系统主题或者壁纸取色

**Comment by Predidit** [comment]
1. 这不是报错，这是正常的日志输出，内容大概是获取视频源的过程。这并不会拖慢视频加载速度。

2. 听上去是个好主意，这会包含在下个版本中。

3. 和 #2 重复，这个问题同样在 #62 中被提及，有需要解决的问题。

**Comment by YunnrEX** [comment]
很简单，把这个换成转圈圈用户就接受了

**Comment by xsfx0313** [comment]
似乎可以添加一个设置选项，日志默认为开，但可以在设置里关掉输出，当然，应在关闭时提示： `此日志可以帮助判断问题，在提交错误报告截屏是时应为开启状态` 之类的玩意。😆

**Comment by Predidit** [comment]
1.3.5 版本现在拥有美观且可隐藏的日志输出
