### ISSUE TITLE
[Linux] 使用反馈

### ISSUE THREAD

**Issue by madoka773** [Predidit/Kazumi#94]
1. 经典的 tray icon 问题（左右键均不能用，没有显示软件的自定义图标）

**Comment by madoka773** [comment]
好像没发现别的问题了

**Comment by madoka773** [comment]
Tested on flatpak gnome 46 platform
OS: Fedora 40 Silverblue

**Comment by Predidit** [comment]
感谢您的反馈，关于花屏问题，您在使用什么显卡，如果在使用开源驱动的话，更新内核到主线是否能解决问题。

关于 webview 支持的问题。这需要在GTK侧进行离屏渲染并和flutter侧进行较为精巧的互操作来实现 GTKWebkit 在 flutter 界面上的嵌入。

虽然听上去很简单，但这实际上是很复杂的事情，还牵扯到 Cario 内容和 openGL 内容混合的问题，以及垂直同步的处理。

我并没有能力处理这些问题。现在所使用的实现在 Predidit/linux_webview_window 。这是一个不包含 webview 渲染的简单实现。您如果在这方面有经验的话，可以在这里PR。

**Comment by madoka773** [comment]
> 感谢您的反馈，关于花屏问题，您在使用什么显卡，如果在使用开源驱动的话，更新内核到主线是否能解决问题。
> 
> 关于 webview 支持的问题。这需要在GTK侧进行离屏渲染并和flutter侧进行较为精巧的互操作来实现 GTKWebkit 在 flutter 界面上的嵌入。
> 
> 虽然听上去很简单，但这实际上是很复杂的事情，还牵扯到 Cario 内容和 openGL 内容混合的问题，以及垂直同步的处理。
> 
> 我并没有能力处理这些问题。现在所使用的实现在 Predidit/linux_webview_window 。这是一个不包含 webview 渲染的简单实现。您如果在这方面有经验的话，可以在这里PR。

我这没有花屏的问题，不过稍后我会提交个打包deb的pr

**Comment by madoka773** [comment]
#96

**Comment by Predidit** [comment]
我看到这个PR被标记为草稿，您的工作还没有完成，是吗？

**Comment by madoka773** [comment]
检查了一下应该好了
