### ISSUE TITLE
Release 明确各个软件包的架构

### ISSUE THREAD

**Issue by pugaizai** [Predidit/Kazumi#98]
这样更方便各种电脑的用户找到自己需要的软件包进行下载

**Comment by Predidit** [comment]
flutter 目前在 windows 平台上不支持交叉编译，github actions 也没有提供 windows arm 容器。所以目前 windows x86 构建是 windows 平台上唯一可用构建。且考虑到 windows arm 提供兼容层，当前构建理论上可以在 windows arm 上运行，故不做区分似乎是合理的。

Linux 平台的情况和上述类似。
